hotosm/tasking-manager

client/package.json
shippable.yml
tests/client/karma.conf.js

Ensures JS unit tests run
Upgrade OL3-geocoder

Upgrade OL3-geocoder

---

client/app/admin/create-project/create-project.controller.js
client/app/admin/create-project/create-project.html
client/app/services/draw.service.js
client/app/services/project.service.js
tests/client/unit/app/admin/create-project/test.create-project.controller.js
tests/client/unit/app/services/test.project.service.js

Split specific area into smaller tasks.
Also:
- AOI and task grid are now MultiPolygon instead of Polygon
- AOI validation support for MultiPolygon + tests added

Ht 24 split tasks

---

server/models/project.py
server/models/task.py
server/models/utils.py

BUGFIX - Force timestamp to refresh when adding taskhistory items

Force timestamp refresh on taskhistory

---

client/app/admin/create-project/create-project.controller.js
client/app/admin/create-project/create-project.html
client/app/services/map.service.js
client/assets/styles/sass/_map.scss
client/index.html
client/package.json
client/taskingmanager.config.json
tests/client/karma.conf.js

- Added MapBox aerial layer and layer switcher - this will now show up on any map
- Added button to reset the grid (project creation)

Ht 17 aerial layer

---

server/api/projects_api.py
server/models/dtos/project_dto.py
server/models/postgis/project.py
server/models/postgis/statuses.py

Add ability to update priority

POST Project - Add Priority

---

client/assets/styles/sass/_map.scss
client/package.json

Change OL layerswitcher plugin version to one that is available on a CDN as well

change layerswitcher to available cdn v

---

server/__init__.py
server/api/mapping_apis.py
server/api/project_admin_api.py
server/models/dtos/project_dto.py
server/models/postgis/project.py
server/services/project_service.py
tests/server/integration/models/test_project.py
tests/server/unit/models/test_project.py
tests/server/unit/services/test_project_service.py

Initial work on getting Projects for admins

Project Admin API GET Project 1

---

client/app/project/project.controller.js
client/app/project/project.html
client/app/services/style.service.js
client/app/services/task.service.js

- ability to lock a task for  mapping
- ability to stop mapping without chaning status with a comment
- ability to mark task as done with a comment
TODO
- Integration with editors
- Refactor when enhanced task api's are available

Ht 39 start stop mapping

---

server/api/mapping_apis.py
server/models/dtos/project_dto.py
server/models/postgis/project.py
server/services/project_service.py
tests/server/integration/models/test_project.py

Further work to return project info

Project GET Apis

---

server/api/mapping_apis.py
server/models/postgis/project.py
server/services/project_service.py

Make GET Mapper Project API locale aware

Get locale from header on GET Mapper Project

---

client/app/project/project.controller.js
client/app/project/project.html
client/app/services/task.service.js

Refactor start and stop mapping to use task lock/unlock for mapping api

use-new-task-lock-api

---

server/models/dtos/project_dto.py
server/models/postgis/project.py
server/services/mapping_service.py
tests/server/integration/models/postgis/test_project.py
tests/server/unit/services/test_mapping_service.py

Handle partial translations in mapping service.  Add tests.

Mapping Service now handles partial translations

---

server/__init__.py
server/api/validator_apis.py
server/models/dtos/task_dto.py
server/models/dtos/validator_dto.py
server/models/postgis/task.py
server/services/mapping_service.py
server/services/validator_service.py
tests/server/unit/services/test_mapping_service.py
tests/server/unit/services/test_validator_service.py

Initial work on Validation APIs
Add Lock tasks for validation api

Validate APIs Part 1

---

client/app/admin/create-project/create-project.controller.js
client/app/admin/edit-project/edit-project.controller.js
client/app/contribute/contribute.html
client/app/project/project.controller.js
client/app/taskingmanager.app.js

Change the URLs to make them nicer :)
e.g. 
http://localhost:3000/project/9
http://localhost:3000/admin/edit-project/9

change URLs for contributing and editing

---

server/__init__.py
server/api/swagger_docs_api.py
server/api/validator_apis.py
server/models/dtos/validator_dto.py
server/models/postgis/statuses.py
server/models/postgis/task.py
server/services/mapping_service.py
server/services/validator_service.py
tests/server/unit/services/test_mapping_service.py
tests/server/unit/services/test_validator_service.py

Add API for UnlockAfterValidation
Add necessary validation
Refactor sethistory into PostGis model

Addition of UnlockAfterValidation API

---

client/app/project/project.html
client/app/taskingmanager.app.js
client/assets/styles/sass/_project.scss
client/assets/styles/sass/taskingmanager.scss
client/index.html
client/package.json
tests/client/karma.conf.js

V1 of tidy up of sidebar for project + usage of Moment.js for task history + ordering task history. A npm install is necessary to include the new libs.

Ht 54 polish mapping

---

client/app/project/project.html
client/assets/styles/sass/_helpers.scss
client/assets/styles/sass/_project.scss
client/assets/styles/sass/_structure.scss
client/assets/styles/sass/_variables.scss
client/assets/styles/sass/taskingmanager.scss
client/index.html

"full screen" project page. More space for the sidebar and map. Limit size of images to width of the sidebar.

Ht 54 polish mapping v2

---

client/app/admin/edit-project/edit-project.html

Renamed tags to metadata after a discussion with Blake and added fields for types of mapping to the metadata section

rename tags to metadata and add fields for types of mapping

---

README.md
server/__init__.py
server/api/authentication_apis.py
server/config.py

Auth Part 2 - Enhance security and docs

---

client/app/project/project.controller.js
client/app/project/project.html
client/app/services/editor.service.js
client/app/services/geospatial.service.js
client/index.html
tests/client/unit/app/services/test.editor.service.js
tests/client/unit/app/services/test.geospatial.service.js

Start of being able to launch the iD editor. I'll create tickets for the TODOs.

Ht 57 id editor

---

client/app/project/project.controller.js
client/app/services/map.service.js
client/assets/styles/sass/_map.scss

Add overview map on /project/project_id page. It is hidden initially (click on the button on the left hand corner of the map to see it)

add overview map

---

README.md
requirements.txt
server/api/project_admin_api.py
server/api/user_apis.py
server/api/utils.py
server/models/postgis/user.py
server/services/authentication_service.py
server/services/user_service.py
tests/server/unit/services/test_authentication_service.py

This PR is the initial work that allows us to validate tokens supplied with API requests

Add ability to authenticate tokens on API endpoints

---

server/api/validator_apis.py
server/models/dtos/validator_dto.py
server/services/validator_service.py

Validation endpoints are now authorized

Add auth to validation

---

manage.py
server/api/mapping_apis.py
server/models/postgis/project.py
server/models/postgis/task.py
server/services/mapping_service.py
tests/server/unit/services/test_mapping_service.py
tests/server/unit/services/test_project_admin_service.py

Ensure user can only lock one task at a time on a project.

Enforce lock rules

---

server/__init__.py
server/api/user_apis.py
server/models/dtos/user_dto.py
server/services/user_service.py
tests/server/helpers/test_files/osm_user_details_simple.xml
tests/server/helpers/test_helpers.py
tests/server/unit/services/test_user_service.py

New User API to get details on the user via OSM

Add API to get details about user from OSM

---

server/models/postgis/project.py

Project DTO contains new fields

---

client/app/profile/profile.controller.js
client/app/profile/profile.html
client/app/services/account.service.js

Add OSM details (joined and number of changesets) to profile

Ht 60 profile

---

server/api/validator_apis.py
server/services/mapping_service.py
server/services/user_service.py
server/services/validator_service.py
tests/server/unit/services/test_user_service.py
tests/server/unit/services/test_validator_service.py

Enforce only validators can validate rule in the API

Enforce validator only rule

---

server/api/mapping_apis.py
server/models/dtos/mapping_dto.py
server/models/postgis/utils.py
server/services/mapping_service.py
tests/server/unit/services/test_mapping_service.py

Add constructor to mapping_service allowing for easier testing and better exception handling

Refactor mapping service

---

server/__init__.py
server/api/mapping_apis.py
server/api/project_apis.py
server/models/postgis/project.py
server/services/mapping_service.py
server/services/project_service.py
tests/server/unit/services/test_mapping_service.py
tests/server/unit/services/test_project_service.py

Create a new service for managing project stuff

Add project service

---

client/app/project/project.controller.js
client/app/project/project.html
client/app/services/editor.service.js

Launch Potlatch2 and Field Papers. Walking Papers does not seem to exist anymore.

Potlatch field papers editors

---

server/api/user_apis.py
server/models/postgis/user.py
server/services/authentication_service.py
server/services/user_service.py
tests/server/integration/models/postgis/test_project.py
tests/server/integration/services/test_authentication_service.py
tests/server/unit/services/test_authentication_service.py
tests/server/unit/services/test_user_service.py

Rework user-service to make it easier to unit test.

User Service Refactor 1

---

server/api/user_apis.py
server/services/authentication_service.py
server/services/user_service.py
tests/server/unit/services/test_authentication_service.py
tests/server/unit/services/test_user_service.py

Rework user-service to use static methods

User refactor

---

server/api/authentication_apis.py
server/api/mapping_apis.py
server/api/project_apis.py
server/api/validator_apis.py
server/models/dtos/mapping_dto.py
server/services/authentication_service.py
server/services/mapping_service.py
server/services/project_service.py
server/services/validator_service.py
tests/server/unit/services/test_authentication_service.py
tests/server/unit/services/test_mapping_service.py
tests/server/unit/services/test_project_service.py
tests/server/unit/services/test_validator_service.py

Make service methods static for easier use

Service refactor

---

server/api/project_admin_api.py
server/services/project_admin_service.py
tests/server/unit/services/test_project_admin_service.py

Make methods static for easier use

Serv refactor 2

---

client/app/profile/profile.controller.js
client/app/profile/profile.html
client/assets/styles/sass/_helpers.scss
client/assets/styles/sass/_profile.scss

More work on the profile page. Stats and projects are mocked. Only top bit contains data from API.

Profile page projects

---

server/models/dtos/project_dto.py
server/models/postgis/project.py
server/models/postgis/utils.py
server/services/project_admin_service.py
tests/server/unit/models/postgis/test_project.py

Return centroid in search results.

Aoi centroid2

---

server/services/project_service.py
server/services/user_service.py
tests/server/unit/services/test_project_service.py

Ensure mappers have correct level before mapping

Enforce mapper level rule

---

server/__init__.py
server/api/project_apis.py
server/api/validator_apis.py
server/config.py
server/models/dtos/validator_dto.py
server/models/postgis/task.py
server/services/project_service.py
server/services/validator_service.py

New validation API allows client to get all mapped tasks grouped by user

API for getting mapped tasks by user

---

client/app/admin/users/users.controller.js
client/app/admin/users/users.html
client/app/components/account-nav/account-nav.directive.js
client/app/components/account-nav/account-nav.html
client/app/taskingmanager.app.js
client/assets/styles/sass/_contribute.scss
client/assets/styles/sass/_helpers.scss
client/assets/styles/sass/_users.scss
client/assets/styles/sass/taskingmanager.scss
client/index.html
tests/client/unit/app/admin/users/test.users.controller.js

Mockup user list (/admin/users)

Ht 97 user list

---

server/services/mapping_service.py

See if XML encoding makes a difference when testing

Bugfix - XML Encoding

---

client/app/project/project.controller.js
client/app/project/project.html
client/app/services/editor.service.js

Pass GPX to iD editor + tidy up UI

Ht 86 id editor

---

server/__init__.py
server/api/project_admin_api.py
server/models/dtos/project_dto.py
server/models/postgis/task.py
server/services/project_admin_service.py

Add API so PMs can see all comments

New API to see all comments on a project

---

client/app/admin/edit-project/edit-project.controller.js
client/app/admin/edit-project/edit-project.html
client/app/services/project.service.js
client/assets/styles/sass/_helpers.scss

Wire up the following fields for project edit:
- changesetComment
- entitiesToMap
- dueDate
- imagery
- defaultLocale
Add ability to delete project - see actions tab

edit - wire up text fields + delete

---

client/app/project/project.controller.js
client/app/services/editor.service.js

Added changesetComment + imageryURL to iD editor
I have saved a changeset comment and a imagery URL on project 186 for testing purposes.

changeset comment + imagery URL

---

client/app/admin/dashboard/dashboard.controller.js
client/app/admin/dashboard/dashboard.html
client/app/project/project.controller.js
client/app/project/project.html
client/app/services/project.service.js
client/assets/styles/sass/_dashboard.scss

Show project comments on the dashboard. The projects are hardcoded, but once you have selected a project and scroll down to comments, it will show the comments for that project ID (comes from API)
Also, I have set a limit to the comment length to prevent people from putting in essays!

add project comments

---

server/api/mapping_apis.py

Tweak API so that GPX XML can be downloaded as a file
cc @feenster

Update API to make GPX available as a file

---

client/app/project/project.controller.js
client/app/project/project.html
client/app/services/editor.service.js

If you select JOSM as the editor you see a link to download the current tasks as GPX file.  Download then Open in Josm with File > Open

can download currents tasks as gpx for JOSM

---

server/api/mapping_apis.py
server/models/postgis/task.py
server/services/mapping_service.py
tests/server/integration/services/test_mapping_service.py

Multiple tasks on gpx

---

server/api/project_apis.py
server/models/dtos/project_dto.py
server/models/postgis/project.py
server/services/project_service.py

Users can now filter projects by mapping type

Add MappingTypes to search

---

client/app/admin/edit-project/edit-project.controller.js
client/app/admin/users/users.html
client/app/contribute/contribute.controller.js
client/app/contribute/contribute.html
client/app/project/project.html
client/app/services/search.service.js
client/assets/styles/sass/_contribute.scss

Feedback changes and bugfixes:
- edit project: default due date not to 1970
- edit project: warnings populate fields only when status is published
- contribute: add search 'all' mapping level button (not working in API yet)
- contribute + users list: pagination max size
- comments on tasks: add characters remaining text

feedback changes

---

server/api/project_apis.py
server/models/dtos/project_dto.py
server/models/postgis/project.py
server/models/postgis/tags.py
server/services/project_service.py

Add facility to search by org tag

Add search for org-tag

---

server/api/project_apis.py
server/models/dtos/project_dto.py
server/models/postgis/project.py
server/services/project_service.py
tests/server/unit/services/test_project_service.py

Add ability to search by campaign

---

client/app/admin/edit-project/edit-project.controller.js
client/app/admin/edit-project/edit-project.html
client/app/contribute/contribute.controller.js
client/app/contribute/contribute.html
client/app/services/search.service.js
client/app/services/tag.service.js
client/assets/styles/sass/_helpers.scss
client/index.html

Work in progress PR to make staging working again.
- Search: you can now search by mapping type, organisation and campaign
- Project edit: you can now edit the types of mapping 
TODO:
- Project edit: organisation tags and campaign tags
- Basic tests for the new tag service

Enhance search

---

server/api/project_admin_api.py
server/models/postgis/task.py
server/services/validator_service.py

Now invalidates/validates all except ready.

Invalidate / Validate all v2

---

server/models/dtos/project_dto.py
server/models/postgis/project.py
server/services/mapping_service.py
server/services/project_service.py
server/services/stats_service.py
server/services/validator_service.py
tests/server/unit/services/test_mapping_service.py
tests/server/unit/services/test_stats_service.py

Add code to refresh stats on statechange of Task.

Initial Stats Service and API

---

client/app/admin/create-project/create-project.html
client/app/admin/dashboard/dashboard.html
client/app/admin/edit-project/edit-project.html
client/app/contribute/contribute.controller.js
client/app/contribute/contribute.html
client/app/profile/profile.controller.js
client/app/profile/profile.html
client/app/project/project.html
client/app/services/map.service.js

- project edit: increase size of project description and instructions fields
- contribute: disable scroll of map
- contribute: make contribute button in list view smaller
- contribute: limit characters short description 
- mapping: history not under advanced. Show the history above the advanced.
- mapping: Remove text "task # is STATUS" from top of panel and add user to advanced section (if locked by someone for example)
- admin project dashboard: added buttons 'create a new project' + 'edit'
- user profile: wire up tasks mapped + tasks validated to updated API

Feedback tidy up v1

---

server/__init__.py
server/api/stats_api.py
server/models/dtos/stats_dto.py
server/services/stats_service.py

Add API to get Project Activity

---

client/app/contribute/contribute.html
client/app/project/project-dashboard.controller.js
client/app/project/project-dashboard.html
client/app/services/stats.service.js
client/assets/styles/sass/_contribute.scss
client/assets/styles/sass/_dashboard.scss
client/assets/styles/sass/_helpers.scss
client/assets/styles/sass/_project.scss
client/index.html
tests/client/unit/app/services/test.stats.service.js

Contribute page: the grid view includes stats (hard coded until the API returns it)
Activity and stats page: /project/{{project-id}}/dashboard shows user's contribution stats (coming from API)

Stats on project

---

server/__init__.py
server/api/user_apis.py
server/models/postgis/user.py
server/services/user_service.py
tests/server/unit/services/test_user_service.py

New API allows PMs and Admin to set user roles

Add API to allow admins and pms to set role

---

client/app/admin/dashboard/dashboard.controller.js
client/app/admin/dashboard/dashboard.html
client/app/contribute/contribute.controller.js
client/app/contribute/contribute.html
client/app/services/projectMap.service.js
client/assets/styles/sass/_map.scss

Show popup with project ID and project name on contribute page and project dashboard page

show popup on hover/click

---

client/package.json
server/__init__.py
server/api/user_apis.py
server/models/postgis/user.py
server/services/user_service.py
tests/server/integration/services/test_user_service.py
tests/server/unit/services/test_user_service.py

New API that allows PMs to set a users mapping level

Add set-level on user api

---

client/app/profile/profile.controller.js
client/app/profile/profile.html
client/app/project/project.controller.js
client/app/services/account.service.js
client/app/services/user.service.js
client/assets/styles/sass/_profile.scss
client/index.html
tests/client/unit/app/services/test.user.service.js

/user/{username}
- Add ability to change someone's role (ADMIN, PROJECT_MANAGER, VALIDATOR) depending on your own role.
- Add ability to change someone's mapper level (BEGINNER, INTERMEDIATE, ADVANCED)

Wire up set level + roles

---

server/api/project_admin_api.py
server/models/dtos/project_dto.py
server/models/postgis/project.py
server/services/project_admin_service.py
tests/server/unit/services/test_project_admin_service.py

Add code so we can associate imagery license with a project

Attach license to project

---

server/api/mapping_apis.py
server/models/postgis/project.py
server/models/postgis/statuses.py
server/models/postgis/user.py
server/services/mapping_service.py
server/services/project_service.py
server/services/user_service.py
tests/server/unit/services/test_mapping_service.py
tests/server/unit/services/test_project_service.py

Enforce imagery license when attempting to map

Validate license

---

server/__init__.py
server/api/user_apis.py
server/models/postgis/user.py
server/services/user_service.py

New API so we can record users accepting license terms

Add API to accept license terms

---

server/api/mapping_apis.py
server/api/user_apis.py
server/models/dtos/user_dto.py
server/models/postgis/statuses.py
server/models/postgis/user.py
server/services/user_service.py

Add ability to search and filter users

User search filters

---

server/services/stats_service.py

TEST PR
Unfinished code adding additional user stats to the API. Used to test out branch cloning by other users.

[WIP] Start additional stats API for Blake

---

server/api/validator_apis.py
server/models/postgis/statuses.py
server/models/postgis/user.py
server/models/postgis/utils.py
server/services/mapping_service.py
server/services/project_service.py
server/services/validator_service.py
tests/server/unit/services/test_validator_service.py

Ensure license check happens when validating

Add check for license to validating

---

client/app/admin/edit-project/edit-project.controller.js
client/app/admin/edit-project/edit-project.html
client/app/admin/licenses/license-edit.controller.js
client/app/admin/licenses/license-edit.html
client/app/admin/licenses/licenses.controller.js
client/app/admin/licenses/licenses.html
client/app/project/project.controller.js
client/app/project/project.html
client/app/services/license.service.js
client/app/services/user.service.js

Wire up licence APIs
License management
/admin/licenses
- Ability to add new license
- Ability to update existing license
- Ability to delete a license
Attach license to project
/admin/edit-project/{project-id}
- Ability to attach a license to a project
User accepting license
/project/{project-id}
- User is shown modal popup when they lock a task for mapping (locking a task for validating is still work in progress in API land). Once the user has accepted a license, it won't be shown to the user anymore.

Wire up licences

---

server/models/dtos/project_dto.py
server/models/postgis/statuses.py
server/services/project_service.py
tests/server/unit/services/test_project_admin_service.py

Ensure only allowed users can map on private projects

Enforce allowed users

---

client/app/admin/edit-project/edit-project.html
client/app/project/project.controller.js
client/app/project/project.html
client/app/taskingmanager.app.js
client/index.html
client/package.json
tests/client/karma.conf.js

- add warning message when creating a private project without allowed users
- start of implementing mentions in comments on projects

Wire up user apis

---

server/__init__.py
server/api/message_apis.py
server/models/dtos/message_dto.py
server/models/postgis/message.py
server/models/postgis/project.py
server/services/message_service.py

Add API to allow user to retrieve all messages

Get all messages API

---

server/api/message_apis.py
server/models/postgis/message.py
server/services/message_service.py

Add API to allow users to delete messages

Delete message api

---

server/models/postgis/message.py
server/services/message_service.py
server/services/validator_service.py

Add code to send thankyou on validation

Add thankyou message on validation

---

server/services/mapping_service.py
server/services/message_service.py
server/services/validator_service.py
tests/server/unit/services/test_messaging_service.py

Create links for task messaging

Add links to tasks on messaging

---

server/models/postgis/priority_area.py
server/models/postgis/project.py

Get priority areas

---

client/app/project/project.controller.js
client/app/project/project.html

Improve messaging on mapping page when use is not logged in

fix messaging for not logged in

---

client/app/contribute/contribute.html
server/models/dtos/project_dto.py
server/models/postgis/project.py

Include last updated data and author name on project

Organisation tag search

---

devops/tm2-pg-migration/migrationscripts.txt

messages, priority_areas, project_priority_areas, project_allowed_users

Add migration queries for... 

---

client/app/admin/users/users.controller.js
client/app/admin/users/users.html
client/app/components/language/language-switch.directive.js
client/app/contribute/contribute.controller.js
client/app/contribute/contribute.html
client/app/project/project.controller.js
client/app/project/project.html
client/app/services/language.service.js
client/app/services/project.service.js
client/app/services/search.service.js
client/index.html
tests/client/unit/app/contribute/test.contribute.controller.js
tests/client/unit/app/services/test.language.service.js

V1 of wiring up paging the search results. Only the grid view is paged.
Also, it adds the preferred language to the header when searching for a project.

Paging search results

---

client/app/contribute/contribute.controller.js
client/app/contribute/contribute.html
client/assets/styles/sass/_contribute.scss

tidy up list view + include % mapped and validated

paging list view + % mapped/validated

---

client/app/contribute/contribute.controller.js
client/app/contribute/contribute.html

Free text search

---

client/app/admin/edit-project/edit-project.controller.js
client/app/admin/edit-project/edit-project.html
client/app/components/language/language-switch.directive.js
client/app/components/language/language-switch.html
client/app/services/language.service.js

The language settings API wired up

supported languages

---

client/app/admin/edit-project/edit-project.controller.js
client/app/contribute/contribute.html
client/app/project/project.html
client/index.html
client/package.json

Save as markdown and render as HTML

Markdown change

---

devops/tm2-pg-migration/migrationscripts.sql
server/services/project_search_service.py

Bugfix for text search

---

client/app/login/auth.controller.js
client/app/login/login.controller.js
client/app/login/login.html
client/app/project/project.controller.js
client/app/services/auth.service.js
client/app/services/httpInterceptor.service.js
client/app/taskingmanager.app.js
client/index.html

401 interceptor service. All 401's get redirected to a login page (which will take you to the OSM login page). It will pass the redirect URL through.
On locking the task, it is intercepted by project controller before the interceptor service gets it so it displays a message inline rather than taking the user to another page.

401 interceptor

---

client/app/project/project.controller.js
client/app/project/project.html
client/app/taskingmanager.app.js
client/index.html
client/package.json
tests/client/karma.conf.js

Facebook and LinkedIn don't seem to like the 'localhost' URL. I put in the staging URL for testing purposes and that worked fine.

Social media share

---

client/locale/en.json

This fix/change is already updated to Transifex's master resource.

Update to en.json file for Transifex

---

server/models/postgis/message.py
server/services/messaging/message_service.py
server/services/messaging/smtp_service.py
server/services/messaging/templates/message_alert_en.html
server/services/messaging/templates/message_alert_en.txt
tests/server/integration/services/messaging/test_smtp_service.py

Send users an email alert (if they have supplied their email) when a message is generated.

Ensure user receives email alert if they are sent a message

---

client/app/login/auth-failed.html

en.json already has these strings so no need to update that file

Adds translation syntax to auth-failed.html

---

client/app/login/authorized.html

en.json already has these strings, so no need to update that file.

Adds translation syntax to authorized.html

---

client/app/login/login.html
client/locale/en.json

Added one string to en.json, which is not pushed to transifex yet. I think I will hold off as I think there might be more strings to add to en.json.

Adds syntax and string for login.html

---

devops/tm2-pg-migration/migrationscripts.sql

Modify query for calculating task counts.

Modify task count query

---

server/services/project_search_service.py

Addition of OrderBy project.id to the project filter.  This should resolve issues #423 and #427

Add ORDERBY projectId on project filter

---

server/api/mapping_apis.py
server/models/dtos/mapping_dto.py
server/services/mapping_service.py
tests/server/unit/services/test_mapping_service.py

Localise mapping APIs so per task instructions can be pulled back in correct language.

Add localisation to mapping APIS

---

client/taskingmanager.config.json
server/services/mapping_service.py
tests/server/integration/services/test_mapping_service.py

it seems that upload=no is not a valid value, should be upload = false

change upload value on osmxml to false

---

server/api/validator_apis.py
server/models/dtos/validator_dto.py
server/services/validator_service.py

Localise validation APIs so we can pull per-task instructions in correct language.

Add localistion to validation apis

---

client/app/admin/edit-project/edit-project.controller.js
client/app/admin/edit-project/edit-project.html
client/app/project/project.html

Edit, save and display per task instructions

Per task instructions ui

---

client/app/project/project.controller.js

In order to invite users to click on a task to select it.
Please review.

Show pointer cursor when hovering a task

---

client/app/contribute/contribute.controller.js
client/app/contribute/contribute.html
client/app/profile/profile.controller.js
client/app/profile/profile.html
client/app/taskingmanager.app.js
client/assets/styles/sass/_helpers.scss

Fixes for bugs @popelnuh reported:
- Profile page: redirect fix
- Filtering: default to user's level fix
- Profile page: remove buttons for setting level for validator/mapper roles
- Profile page: only allow users to set another user's level to above any automatic changeset level
- Start of saving URL params for search. TODO: wire up ALL for all mapping difficulties.

Bugfixes profile filtering

---

client/app/components/add-layer/add-layer.directive.js
client/app/services/map.service.js
client/assets/styles/sass/_map.scss
client/taskingmanager.config.json

Switched to the humanitarian OSM and added attribution setting for layers in config

humanitarian-osm

---

devops/tm2-pg-migration/migrationscripts.sql
server/models/postgis/task.py
server/services/validator_service.py
tests/server/integration/services/test_validation_service.py

Counters now set appropriately for validate, invalidate all.

Bugfix - Ensure counters set for validate, invalidate all

---

client/assets/styles/sass/_helpers.scss
client/index.html

This should fix https://github.com/hotosm/tasking-manager/issues/502

fix for loading header translations

---

server/services/messaging/chat_service.py
server/services/messaging/message_service.py

Cache a couple of api requests to take pressure off db

Add caching

---

client/app/contribute/contribute.controller.js

This PR sorts out https://github.com/hotosm/tasking-manager/issues/464

Default mapper level all

---

client/app/project/project.html
server/models/postgis/statuses.py
server/services/project_service.py
tests/server/unit/services/test_project_service.py

Allow users to view unpublished and archived projects, but not map them.
Addresses issues #422 and #529

Allow users to view Unpublished / Archived projects

---

client/app/components/account-nav/account-nav.directive.js
client/app/components/project-chat/project-chat.directive.js
client/app/components/project-chat/project-chat.html
client/app/project/project.controller.js
client/app/services/map.service.js
client/taskingmanager.config.json

chat enhancements:
- added url param to be able to navigate to the chat tab
- get chat messages every 10s
- message PM button which prepopulates the message field with PM/author's username
- make message from username a URL
Also:
- hide 'you have new messages' after 10s
- make OSM attributions open in new tab

Chat enhancements

---

server/models/dtos/project_dto.py
server/services/project_search_service.py

Enhance search API so it returns all matches as points so we can draw them on the map.

Project search v2

---

client/app/components/account-nav/account-nav.directive.js
client/assets/styles/sass/_project.scss

https://github.com/hotosm/tasking-manager/issues/501
and 
https://github.com/hotosm/tasking-manager/issues/409

route reload on project create + tidy up project UI

---

client/app/project/project-dashboard.html
server/models/dtos/project_dto.py
server/models/postgis/task.py

This should resolve issue #461 and allow user to click link to view Task

Task link in comment

---

server/__init__.py
server/api/project_apis.py
server/api/stats_api.py
server/models/dtos/project_dto.py
server/models/postgis/project.py
server/services/project_service.py
server/services/stats_service.py

Add a summary API for loading map bubble on Map

Project summary api

---

client/app/home/home.html
client/assets/styles/sass/_landingpage.scss

Addresses issue https://github.com/hotosm/tasking-manager/issues/499

image credit home page

---

client/app/contribute/contribute.html
client/assets/styles/sass/_contribute.scss

Addresses issue https://github.com/hotosm/tasking-manager/issues/536

List view longer title

---

server/services/validator_service.py

Bugfix for tasks that are locked when invalidate all is called.

Fix issue with locked tasks and invalidate all

---

client/app/project/project.controller.js
client/app/project/project.html

Unselect task on click off

---

client/app/project/project.html

- fix bug History doesn't show on mapping tab when task locked for mapping #640 
- Allow users to look at completed or validated task squares in ideditor to address #532

show history and add preview button

---

client/app/project/project.controller.js
client/app/project/project.html

https://github.com/hotosm/tasking-manager/issues/543

invalid project error handling

---

server/models/postgis/tags.py

This PR allows mixed case tags as requested in #509

Allow mixed case tags

---

server/services/validator_service.py

Only send one message when validating mutiple tasks

---

client/app/project/project.controller.js
client/app/project/project.html
client/app/services/task.service.js

Undo button which shows when you are logged in and when you have mapped/validated that task.

undo button

---

README.md
server/config.py

This removes the hardcoded SMTP variables and expects them to be supplied by environment variables instead. cc @bgirardot

removes hardcoded SMTP variables

---

server/config.py

cc @bgirardot in the future we'll remove this from the code and make it part of the configuration.

updates prod url

---

client/app/login/login.controller.js
client/app/services/auth.service.js

move login fix to auth service to make sure it gets called from where ever you login

login fix v2

---

devops/ci/circleci_deploy.sh

To update with branch deploys to the [demo env](tasks-demo.hotosm.org) update the `DEMO_BRANCH` environment variable in [CircleCI](https://circleci.com/gh/hotosm/tasking-manager/edit#env-vars).

makes the demo branch an environment variable in CircleCI

---

client/app/contribute/contribute.html

Bugfix for https://github.com/hotosm/tasking-manager/issues/690

bugfix for showing pagination when no results

---

client/app/components/account-nav/account-nav.html
client/app/contribute/contribute.controller.js

Fix for https://github.com/hotosm/tasking-manager/issues/714

bugfix for searching land use type

---

client/app/about/about.html
client/app/about/news.html
client/app/admin/create-project/create-project.html
client/app/components/account-nav/account-nav.html
client/app/contribute/contribute.controller.js
client/app/profile/profile.html
client/app/taskingmanager.app.js
client/assets/styles/sass/_structure.scss
client/index.html
devops/ci/circleci_deploy.sh

catch up master

---

client/app/about/about.html
client/assets/styles/sass/_about.scss

Hopefully fixes https://github.com/hotosm/tasking-manager/issues/702
Could you test this please @bgirardot ?

adblocker css fix

---

client/app/message/inbox.html

Show delete message button
Fix for https://github.com/hotosm/tasking-manager/issues/718

fix delete message button

---

client/app/admin/edit-project/edit-project.controller.js
client/app/admin/edit-project/edit-project.html

Fix for https://github.com/hotosm/tasking-manager/issues/731

Bugfix 731 message subject

---

client/app/contribute/contribute.html

Fix for https://github.com/hotosm/tasking-manager/issues/768

bugfix campaign and organisation tag

---

server/services/grid/grid_service.py

Bugfix for uploading kml shapes fix for #723

Remove Z dimension from kml features fixes #723

---

server/services/validator_service.py

Resolves issue #650 when invalidating all tasks on project

Ignore locked for validation tasks when invalidating all

---

server/services/validator_service.py

Fix same #650 issue for validate all

Bugfix 650 validate all

---

circle.yml

CircleCI 2.0

---

circle.yml
client/app/project/project.controller.js

Fix for https://github.com/hotosm/tasking-manager/issues/756
@bgirardot could you also test this please?

bugfix selecting task for imported projects

---

client/app/home/home.html

Updates front text and links to hook up functionality. Added a paragraph to link to disaster mapping.

adds new disasters paragraph, adds link functionality

---

client/app/home/home.html

Fixes a mistake from #804. Missed a text change.

fix frontpage text to match paragraph

---

client/app/project/project.html

Reverts hotosm/tasking-manager#830
We're merging changes first to develop--apologies.

Revert "Use consistent heading tag"

---

client/app/project/project.html

From https://github.com/hotosm/tasking-manager/pull/830 but for develop now

Use consistent heading tag

---

client/assets/styles/sass/_base.scss

Still not the best styling, but this will at least make clicking a bit more intuitive for now.

Add pointer for pagination

---

client/assets/styles/sass/_contribute.scss

An other option to fix #758
See #759 as well.
Fixes #758

Avoid mix of text in project cards

---

client/taskingmanager.config.json

Ethan, this makes it so the newly added layers show up in our testing environment, which I assume is very close to 'release' we just don't use any tools to manage.
See if this works for you and if so please merge it.
You should see:

Adds the confing change needed to deploy bing and pop density to 'release'

---

README.md

With `-r` any change to a python file will be taken into account.

Add auto-reload option to doc on how to run server

---

server/services/messaging/templates/validation_message_en.txt
server/services/messaging/templates/welcome_message_en.txt

The original text was someone confusing, this change makes it clear it is an automated message and there might be more feedback coming. And improves the welcome letter text.

Validation and welcome email template text fix up

---

client/app/about/about.html
client/app/home/home.html
client/app/learn/learn.html
client/assets/styles/sass/_landingpage.scss
client/index.html

This PR proposes updates to text and links across the site to clarify connection and linking to OpenStreetMap. Key updates are on landing page, footer, Learn page, and About page. 
To do:

Proposed update to text and links

---

client/app/project/project.html

Fixes #616. I have no experience with this front end framework, so this may not be the best way?

Add link to task gpx when mapping or validating

---

client/app/admin/create-project/create-project.html
client/app/components/add-layer/add-layer.html
client/assets/styles/sass/_admin.scss
client/assets/styles/sass/_map.scss

Fixes https://github.com/hotosm/tasking-manager/issues/835
Expanded:

835 add tms button tweak

---

server/services/mapping_service.py

This fixes an error in PR #934 kind of crudely, but it does seem to fix it.

Fixes len() error in PR #934 Tasks APIs improvements

---

server/api/project_apis.py

Right now the project API endpoint with all task and project information is only served as a text response.
This includes an `as_file` option so that a project manager or other person can download the information as a json file. Default on this is set to false so that front end usage doesn't break.
The filename is chosen to be somewhat consistent with TM2.

Full project API call add download as a file option

---

client/index.html

Updates the banner text to change goal and date that is shown.

update campaign banner text to Dec 31

---

client/app/project/project.html
client/assets/styles/sass/_mobile.scss
client/index.html
server/config.py
server/services/validator_service.py

Includes: 
* direct dl links
* prevent file caching
* revert banner to Mapswipe for mobile only

Update master with latest develop

---

client/app/404/404.html
client/app/taskingmanager.app.js

Add basic 404

---

client/app/project/project.html
client/app/services/message.service.js
server/models/postgis/task.py

Show the current lock state in history

---

server/services/mapping_service.py

change the task gpx boundary label

---

client/app/components/language/language-switch.directive.js
client/app/services/userPreferences.service.js
tests/client/unit/app/services/test.userPreferences.service.js

Fixes https://github.com/hotosm/tasking-manager/issues/962 + tidy up

save language in user preferences

---

client/app/admin/edit-project/edit-project.controller.js

#977 
@bgirardot hi! please review the changes :) thx!

fix autocomplete for organisation and campaign in editprojectadmin

---

server/models/postgis/project.py
server/services/messaging/message_service.py
server/services/project_service.py

fixes issue #553 and fixes issue #952

Improve Task comment and validation message subject lines

---

server/models/dtos/user_dto.py
server/models/postgis/user.py

add userId

---

server/api/messaging/message_apis.py
server/services/messaging/template_service.py
tests/server/integration/services/messaging/test_smtp_service.py

@smit1678 I did some testing locally, and it's all working for me.  So I need to get hold of the error you're seeing in prod re #961

Add test improve debug and file handling

---

server/api/messaging/message_apis.py
server/config.py
server/services/messaging/template_service.py
tests/server/integration/services/messaging/test_smtp_service.py

This PR cherry-picks the commit from https://github.com/hotosm/tasking-manager/pull/1069 into master in order to deploy this update without deploying all the updates from the current develop branch. Some features on current develop branch need additional review before they are deployed. 
I don't want to mess up the commit history so hopefully this method is correct.

Cherry-pick error logging bugfix to deploy to production

---

Dockerfile

A hotfix for the recent latency issues.

Increase gunicorn threads

---

Dockerfile

Reconcile changes from master branch

---

Dockerfile
circle.yml
requirements.txt

Enables New Relic monitoring agent in the app. 
@smit1678 I added you as a user, so you can see how it's working for tasks-demo.hotosm.org

Add New Relic agent

---

client/app/profile/profile.html

Add links on the User Profile to Pascal's tools like heatmap #958

Add links on the User Profile to Pascal's tools like heatmap

---

server/services/messaging/message_service.py

@bgirardot Hi blake please see this update :D i have added the link

add task link into the message instead of the number

---

client/app/home/home.html
devops/ci/circleci_deploy.sh
server/config.py

From here we can set up automatic deployments and let teachosm contributers directly control those changes.

Initial TeachOSM branch commit

---

server/models/postgis/project.py

Include validation in active mappers

---

server/services/mapping_service.py

Include www in gpx namespace

---

client/app/learn/learn.html

add ability to link to all h2 headers in Learn section. #1125 refers

Adds anchors to Learn Page

---

server/config.py

Update OSM authentication for TeachOSM

---

client/app/contribute/contribute.html
server/services/project_search_service.py

The API now allows the behavior requested in https://github.com/hotosm/tasking-manager/issues/1127
While doing the frontend part, I noticed some problems that need to be addressed before I can push the change; discussing on Slack.

Allow viewing archived projects by non authenticated users

---

client/app/contribute/contribute.html

Include priority label in project cards

---

client/app/project/project.controller.js
client/app/project/project.html

This timer picks up the lock action time from the task history and updates itself using the angular moment directive `am-time-ago`.
fixes issue #995

Fix #995: Add countdown timer to checked out task 

---

client/app/project/project-dashboard.html
client/app/project/project.html
server/models/postgis/task.py

Fixes https://github.com/hotosm/tasking-manager/issues/1002
For testing, I set the auto unlock time to 10 seconds. Here are the results:

Add AUTO_UNLOCKED_FOR_* action in TaskHistory

---

client/app/project/project.controller.js
client/app/project/project.html

Fixes #1065 
Here's a screenshot for an auto unlocked mapping task:
The behavior is exactly the same for validation tasks.

Update frontend on auto unlock

---

server/models/dtos/project_dto.py
server/models/postgis/project.py

Fix for #1162 
cc: @smit1678 @bgirardot please review for merge

Add creation date to project id api

---

client/app/admin/edit-project/edit-project.controller.js
client/app/admin/edit-project/edit-project.html
client/app/services/project.service.js
server/__init__.py
server/api/project_admin_api.py
server/services/mapping_service.py

Add reset all bad imagery option

---

client/app/admin/create-project/create-project.html

Resolved the Error Message alignment issue for self intersecting shapes by adding in-line css styling to the span tags which provide the error message.

Project Creationn: Error Message alignment

---

CONTRIBUTING.md

Adding a line about Transifex to clarify the workflow for string translations.

Add translation repo to CONTRIBUTING

---

client/app/project/project.html

Fixes #1219 by restoring the length of an event.

Restore the length of events in history view.

---

server/models/postgis/task.py

Second #Hacktoberfest contribution 😄 Hopefully fixes #1045 and #668 
This PR adds robustness to updating the task history and hopefully resolves #1045 and #668.  Reading thru the issue I agree with @ethan-nelson that the underlying cause of this issue is most likely one or more race conditions.
Stepping thru the code, I think the most likely spot this errors are being generated is update_task_locked_with_duration method, where we only expect to find one row
This PR doesn't seek to resolve the race conditions (as they are notoriously hard to replicate), however, it adds robustness to the update task history code, which should mitigate the error allowing users to continue mapping.
It does this in 3 ways:
* We now supply the user_id when we unlock this task.  If somehow 2 users have managed …

Add robustness to updating task history

---

client/app/components/project-chat/project-chat.html
client/app/project/project.html

Addresses issue #1152 : Show exact time in "time ago" alt text.
Being really new to contributing, I'm not sure how to preview and test the changes in the changes in the application.

Re-add exact time to history, chat re: issue #1152

---

client/app/project/project.html

Continuing from https://github.com/hotosm/tasking-manager/pull/1260 - since the element ID was not part of the merged Pr, including that change here in a separate PR in the same branch. Thanks for catching this @dakotabenjamin

SVG element identifiers

---

README.md

@ethan-nelson -Just update the [Dev FAQ section](https://github.com/hotosm/tasking-manager/wiki/Dev-Environment-FAQ) with the solutions discussed in slack. Linking the same to the main README file.

Link FAQ section to dev environment setup

---

README.md

* some formatting proposals on #136, #137, #138

Typo on #04

---

client/app/project/project.html
client/assets/styles/sass/_map.scss

Move Priority Area legend to task legend

---

client/app/contribute/contribute.html
client/app/project/project.html

Fixes #1225 
Removed href="#"
Removed excessive div

Don't jump to the top of the page after clicking on tab header

---

client/assets/styles/sass/_structure.scss

closes [#688](https://github.com/hotosm/tasking-manager/issues/688)

fix whitespace between menubar and page content

---

client/index.html

Small fix prior to 3.1.1 release
@dakotabenjamin

Close Matomo comment

---

client/app/project/project.controller.js
client/app/project/project.html

cc @ethan-nelson @smit1678 @wronk

Basic legend and interactions

---

client/app/about/about.html
client/app/home/home.html
client/index.html

Updating some strings that didn't have the ` | translate` filter applied and fixing presence of spaces (inside versus outside translation string).

A few translation tweaks

---

.dockerignore
.ebextensions/aws.config
Dockerfile
circle.yml

This PR is a predecessor of the #1393.
**Update Dockerfile:**
* Include front end packages in the container.
* some smaller typo changes for better readability and sticking to best practices in Docker containers
* Prepare for development setup use of the container (Add .dockerignore).
This PR is not introducing any breaking changes.

Improve Dockerfile

---

circle.yml

Fix ci container building

---

client/app/profile/profile.html
server/services/users/user_service.py

Restrict PM promotion to admin

---

client/app/project/project.controller.js
client/app/project/project.html

This will Add Loading message in Project page 
and also handles errorGetProject to show this error

Add loading message in project page

---

devops/docker/tasking-manager/Dockerfile
docker-compose.override.yml
docker-compose.yml

This PR enables users to create instances of the tasking-manager project using docker. Users are able to execute both client and server tests within the container.

Improvement of docker-compose

---

.circleci/config.yml
cloudformation/tasking-manager.template.js
requirements.txt

The tests aren't running but I'm 99% certain the structure of the CircleCI configuration is functional. We can continue to debug the testing issue without delaying the rest of the work.

Revert CircleCI version to 2 (redux)

---

tests/database/tasking-manager.sql

Replaces https://github.com/hotosm/tasking-manager/pull/1512

No owner on test SQL dump

---

server/services/project_admin_service.py

Fixes #1505 - Updated code to reset bad imagery counter in `projects` table on task reset

Reset bad imagery counter

---

client/app/profile/profile.html

Catching a few strings on the profile page that weren't translated.

Include a few missing profile translate strings

---

server/services/messaging/chat_service.py

Hotfix: Fix commenting

---

.circleci/config.yml

This fixes points 2 and 4 in https://github.com/hotosm/tasking-manager/issues/1444#issuecomment-488684858
cc @arunasank 
tested via local circleci execution

Remove redundant code and fix temp snapshot deletion

---

.circleci/config.yml

Only recycle snapshots, but do not use them during CloudFormation updates

---

.circleci/config.yml
circle.yml

Get python tests to work

---

client/app/message/message.controller.js
client/app/message/message.html
client/app/services/message.service.js

The Pr handles
1-> Invalid message id.
2-> Any other error loading the message. And
3-> Add error status in getMessage service.

Show 404 error on using in-valid message id.

---

.circleci/config.yml

There was some dummy code that is unnecessary and reveals secrets.

Remove testing code

---

.gitignore
client/app/admin/edit-project/edit-project.controller.js
client/app/admin/edit-project/edit-project.html

Fixes #602 - Making fields in metadata panel required

---

client/app/components/account-nav/account-nav.directive.js

Increase time interval of has-new-messages requests to 1 min

---

server/config.py
server/models/postgis/project.py
server/models/postgis/task.py
server/services/mapping_service.py
server/services/stats_service.py
tests/server/integration/models/postgis/test_user.py

This PR includes implementations and test modifications with the purpose of running tests within a local setup. Each of the changes are documented and explained on issue #1491 
**Note.** The assigned reviewer **must** verify this PR using their own setup of Tasking Manager or with docker.
```python -m unittest discover tests/server/```

Multiple fixes to python local tests

---

migrations/versions/0a6b82b55983_.py

Noticing a db migration related commit 9665583 missing from the current `develop` branch. Per voice w/ @xamanu - adding those changes in this branch

Pull in project query related changes

---

client/app/services/account.service.js

* When data for the logged-in user is freshly fetched from the server
through the account service, update the service's account data with the
latest user data

Update account data if logged-in user fetched

---

client/app/home/home.html
client/index.html

* changed title to "{{page}} - AI Assisted Tasking Manager"
* changed homepage content to explain the purpose of the instance

Update homepage content for the tasks-assisted instance

---

migrations/versions/05e1ecf9953a_.py
migrations/versions/0d47c10c8a66_.py
server/__init__.py
server/api/application_apis.py
server/api/project_apis.py
server/models/dtos/application_dto.py
server/models/dtos/project_dto.py
server/models/postgis/application.py
server/models/postgis/task_annotation.py
server/services/application_service.py
server/services/project_service.py
server/services/task_annotations_service.py

This is the backend work from PR #1349 as work in progress to solve issue #1264

Task Annotation Backend

---

client/app/admin/edit-project/edit-project.controller.js
client/app/admin/edit-project/edit-project.html
client/app/services/project.service.js
server/__init__.py
server/api/project_admin_api.py
server/services/project_admin_service.py

How to test:
- Go to edit project
- Click actions
- Search for Transfer Project
- enter a username (auto complete is enabled)
- Click transfer, 
- that username should now own the project.

Transfer project to new owner feature, fixes #1341

---

client/app/project/project.html
devops/cloudformation/tasking-manager.template.js

- Restricting project edit control to just project authors and admin
- Enabling detail logs for DB transactions

Restrict project edits to author & admins

---

.circleci/config.yml

Change circleci deployment branches

---

server/config.py

Just reviewed and rerolled #1713 on latest `develop`. approved from my side. moving in.

Add Korean language

---

.circleci/config.yml
devops/cloudformation/tasking-manager.template.js

This PR should finalize the infrastructure code for the 3.4 release.
It's marked WIP because we are still monitoring RDS usage to determine the appropriate size for our needs. 
Points of Discussion:
- m3 vs m5
- large vs xlarge (or bigger?)
- anything else

Modify deployment for new stack

---

server/services/stats_service.py

Fixes: https://github.com/hotosm/tasking-manager/issues/1720

Calculate stats in the database

---

README.md
docs/setup-live.md
server/api/project_admin_api.py
server/api/project_apis.py
server/api/swagger_docs_api.py
server/web/templates/welcome.html

* Fix link to LearnOSM on readme
* First short docu for live deployments
* Some swagger tagging things and moving one endpoint to have a nicer order

Some documentation and sorting of API tags

---

server/models/postgis/message.py
server/models/postgis/project.py
server/models/postgis/task.py
server/models/postgis/user.py
server/services/stats_service.py
server/services/users/user_service.py

Fixes: https://github.com/hotosm/tasking-manager/issues/1731

Prevent SQL Injection when executing custom SQL

---

client/app/project/project.controller.js
client/app/project/project.html
client/assets/styles/sass/_project.scss
client/locale/en.json

Rerolled reviewed PR #1431 by @uwaiszaki

Block start mapping and start validating options if email is not set

---

server/models/postgis/project.py

From #1753 - Per chat w/ team, updated the default value in model

Modify default mapper level

---

server/services/messaging/smtp_service.py

Print message in logger within testing environments

---

client/app/project/project.controller.js

This PR uses the map size in addition to the padding when going to a task using the URL.
It would be super helpful for this to get merged into `tasks-assisted` ASAP.
Closes #1776

Fix for high zoom level when accessing tasks by URL

---

server/__init__.py
server/api/stats_api.py
server/models/dtos/project_dto.py
server/services/project_search_service.py
server/services/project_service.py

This is a rebased PR with latest develop. Same approach as #1681

API endpoint to list project contributions by day (rebased)

---

server/models/dtos/project_dto.py
server/services/project_search_service.py

Include totalcontributors in project search endpoint

---

server/models/postgis/project.py
server/services/stats_service.py

Updated query for
- [Home page stats](https://tasks.hotosm.org/api-docs/swagger-ui/index.html?url=https://tasks.hotosm.org/api/docs#!/stats/get_api_v1_stats_summary)
- [Proejct stats](https://tasks.hotosm.org/api-docs/swagger-ui/index.html?url=https://tasks.hotosm.org/api/docs#!/stats/get_api_v1_stats_project_project_id)
All areas are returned in `sq.km`

Fix area query

---

migrations/versions/6612e4d6524c_.py
server/models/dtos/user_dto.py
server/models/postgis/user.py

From #1834 
- Added a migration file
- Updated DTO
- Updated PostGIS file

New fields for user table 

---

scripts/aws/cloudformation/tasking-manager.template.js

@xamanu I should have caught this before, this will fix the failed build

Add missing comma in cfn template

---

server/api/projects/resources.py
server/models/dtos/project_dto.py
server/services/project_search_service.py

This Pull request includes the additional request parameters _orderBy_ and _orderByType_ in project search endpoint.
Accepted options were included within _project_dto.py_ file

Order by and sort options for search project endpoint

---

server/models/dtos/project_dto.py
server/models/postgis/project.py

Updated ProjectSummary DTO and related function to return mappingTypes as a String Array.

Include mappingTypes in project summary

---

server/__init__.py
server/api/projects/activities.py
server/models/dtos/mapping_dto.py
server/models/dtos/stats_dto.py
server/services/stats_service.py

Per chat w/ @willemarcel - introducing `api/v2/projects/{project_id}/activities/latest/` to list down all tasks for a projects with:
* task ID
* current status
* last activity date and
* last mapper name who contributed to the task

Capture latest status of tasks

---

.circleci/config.yml
scripts/aws/cloudformation/tasking-manager.template.js

I created a mapbox token and added it as an env variable in CircleCI, and tested on a test deployment.

add mapbox token to deployment

---

server/api/projects/resources.py
server/services/project_admin_service.py
server/services/users/user_service.py
tests/server/unit/services/test_project_admin_service.py

was #1760, fixes #1748 and updates it with develop branch.

Implements backend restriction to edit and delete projects

---

server/models/dtos/project_dto.py
server/models/postgis/project.py

`countryTag` included in `/api/v2/projects/{project_id}/queries/summary/` endpoint

Include countryTag in Project Summary

---

server/models/dtos/project_dto.py
server/models/postgis/project.py

Per chat w/ @willemarcel - updated serialized name for:
* enforceMapperLevel
* enforceValidatorRole
Added the following new fields:
* allowNonBeginners
* private

Update serialised names for Summary

---

server/api/tasks/resources.py
server/models/postgis/project.py
server/models/postgis/task.py
server/services/project_service.py

Feature:task difficulty sort

---

server/__init__.py
server/api/users/resources.py
server/models/dtos/user_dto.py
server/models/postgis/user.py
server/services/users/user_service.py

this is a merge from latest develop to update PR ##1778

Recommended projects

---

server/services/project_admin_service.py

This PR is a simple way to help mitigate the project ownership bug discussed in #1715

Confirm project author is PM

---

client/app/admin/edit-project/edit-project.controller.js
client/app/admin/edit-project/edit-project.html

Quick fixes for problems when saving the project after adding, removing, adding custom editors

fixes for saving project

---

server/__init__.py
server/api/users/resources.py
server/services/users/user_service.py

adds user interets endpoint

---

server/api/projects/resources.py
server/models/dtos/project_dto.py
server/services/project_search_service.py

adds filter by interest on projects endpoint

---

manage.py
server/services/stats_service.py
tests/server/unit/services/test_stats_service.py

Adds new command to refresh project stats on production and also fixes on the update stats methods.
Fixes #1853 and #1908

Fixes for #1853 bad counting

---

frontend/src/App.js
frontend/src/hooks/UseTagAPI.js
frontend/src/network/user.js
frontend/src/views/authorized.js
frontend/src/views/messages.js
frontend/src/views/verifyEmail.js
server/api/system/authentication.py
server/services/messaging/smtp_service.py
tests/server/integration/services/messaging/test_smtp_service.py

Solves #1979
@hexiaok @xamanu I would like some suggestions on how to improve the text and the style of the email confirmation page.
**Error:**
**Success:**

update user confirmation process

---

server/__init__.py
server/api/users/resources.py
server/api/users/tasks.py
server/models/dtos/application_dto.py
server/models/dtos/mapping_dto.py
server/models/postgis/task.py
server/services/users/user_service.py

fixes #1597 was PR #1684
How to test:
Authenticated ajax request to /api/v1/user/tasks
Filters as get params, available filters: status, project_id, min_action_date, max_action_date
Sample request url: /api/v1/user/tasks?status=READY&project_id=2&min_action_date=2019-04-9&max_action_date=2019-04-10
Sample response:
```
{
"tasks": [
{
"taskId": 9,
"projectId": 1,
"taskStatus": "READY",
"taskHistory": [],
"taskAnnotation": null,
"isUndoable": false,
"autoUnlockSeconds": 7200
},
{
"taskId": 16,
"projectId": 1,
"taskStatus": "READY",
"taskHistory": [],
"taskAnnotation": null,
"isUndoable": false,
"autoUnlockSeconds": 7200
}
]
}
```

Endpoint for my tasks

---

server/api/projects/activities.py
server/api/projects/resources.py
server/models/dtos/project_dto.py
server/models/postgis/project.py
server/models/postgis/tags.py

Replace organisationTag by organisationName on project summary endpoint
adds organisation logo and name to project detail endpoint fixes #2007

Fixes #2007  

---

frontend/package.json
frontend/src/App.js
frontend/src/components/header/index.js
frontend/src/components/projectCreate/create.js
frontend/src/components/projectCreate/messages.js
frontend/src/components/projectCreate/navButtons.js
frontend/src/components/projectCreate/projectCreationMap.js
frontend/src/components/projectCreate/review.js
frontend/src/components/projectCreate/setAOI.js
frontend/src/components/projectCreate/setTaskSizes.js
frontend/src/components/projectCreate/trimProject.js
frontend/src/config/index.js
frontend/src/store/actions/project.js
frontend/src/store/reducers/index.js
frontend/src/store/reducers/project.js

This PR closes #1888.
- In your local instance of TM, login as ADMIN or PM role.
https://recordit.co/RFmyTp8U6C
- The user is able to upload shp as zip, geojson, kml or osm files.

Frontend Project creation wizard

---

server/models/postgis/organisation.py
server/services/organisation_service.py

Fixes https://github.com/hotosm/tasking-manager/issues/2020. This affects `GET` method on `/api/v2/organisations/`

Organisation filter by table join

---

frontend/public/index.html
frontend/src/App.js

Reformulated  `OSM Tasking Manager` to `Tasking Manager` and description texts.

Change some wording in html meta attributes

---

server/models/postgis/organisation.py
server/models/postgis/team.py
server/models/postgis/user.py
server/services/organisation_service.py
server/services/users/user_service.py

restrict users that can be added as manager of an organisation to only admin and manager roles

Fixes #1984 org managers can just be users with admin org manager role

---

server/api/projects/resources.py
server/models/dtos/project_dto.py
server/services/project_search_service.py

Allow to filter projects by teams

---

server/api/organisations/campaigns.py
server/models/postgis/campaign.py
server/services/campaign_service.py

fixes campaign organisation delete issue

---

server/__init__.py
server/api/annotations/resources.py
server/api/campaigns/resources.py
server/api/comments/resources.py
server/api/countries/resources.py
server/api/interests/resources.py
server/api/licenses/actions.py
server/api/licenses/resources.py
server/api/organisations/campaigns.py
server/api/organisations/resources.py
server/api/projects/actions.py
server/api/projects/activities.py
server/api/projects/campaigns.py
server/api/projects/contributions.py
server/api/projects/favorites.py
server/api/projects/resources.py
server/api/projects/statistics.py
server/api/projects/teams.py
server/api/tasks/actions.py
server/api/tasks/resources.py
server/api/teams/actions.py
server/api/teams/resources.py
server/api/users/actions.py
server/api/users/openstreetmap.py
server/api/users/resources.py
server/api/users/statistics.py
server/api/users/tasks.py

Review parameters, description and functioning of all server resources

Docstring review within server setup

---

frontend/package.json
frontend/src/App.js
frontend/src/components/projectCreate/create.js
frontend/src/components/projectCreate/messages.js
frontend/src/components/projectCreate/review.js
frontend/src/components/projectEdit/actionsForm.js
frontend/src/components/projectEdit/descriptionForm.js
frontend/src/components/projectEdit/imageryForm.js
frontend/src/components/projectEdit/instructionsForm.js
frontend/src/components/projectEdit/metadataForm.js
frontend/src/components/projectEdit/permissionsForm.js
frontend/src/components/projectEdit/priorityAreasForm.js
frontend/src/components/projectEdit/settingsForm.js
frontend/src/views/project.js
frontend/src/views/projectEdit.js
server/api/projects/resources.py
server/models/dtos/project_dto.py
server/models/postgis/project.py
server/services/project_admin_service.py

This PR constains the project editing feature.
**Features:**
- Description, instructions, metadata, priority Areas, imagery, permissions, settings and actions views.
- Includes project relationship with new orgs feature.
- Actions to validate, invalidate, reset, message contributors modal.
- Included project transfer.
- Included project clone.

Project Edit view

---

frontend/src/App.js
frontend/src/components/projectcard/messages.js
frontend/src/components/projectcard/nCardPlaceholder.js
frontend/src/components/projectcard/projectCard.js
frontend/src/components/projects/messages.js
frontend/src/components/projects/myProjectNav.js
frontend/src/components/projects/orderBy.js
frontend/src/components/projects/projectNav.js
frontend/src/components/projects/projectSearchBox.js
frontend/src/components/projects/projectSearchResults.js
frontend/src/hooks/UseProjectsQueryAPI.js
frontend/src/views/project.js
frontend/src/views/welcome.js
server/api/projects/resources.py
server/models/dtos/project_dto.py
server/models/postgis/project.py
server/services/project_admin_service.py
server/services/project_search_service.py

Adds sorting for projects and projects by owner

---

server/api/tasks/resources.py
server/models/postgis/project.py
server/models/postgis/task.py
server/services/project_service.py

Per chat w/ @willemarcel - fixing the task classes. Endpoints touched:
* /api/v2/projects/{project_id}/tasks/queries/own/locked/
* /api/v2/projects/{project_id}/tasks/queries/own/locked/details/
* /api/v2/projects/{project_id}/tasks/ - introduced a query parameter for task ID

Fix task endpoints for logged in user

---

.circleci/config.yml
scripts/aws/cloudformation/tasking-manager.template.js

In preparation for the TM4 testing release, adding new site parameters to the template.

Add org parameters to cloudformation template

---

server/models/postgis/project.py

Added the new parameter for tasks_as_geojson function from within project dto fetch

Handle all task fetch in Project DTO function

---

server/__init__.py

From #2056:
* Updated tasks/queries/own/mapped/ -> tasks/queries/mapped/

Minor changes to task endpoints

---

server/__init__.py
server/api/tasks/resources.py
server/models/postgis/project.py
server/models/postgis/task.py
server/services/project_service.py
tests/server/unit/services/test_project_service.py

From  #2063 - checking for user's locked tasks across all projects

Check task lock across multiple projects

---

.dependabot/config.yml

Add dependabot service to keep both backend and frontend dependencies updated.

add dependabot config file

---

frontend/src/assets/styles/_organizations.scss
frontend/src/assets/styles/index.scss
frontend/src/components/footer.js
frontend/src/components/header/index.js
frontend/src/components/header/messages.js
frontend/src/components/header/tests/menuItens.test.js
frontend/src/components/header/updateEmail.js
frontend/src/components/projects/messages.js
frontend/src/components/projects/myProjectNav.js
frontend/src/components/projects/projectSearchResults.js
frontend/src/components/teamsAndOrgs/campaigns.js
frontend/src/components/teamsAndOrgs/management.js
frontend/src/components/teamsAndOrgs/menu.js
frontend/src/views/management.js

fix orgs logos, footer menu links and management pages alignment

style improvements 

---

frontend/src/components/projectCreate/create.js
frontend/src/components/projectCreate/messages.js
frontend/src/components/projectCreate/navButtons.js
frontend/src/components/projectCreate/projectCreationMap.js
frontend/src/components/projectCreate/setAOI.js
frontend/src/components/projectCreate/setTaskSizes.js
frontend/src/components/projectEdit/actionsForm.js
frontend/src/config/index.js
frontend/src/config/tests/config.test.js

This PR closes #2018 
**Features:**
- Error notification as messages instead of alerts
- Allow to return without resetting taskgrid.
- Fix for Tasks counter
- Updated intiial zoom level to set taskgrid.
- Split multiple tasks

Enhancement in project creation view

---

server/api/teams/resources.py
server/services/team_service.py

adds filters to team endpoints

---

frontend/src/components/projectCreate/create.js
frontend/src/components/projectCreate/navButtons.js
frontend/src/components/projectCreate/setAOI.js
frontend/src/components/projectCreate/setTaskSizes.js

- Fixes error notification message when user defines aoi.
- Removes the click event split after tasks grid update.
- Display notification for incorrect file format

set AOI message error / Remove eventlistener split

---

server/api/teams/resources.py
server/models/postgis/team.py
server/services/team_service.py

From https://github.com/hotosm/tasking-manager/issues/2046 - added a query parameter to `/api/v2/teams/`

Include organisation filter for teams

---

server/models/dtos/project_dto.py
server/models/postgis/task.py
server/services/project_service.py
tests/server/unit/services/test_project_service.py

From #2103 - updated the locked tasks DTO to present project ID and task status for further processing and presentation on client side

LockedTasksDTO additional fields

---

frontend/src/components/user/forms.js
frontend/src/components/user/messages.js
frontend/src/views/settings.js
server/models/dtos/interests_dto.py
server/services/users/user_service.py

This PR closes #1640 
**how to test**
1. Load into database a list of interests. You can use Flask Shell and make a loop inserting elements into a database.
```
>>> from server.models.postgis.interests import Interest
>>> items = ['Water', 'Sanitation', 'Disaster Risk Reduction', 'environment', 'disaster Response', 'public health', 'gender equality'] 
>>> [Interest(name=i).create() for i in items] 
```
2. Login normally to tasking manager.
3. Go to settings view.
4. Select some interests and update.
6. Deselect some previous selected ones and update

User interests frontend

---

frontend/src/components/taskSelection/action.js
frontend/src/components/taskSelection/map.js

+ zoom map even if the window is not active
+ disable zoom animation in `/projects/<id>/map/`
(solves #2112)

Fix TasksMap zoom

---

server/services/users/user_service.py

Affects `/api/v2/users/{username}/recommended-projects/`

[WIP] Fix 500 errors on recommended projects

---

frontend/src/App.js
frontend/src/assets/styles/_extra.scss
frontend/src/components/contributions/messages.js
frontend/src/components/contributions/myTasksNav.js
frontend/src/components/contributions/taskBodyCard.js
frontend/src/components/contributions/taskCard.js
frontend/src/components/contributions/taskResults.js
frontend/src/components/menu.js
frontend/src/components/projects/projectSearchBox.js
frontend/src/components/svgIcons/clock.js
frontend/src/components/taskSelection/messages.js
frontend/src/components/taskSelection/taskList.js
frontend/src/components/teamsAndOrgs/menu.js
frontend/src/components/tests/menu.test.js
frontend/src/hooks/UseTaskContributionAPI.js
frontend/src/views/contributions.js

This PR closes #1599 but you'll need to open a new one for the "My Contributions" redesign and I recommend pulling across my checklist of backend changes. (includes IE fix)

My Contributions page basics

---

frontend/src/App.js
frontend/src/assets/styles/_extra.scss
frontend/src/components/header/index.js

- set a bigger width to modal popups on small screens
- fix page scrolling on Chrome

Style enhancements

---

frontend/src/components/taskSelection/messages.js
frontend/src/components/taskSelection/taskActivity.js
frontend/src/components/taskSelection/taskList.js
server/api/comments/resources.py
server/models/dtos/mapping_dto.py
server/models/postgis/task.py
server/services/messaging/message_service.py
tests/server/unit/services/messaging/test_messaging_service.py

This PR closes #1620 
**How to test**:
1. Load sql database dump.
2. Login as user.
3. Go to projects tasklist view.
4. Press the **listview** icon

Task activity modal

---

frontend/src/App.js
frontend/src/components/footer.js
frontend/src/components/header/index.js
frontend/src/components/header/messages.js
frontend/src/components/teamsAndOrgs/management.js
frontend/src/components/teamsAndOrgs/messages.js
frontend/src/components/teamsAndOrgs/projects.js
frontend/src/components/teamsAndOrgs/teams.js
frontend/src/hooks/UseProjectsQueryAPI.js
frontend/src/views/campaigns.js
frontend/src/views/messages.js
frontend/src/views/organisations.js
frontend/src/views/teams.js
server/models/postgis/team.py

add team membership view

---

frontend/package.json
frontend/src/components/projectDetail/index.js
frontend/src/components/projectDetail/messages.js
frontend/src/components/projectDetail/questionsAndComments.js
server/api/comments/resources.py
server/models/dtos/message_dto.py
server/models/postgis/project_chat.py
server/services/messaging/chat_service.py

This Pull request includes the **Question and Comments** view within the Project Detail page in the frontend side.
**backend changes:**
- Modified the project chat endpoint to limit the number of messages returned per request.
- Include the **PictureUrl** field for each returned message for project chat endpoint.
**How to test:** Using a database dump.
- Login as user.
- Go to a project detail.
- Include some comments.
- To reference some users. You have to press the @ symbol to enable search. You will need some users in the database.

Questions and comments component

---

frontend/src/App.js
frontend/src/components/homepage/contactForm.js
frontend/src/components/homepage/messages.js
frontend/src/views/contact.js
frontend/src/views/messages.js
server/__init__.py
server/api/system/general.py
server/services/messaging/smtp_service.py

closes #1635. 
Needs POST-capable backend on `contactUs` for `{"name":"Thad","email":"contact@openstreetmap.org","description":"An example message"}`

Create Contact frontend

---

frontend/src/App.js
frontend/src/components/contributions/messages.js
frontend/src/components/contributions/myTasksNav.js
frontend/src/components/contributions/taskBodyCard.js
frontend/src/components/contributions/taskCard.js
frontend/src/components/taskSelection/taskActivity.js
frontend/src/components/taskSelection/taskList.js
frontend/src/views/contributions.js

- Improve Task Activity modal style
- Reuse Task Activity modal on "My Contributions" page
- Change links on the task cards on "My Contributions" page

improve my-contributions and task activity modal

---

frontend/src/components/projectDetail/header.js
frontend/src/components/projectDetail/index.js
frontend/src/components/projectDetail/messages.js
frontend/src/components/taskSelection/action.js
frontend/src/components/taskSelection/index.js
frontend/src/components/taskSelection/messages.js

...and refactor project header

add project status label when draft or archived

---

frontend/src/components/user/avatar.js

...due to performance issues on the server

don't fetch user profile endpoint from UserAvatar

---

frontend/src/components/projects/myProjectNav.js
server/api/projects/resources.py
server/models/dtos/project_dto.py
server/services/project_search_service.py
server/services/users/user_service.py

Included a `favoritedByMe` filter  for `/api/v2/projects`

Favorite project filter

---

frontend/src/hooks/UseFavProjectAPI.js

only verify if project is favorited if the user is logged in

---

frontend/src/assets/styles/_extra.scss
frontend/src/components/taskSelection/action.js

hide completion instructions if height is less than 930 px

---

frontend/src/components/taskSelection/taskActivity.js

Better alignment of Comment form textarea and button on the task activity modal

Better alignment of Comment form textarea and button 

---

frontend/package.json
frontend/src/components/projectCreate/projectCreationMap.js
frontend/src/components/projectEdit/priorityAreasForm.js
frontend/src/components/projects/projectsMap.js
frontend/src/components/taskSelection/index.js
frontend/src/components/taskSelection/map.js
frontend/src/config/index.js
frontend/src/config/tests/config.test.js
frontend/src/store/index.js
frontend/src/utils/tasksGeometry.js
frontend/src/utils/tests/tasksGeometry.test.js

Plus:
- update mapbox-gl version
- add right to left text mapbox-gl plugin
- improve tests

set map locale according to user preferences

---

frontend/src/components/header/index.js
frontend/src/components/localeSelect.js
frontend/src/components/user/content.js
frontend/src/components/user/forms.js
frontend/src/components/user/messages.js
frontend/src/views/settings.js

- add locale selector on user settings page
- add interests selector on welcome page

improve user settings and welcome pages

---

frontend/src/components/dropdown.js
frontend/src/components/tests/dropdown.test.js

How to test:
- Resize your window in order to having a vertical scroll bar
- Click on a dropdown menu
- Scroll the page
- Check if the dropdown content scrolls with the page

fix dropdown content position

---

frontend/src/components/teamsAndOrgs/members.js
frontend/src/utils/teamMembersDiff.js
frontend/src/utils/tests/teamMembersDiff.test.js
frontend/src/views/teams.js

* doesn't allow to remove all managers or all members from a team
* improve the way we compare the new and old members/managers of a team

improve team members management

---

frontend/src/hooks/UseTaskContributionAPI.js
server/api/users/tasks.py
server/models/dtos/user_dto.py

- Rename task_status filter to status. 
- Rename userTasks to tasks on UserTaskDTOs

Fix task action page and modify user tasks endpoint

---

server/models/dtos/user_dto.py
server/services/users/user_service.py

Closes #2207 . Removed the centroid from the server response

Countries most contributed endpoint

---

server/api/tasks/actions.py
server/services/validator_service.py
tests/server/unit/services/test_validator_service.py

From https://github.com/hotosm/tasking-manager/issues/2191

Useful error messages for task handling

---

frontend/src/components/taskSelection/map.js

Assure centroid data is present before adding map layer

---

frontend/src/components/deleteModal/index.js
frontend/src/components/deleteModal/messages.js
frontend/src/components/formInputs.js
frontend/src/components/messages.js
frontend/src/components/projectCreate/messages.js
frontend/src/components/projectEdit/actionsForm.js
frontend/src/components/projectEdit/descriptionForm.js
frontend/src/components/projectEdit/imageryForm.js
frontend/src/components/projectEdit/inputLocale.js
frontend/src/components/projectEdit/instructionsForm.js
frontend/src/components/projectEdit/messages.js
frontend/src/components/projectEdit/metadataForm.js
frontend/src/components/projectEdit/permissionsForm.js
frontend/src/components/projectEdit/priorityAreasForm.js
frontend/src/components/projectEdit/settingsForm.js
frontend/src/components/projectEdit/teamSelect.js
frontend/src/components/taskSelection/messages.js
frontend/src/components/teamsAndOrgs/messages.js
frontend/src/components/user/messages.js
frontend/src/views/messages.js
frontend/src/views/projectEdit.js
server/__init__.py
server/api/projects/actions.py
server/api/projects/teams.py
server/models/dtos/project_dto.py
server/models/dtos/team_dto.py
server/models/postgis/project.py
server/services/team_service.py

serialize team dto for project update

---

frontend/src/components/projectDetail/index.js
frontend/src/components/projectcard/projectProgressBar.js
frontend/src/components/projectcard/tests/projectProgressBar.test.js
frontend/src/hooks/UseHover.js

fix project progress bar tooltip onHover

---

server/models/dtos/user_dto.py
server/models/postgis/user.py

User filter on role and level

---

server/models/dtos/stats_dto.py
server/services/stats_service.py

**Changes:**
- Modified query to use sqlalchemy instead of raw sql syntax
- Included total column = mapped + validated
- Included User mapping_level column.
- Included task_ids column

Include additional fields in user contributions of projects endpoint

---

frontend/src/components/projectEdit/descriptionForm.js
frontend/src/components/projectEdit/inputLocale.js

- add maxLength prop to InputLocale components
- set maxLength on project name and short description
Solves https://github.com/hotosm/tasking-manager/issues/2160

set maxLength on project name and short description fields

---

frontend/src/components/projectDetail/index.js
frontend/src/components/projectDetail/messages.js
frontend/src/components/projectDetail/projectDetailFooter.js
frontend/src/components/teamsAndOrgs/messages.js
frontend/src/components/teamsAndOrgs/teams.js
frontend/src/components/teamsAndOrgs/tests/teams.test.js

list teams on project detail page

---

frontend/src/hooks/UseFetch.js
frontend/src/hooks/UseProjectsQueryAPI.js

load project descriptions and instructions in the current user language

---

frontend/src/components/checkCircle.js
frontend/src/components/taskSelection/action.js
frontend/src/components/taskSelection/contributions.js
frontend/src/components/taskSelection/index.js
frontend/src/components/taskSelection/messages.js
frontend/src/components/tests/checkCircle.test.js

This PR includes the user contributions for each project.

Users contributions from project frontend

---

frontend/src/utils/login.js

+ increase popup window height

avoid login popup blocking

---

frontend/src/App.js
frontend/src/components/contributions/messages.js
frontend/src/components/contributions/myTasksNav.js
frontend/src/components/header/index.js
frontend/src/components/header/tests/menuItens.test.js
frontend/src/components/menu.js
frontend/src/components/projectCreate/index.js
frontend/src/components/projects/myProjectNav.js
frontend/src/components/taskSelection/taskActivity.js
frontend/src/components/teamsAndOrgs/management.js
frontend/src/components/teamsAndOrgs/projects.js
frontend/src/components/teamsAndOrgs/teams.js
frontend/src/components/tests/menu.test.js
frontend/src/components/user/messages.js
frontend/src/components/userDetail/contributionTimeline.js
frontend/src/components/userDetail/countriesMapped.js
frontend/src/components/userDetail/editsByNumbers.js
frontend/src/components/userDetail/elementsMapped.js
frontend/src/components/userDetail/headerProfile.js
frontend/src/components/userDetail/topCauses.js
frontend/src/components/userDetail/topProjects.js
frontend/src/views/campaigns.js
frontend/src/views/contributions.js
frontend/src/views/management.js
frontend/src/views/organisations.js
frontend/src/views/project.js
frontend/src/views/projectEdit.js
frontend/src/views/teams.js
frontend/src/views/userDetail.js
frontend/src/views/welcome.js

Contributions nav in user profile

---

frontend/src/components/projectDetail/index.js
frontend/src/components/taskSelection/index.js
frontend/src/components/taskSelection/legend.js
frontend/src/components/taskSelection/map.js
frontend/src/components/taskSelection/messages.js
frontend/src/config/index.js
server/__init__.py
server/api/projects/resources.py
server/services/project_service.py

- added project priority-areas endpoint (`​/api​/v2​/projects​/{project_id}​/queries​/priority-areas​/`)
- render priority areas on map
Solves #2288

Show priority areas

---

frontend/src/components/projectCreate/setTaskSizes.js

Fix typo for number of tasks in formattedmessage project creation

---

migrations/versions/6612e4d6524c_.py
server/models/postgis/user.py

From #2240 - updated default editor values

Change default editor value

---

server/models/postgis/project.py
server/models/postgis/user.py
server/services/users/user_service.py

From https://github.com/hotosm/tasking-manager/pull/2016 - bringing in the change to master

Time aggregates for user profile

---

frontend/src/components/projectEdit/inputLocale.js
frontend/src/views/projectEdit.js

Remove notification message after project update form changes

---

frontend/src/components/taskSelection/contributions.js
frontend/src/components/taskSelection/index.js

how to test: use the contributions tab to highlight some user tasks, click on a task in the map and check if the user highlight is disabled.

improve user highlight on contributions tab of task selection page

---

frontend/src/components/taskSelection/contributions.js
frontend/src/utils/projectCompletenessCalc.js
frontend/src/utils/tests/projectCompletenessCalc.test.js
frontend/src/utils/tests/snippets/tasksGeometry.js

add progress bar on contributions tab of task selection page

---

frontend/src/App.js
frontend/src/components/interests.js
frontend/src/components/teamsAndOrgs/menu.js
frontend/src/components/teamsAndOrgs/messages.js
frontend/src/views/campaigns.js
frontend/src/views/interests.js
server/__init__.py
server/api/interests/resources.py
server/services/interests_service.py

Admin panel for interests

---

server/models/dtos/application_dto.py
server/models/dtos/mapping_dto.py
server/models/dtos/message_dto.py
server/models/dtos/notification_dto.py
server/models/dtos/project_dto.py
server/models/dtos/user_dto.py
server/models/dtos/validator_dto.py
server/models/postgis/message.py
server/models/postgis/project.py
server/models/postgis/user.py
server/models/postgis/utils.py
server/services/project_service.py

Update UTC time format

---

frontend/src/components/projectDetail/index.js
frontend/src/components/teamsAndOrgs/organisations.js
frontend/src/components/teamsAndOrgs/teams.js
frontend/src/components/user/avatar.js
frontend/src/components/user/tests/userAvatar.test.js

- add UserAvatarList component to have a way to limit number of users
how to test: check the project detail page, teams management page, orgs management page.

add UserAvatarList component

---

server/api/tasks/actions.py
server/services/project_service.py

* Remove an extra argument from validator function
* ~Include a validator check to handle initial rollout of teams~
* Update error handling for task split

Fix a few task lock related issues

---

frontend/src/components/taskSelection/footer.js
frontend/src/utils/openEditor.js

also avoid race conditions when locking the tasks
Solves https://github.com/hotosm/tasking-manager/issues/2341

avoid browsers from blocking editor windows

---

frontend/src/App.js
frontend/src/components/menu.js
frontend/src/components/projectEdit/messages.js
frontend/src/components/teamsAndOrgs/menu.js
frontend/src/components/teamsAndOrgs/messages.js
frontend/src/components/user/list.js
frontend/src/components/userList.js
frontend/src/views/messages.js
frontend/src/views/users.js

Manage users view

---

frontend/src/components/header/index.js

When user selects any option the modal closes and the respective changes in route take place.
Closes #2364

[FIX]: The popup modal closes on selecting option now.

---

server/api/annotations/resources.py
server/api/comments/resources.py
server/api/projects/activities.py
server/api/projects/contributions.py
server/models/postgis/project_chat.py
server/services/messaging/chat_service.py
server/services/stats_service.py

- remove unneeded lines
- improve module imports
Related to #2333

improvements over #2333 code

---

frontend/src/components/projectCreate/projectCreationMap.js
frontend/src/components/projectCreate/setAOI.js
frontend/src/config/index.js
frontend/src/config/tests/config.test.js

Multiple layers support for project creation

---

frontend/src/components/header/signUp.js
frontend/src/components/taskSelection/index.js
frontend/src/components/user/forms.js

- autocomplete sign up and user settings forms
- open OSM registration page in new window during sign up
- always show instructions tab first to non expertMode users. To expertMode users show the task list if they have already contributed to project

changes requested on user group meeting

---

frontend/src/components/taskSelection/action.js
frontend/src/components/taskSelection/taskActivity.js
server/models/postgis/task.py
tests/server/unit/services/test_mapping_service.py

Include TaskHistory component within project map and validate views

---

frontend/src/utils/login.js

@willemarcel forgot to include the `redirectTo` parameter which I think had the same intention.
__ENHANCEMENT__:
If user hits an invalid url then we should redirect him/her to `/welcome` route. For this we need an array of available valid routes. This can be done in two ways:
1. Make a file where all routes are listed as a raw array.
2. Use any third party package which lists the routes.
Please suggest how to do this !
Closes #2376

[FIX]: User redirected to the url he hit.

---

frontend/src/components/header/index.js
frontend/src/components/localeSelect.js
frontend/src/store/index.js
frontend/src/store/reducers/userPreferences.js
frontend/src/utils/internationalization.js
frontend/src/utils/tests/internationalization.test.js

- fix locale dropdown visibility on user settings page (it was hidden in smaller screens)
- load TM in the user locale if its available

Fix problems in locales

---

frontend/src/components/taskSelection/footer.js

when defaultUserEditor is allowed, activate it by default instead of the first allowed editor for action

Fix automatic editor selection

---

frontend/src/hooks/UseFetch.js
frontend/src/hooks/UseProjectsQueryAPI.js
frontend/src/network/genericJSONRequest.js
frontend/src/utils/internationalization.js

- enable Japanese, Turkish and Swahili

fix locale code on fetch commands and enable new languages

---

frontend/src/components/notifications/notificationCard.js
frontend/src/components/notifications/notificationResults.js

Fixes **invalid date** error in notitfication card

Remove additional string for date in notification card mini

---

frontend/src/components/projectCreate/index.js
frontend/src/components/projectCreate/projectCreationMap.js
frontend/src/components/projectCreate/setAOI.js
frontend/src/components/projectCreate/setTaskSizes.js
frontend/src/components/projectCreate/trimProject.js

Closes #2433 . I refactored in order to add layers by calling a single function.

Preserve taskgrid on basemap change

---

frontend/src/components/projectEdit/customEditorForm.js
frontend/src/components/projectEdit/messages.js
frontend/src/components/projectEdit/settingsForm.js
frontend/src/views/messages.js
frontend/src/views/projectEdit.js

This PR adds the necessary front end components to add a custom editor to a project
closes #2301

Custom Editor Frontend

---

server/services/messaging/message_service.py

Closes #2457 
@willemarcel @ramyaragupathy please review !!

[FIX]: POST comment method amended.

---

frontend/src/components/taskSelection/taskList.js

following suggestion of users on the Slack channel.

make TaskList search case insensitive and add last action users to results

---

server/api/campaigns/resources.py
server/api/comments/resources.py
server/api/interests/resources.py
server/api/organisations/resources.py
server/api/projects/actions.py
server/api/projects/campaigns.py
server/api/projects/resources.py
server/api/projects/teams.py
server/api/tasks/actions.py
server/models/postgis/project.py
server/services/messaging/chat_service.py
server/services/project_admin_service.py
server/services/project_service.py
tests/server/unit/services/test_project_admin_service.py

Endpoints touched:
Class|Verb
-----|-----
ProjectsRestAPI|POST, HEAD, PATCH, DELETE
ProjectsQueriesOwnerAPI|GET
ProjectsQueriesNoTasksAPI|GET
ProjectsActionsTransferAPI|POST
ProjectsActionsMessageContributorsAPI|POST 
ProjectsActionsFeatureAPI|POST
ProjectsActionsUnFeatureAPI|POST
ProjectsActionsSetInterestsAPI|POST
ProjectsCampaignsAPI|POST, DELETE
TasksActionsMapAllAPI|POST 
TasksActionsValidateAllAP|POST 
TasksActionsInvalidateAllAPI|POST 
TasksActionsResetBadImageryAllAPI|POST 
TasksActionsResetAllAPI|POST 
OrganisationsRestAPI|PATCH, DELETE
CampaignsAllAPI|POST
CampaignsRestAPI|PATCH, DELETE
InterestsAllAPI|POST, PATCH, DELETE

Accomodate org manager permissions

---

backend/api/projects/resources.py

The definition of method is:
`def get_project_dto_for_mapper(
project_id, current_user_id, locale="en", abbrev=False
) -> ProjectDTO:`
Made changes accordingly!
Related #2492 
@ramyaragupathy please review !

fix arguments of method.

---

backend/api/users/tasks.py

handle invalid project id values on UserTasks view's query param

---

backend/models/postgis/user.py
backend/services/users/user_service.py

fix typo "get_all_users_not_pagainated" -> "get_all_users_not_paginated"

---

.circleci/config.yml
client/app/learn/learn.html

Replace old buildings video on Learn page with new one

---

requirements.txt

Superseeding:
* Bump pyyaml from 5.3 to 5.3.1 (https://github.com/hotosm/tasking-manager/pull/2524)
* Bump bleach from 3.1.1 to 3.1.3 (https://github.com/hotosm/tasking-manager/pull/2511)

Upgrade dependencies - pyyaml and bleach

---

docs/contributing-code.md
docs/contributing-translation.md
docs/contributing.md

This is my first PR in this repository. Thought I might as well improve the docs while reading them.

Improve "contributing" docs and fix typos

---

backend/models/dtos/mapping_dto.py
backend/models/postgis/interests.py
backend/services/interests_service.py
backend/services/project_service.py
backend/services/users/user_service.py
manage.py

Fixes #1927
To use:
`python manage.py update_project_categories csvfile.csv`

Import project categories command

---

frontend/src/views/about.js

Small changes in the about page

Fix font size; Moved Floss information into two rows

---

backend/api/organisations/resources.py
backend/services/organisation_service.py

From #2366 - remove user details for org fetch without access token. This also touch upon #2526

Remove manager details for anonymous org fetch

---

backend/models/postgis/notification.py

Return 0 when database query is None for unread message count

---

frontend/src/components/user/forms.js
frontend/src/components/user/messages.js
frontend/src/locales/en.json

Include option to resend email verification in user settings

---

frontend/src/views/project.js
frontend/src/views/userDetail.js

Add 404 handling to /projects/{id} and /users/{id}

---

frontend/src/components/notifications/notificationOrderBy.js

Closes #2172 
@willemarcel please review !

Fix mixed up filter query parameters.

---

.circleci/config.yml
backend/api/system/general.py
backend/config.py
backend/services/messaging/smtp_service.py
example.env
scripts/aws/cloudformation/tasking-manager.template.js

Set environment variable for contact form

---

frontend/src/components/projectcard/dueDateBox.js
frontend/src/components/projectcard/projectCard.js
frontend/src/components/taskSelection/action.js

include task counter in sidebar

---

frontend/src/components/header/signUp.js

Redirect to project page after user sign-up

---

frontend/src/hooks/UseLockedTasks.js
frontend/src/views/taskAction.js

Update frontend to the API changes made on https://github.com/hotosm/tasking-manager/pull/2562

update locked tasks endpoints

---

frontend/src/components/taskSelection/instructions.js

User can't open /tasks, and gets unhandled error if the project has empty instructions. This PR fixes it.
@willemarcel please look into it !

Fix dangerouslySetInnerHtml.

---

frontend/src/assets/styles/_extra.scss

hide "improve this map" on map attribution

---

backend/api/projects/resources.py
backend/api/teams/resources.py
backend/models/dtos/project_dto.py
backend/models/postgis/organisation.py
backend/services/organisation_service.py
backend/services/project_admin_service.py
backend/services/project_search_service.py

From #2567 
* Include managedByMe filter for projects
* Let only ADMINs and ORG MANAGER create teams
* Allow users without the project manager role to be selected as an organisation admin
* Allow ADMINs and org managers to create a project under their organization(s)

Org manager permissions across endpoints

---

backend/models/postgis/project.py
migrations/versions/7bbc01082457_.py

Import existing organisation information

---

frontend/package.json
frontend/src/components/editor.js
frontend/src/components/taskSelection/action.js
frontend/src/components/taskSelection/footer.js
frontend/src/utils/openEditor.js
frontend/src/utils/tests/openEditor.test.js

Update iD editor and load it using the locales preferences of the user.

update iD and enable localization

---

backend/api/projects/teams.py

Add token authorization to GET teams method.

---

backend/api/campaigns/resources.py
backend/api/interests/resources.py
backend/api/projects/resources.py

closes [#2631](https://github.com/hotosm/tasking-manager/issues/2630)
please review @xamanu

Error on create or edit in campaigns and categories

---

frontend/src/components/projectDetail/questionsAndComments.js
frontend/src/components/taskSelection/action.js
frontend/src/components/taskSelection/taskActivity.js

Text area to fetch users component

---

frontend/src/components/user/list.js
frontend/src/components/user/messages.js
frontend/src/views/users.js

Clear filter user button

---

frontend/public/index.html
frontend/src/components/projectDetail/index.js
frontend/src/components/taskSelection/action.js
frontend/src/components/taskSelection/index.js
frontend/src/hooks/UseMetaTags.js
frontend/src/hooks/tests/UseMetaTags.test.js
frontend/src/views/about.js
frontend/src/views/campaigns.js
frontend/src/views/contact.js
frontend/src/views/contributions.js
frontend/src/views/interests.js
frontend/src/views/learn.js
frontend/src/views/login.js
frontend/src/views/management.js
frontend/src/views/notifications.js
frontend/src/views/organisations.js
frontend/src/views/project.js
frontend/src/views/projectEdit.js
frontend/src/views/settings.js
frontend/src/views/swagger.js
frontend/src/views/teams.js
frontend/src/views/userDetail.js
frontend/src/views/users.js
frontend/src/views/verifyEmail.js
frontend/src/views/welcome.js

Solves partially https://github.com/hotosm/tasking-manager/issues/2614

Set title tag in all views

---

server/models/postgis/user.py

That is my first PR. I hope everything is working fine.
Issue: Repeated column in the "users" table #2639

delete redundant column in users table

---

frontend/src/components/formInputs.js
frontend/src/components/projectEdit/permissionsForm.js
frontend/src/components/projectEdit/teamSelect.js

fix organisation fetch on the project management

---

frontend/src/components/projectEdit/metadataForm.js

when changing the key from "LANDUSE" to "LAND_USE" use the one that was most used in the project.
Closes #2643
Please review @xamanu or @JorgeMartinezG

Project and Team doesn't update some values 

---

backend/api/interests/resources.py

This is for issue https://github.com/hotosm/tasking-manager/issues/2655. I have replaced organisation field with organisations.

Fixed failing endpoint issue

---

frontend/src/components/projectDetail/header.js
frontend/src/components/projectDetail/index.js
frontend/src/components/projectDetail/questionsAndComments.js

Changes to the project detail page style

---

frontend/src/components/projectDetail/questionsAndComments.js
frontend/src/components/taskSelection/action.js

Mention user in validation textarea

---

frontend/src/views/about.js

change 'h' to 'H' so text appears as GitHub

change GitHub capitalization

---

backend/api/teams/resources.py
backend/models/postgis/organisation.py
backend/services/organisation_service.py

fix team to update the organisation

---

frontend/src/components/interests/index.js
frontend/src/components/licenses/index.js
frontend/src/components/projectcard/projectCard.js
frontend/src/components/projects/projectNav.js
frontend/src/components/projects/projectSearchResults.js
frontend/src/components/teamsAndOrgs/campaigns.js
frontend/src/components/teamsAndOrgs/management.js
frontend/src/components/teamsAndOrgs/organisations.js
frontend/src/views/project.js

use the same alignment on management & explore project pages

---

frontend/src/components/taskSelection/action.js

Preserve comment when switching task in mapping/validation views

---

frontend/src/views/contact.js

closes #2619. The backend has already the option to send email without token validation

Send contact-admin mail without user login validation

---

backend/api/notifications/resources.py
backend/services/messaging/message_service.py
frontend/src/components/notifications/inboxNav.js
frontend/src/components/projects/projectSearchBox.js
frontend/src/hooks/UseInboxQueryAPI.js

Search project by id in notifications search box

---

frontend/src/components/taskSelection/action.js

Preserve status when switching task in mapping/validation views

---

frontend/src/views/projectEdit.js

Closes : #2721
Review please @JorgeMartinezG .

update style in edit project

---

frontend/src/components/contributions/messages.js
frontend/src/locales/en.json

Replace 'You worked on this task {time}' by 'Last updated{time}'

Change date message on My Tasks cards

---

frontend/src/components/user/forms.js
frontend/src/components/user/messages.js
frontend/src/locales/en.json

Add indicators for required fields in personal information
