hotosm/tasking-manager

backend/models/dtos/team_dto.py

Even if the team does not have members

Return always members list when listing teams

---

docs/setup-development.md

This PR adds a note to the devel docs that you can obtain an API token form the user settings.

Amend development setup docs for API 

---

frontend/src/App.js
frontend/src/assets/styles/_extra.scss
frontend/src/components/preloader.js
frontend/src/store/actions/auth.js
frontend/src/store/actions/loader.js
frontend/src/store/reducers/index.js
frontend/src/store/reducers/loader.js
frontend/src/views/authorized.js
frontend/src/views/login.js

Resolves https://github.com/hotosm/tasking-manager/issues/2167
Resolves #2470
Replaces #2371

Add loading indicator while user data is being fetched

---

frontend/src/components/projectDetail/questionsAndComments.js
frontend/src/components/teamsAndOrgs/teams.js
frontend/src/components/user/avatar.js
frontend/src/components/user/tests/userAvatar.test.js

- avoid distortion on UserAvatar
- show correct number on UserAvatarList (contributors section on project detail page)
- makes height of TeamCard fixed in order to avoid break the lines
Solves partially #2622

improve TeamCards and UserAvatar style

---

frontend/src/components/user/content.js
frontend/src/components/user/messages.js
frontend/src/locales/en.json

* add quickstart guide to welcome screen
* add link to OSM basic manual on LearnOSM

add quickstart guide to welcome screen

---

frontend/src/components/projects/projectSearchBox.js
frontend/src/components/user/list.js

Only two search bars were behaving like this, others are working fine, I have checked !
Fixes #2686 partially !

Prevent page refresh on pressing enter

---

frontend/src/components/header/index.js

The https://github.com/hotosm/tasking-manager/pull/2739 PR caused a bug in the user avatar on the header.

fix exhibition of user avatar on header

---

frontend/src/App.js

@xamanu do you think it would be good to add also a redirect from /contribute to /explore?

fix project detail page redirect

---

frontend/src/components/homepage/whoIsMapping.js

force 'who is mapping' title to be only one line

---

backend/services/messaging/message_service.py
backend/services/messaging/smtp_service.py
frontend/src/views/authorized.js
frontend/src/views/notifications.js

Message notification with message id

---

backend/services/project_search_service.py

Fixes local search for projects.
- In explore page, use different keywords or project id in the search box to get different projects that match

Improve project search backend

---

backend/services/project_service.py

From https://github.com/hotosm/tasking-manager/issues/2251 - updated cumulative  and per day count logic for validated and mapped tasks.
So for the example in the 2251 ticket in which tasks wer `mapped all one time, invalidate them, then mapped all, validated all and then reset the status of all tasks to ready to map` - stats would return:
```
{"stats": [{"date": "2020-01-24", "mapped": 0, "validated": 0, "cumulative_mapped": 0, "cumulative_validated": 0, "total_tasks": 112}]}
```
Project 8213 on this branch:
Project 8213 on staging:

Fix daily and absolute count values on contribution endpoint

---

frontend/src/components/taskSelection/index.js
frontend/src/components/taskSelection/messages.js
frontend/src/components/taskSelection/taskActivity.js
frontend/src/components/taskSelection/taskList.js
frontend/src/hooks/UseMemoCompare.js
frontend/src/hooks/UsePermissions.js
frontend/src/utils/sorting.js
frontend/src/utils/tests/sorting.test.js
frontend/src/utils/tests/updateTaskStatus.test.js
frontend/src/utils/updateTasksStatus.js

Resolves https://github.com/hotosm/tasking-manager/issues/2679
Resolves https://github.com/hotosm/tasking-manager/issues/2678
Please review carefully.
Wait 60s to check if the tasks get updated (both list and map). With another user in another browser window, start mapping a task and check if the update on the first browser occurs correctly. Split a task on the second window and see if the map and list get correctly updated on the first.
Do the same with a task activity modal open.

Solves errors caused by the periodic tasks updates

---

.circleci/config.yml
scripts/aws/cloudformation/tasking-manager.template.js

I have also added the URL and key variables to all stacks CircleCI, so it will work on staging/tm4/master once we merge to the respective branches.

Add image upload api envvars for deployment

---

backend/api/teams/resources.py
frontend/src/components/formInputs.js
frontend/src/components/teamsAndOrgs/teams.js
frontend/src/views/teams.js

Team editing was failing when we didn't update the organisation.

fix team editing error

---

frontend/src/components/teamsAndOrgs/messages.js
frontend/src/components/teamsAndOrgs/organisations.js
frontend/src/locales/en.json

when the request to image upload failed, it was causing the app to crash

handle better image upload errors

---

frontend/src/views/learn.js

Part of #2342. @JorgeMartinezG it's not perfect, but I could improve it...

Improve learn page responsiveness

---

frontend/src/components/projectDetail/projectDetailFooter.js

Closes #2651 
Hide `Add to Favorites` button for non-logged-in users.

Fix add to favorites button visibility

---

frontend/src/components/projectDetail/header.js
frontend/src/components/taskSelection/index.js
frontend/src/components/taskSelection/messages.js
frontend/src/components/taskSelection/taskActivity.js
frontend/src/components/taskSelection/taskList.js
frontend/src/locales/en.json
frontend/src/views/taskSelection.js

improve task selection page data fetching

---

frontend/src/utils/internationalization.js

make Ukrainian language available

---

frontend/package.json
frontend/src/hooks/UseInboxQueryAPI.js
frontend/src/hooks/UseProjectsQueryAPI.js
frontend/src/hooks/UseTaskContributionAPI.js

Replaces https://github.com/hotosm/tasking-manager/pull/2769

import stringify from query-string and update use-query-params lib

---

frontend/src/components/user/forms.js
frontend/src/store/actions/auth.js

how to test: go to the user settings page, update any info (and save if needed). The loader shouldn't appear.

don't show the loader when user is updating their settings

---

frontend/src/components/teamsAndOrgs/members.js
frontend/src/components/teamsAndOrgs/teams.js

- only show org logo html element if logo URL is available (team membership page)
- add vertical margins between team members avatar

improvements to teams page

---

backend/models/dtos/project_dto.py
backend/models/postgis/project.py

- Include license_id and other missing fields
- Remove area field
Closes #2829

Review project summary dto fields

---

frontend/src/components/taskSelection/index.js
frontend/src/components/taskSelection/taskList.js

- fix validation permission check when enabling or disabling 'Ready for validation' tasks list filter
- fix tasks status update after undo badimagery/validation

tasks selection page fixes

---

frontend/src/components/projectEdit/descriptionForm.js
frontend/src/components/projectEdit/metadataForm.js

display: inline-block on status, priority and mappingLevel radio fields

---

backend/services/project_admin_service.py
tests/backend/unit/services/test_project_admin_service.py

Resolves https://github.com/hotosm/tasking-manager/issues/2833

remove allowed_users validation when setting a project as private

---

frontend/src/components/projectCreate/navButtons.js

Preserve taskgrid values on step return

---

.circleci/config.yml

Add link to homepage banner video.

Add TM Homepage Video URL

---

frontend/public/index.html
frontend/src/App.js

set lang value on the root div

---

backend/api/organisations/resources.py
backend/api/teams/actions.py
backend/api/users/actions.py
backend/models/postgis/project.py
backend/models/postgis/user.py
backend/services/users/user_service.py
frontend/src/components/user/forms.js

- Add checks for incorrect user_id encoded in token.
- Modify get_user_by_id to staticmethod

User email patches

---

backend/services/project_search_service.py

This PR solves the issue related to project search. To be more specific, when text value has spaces.

Remove blank string when text_search field has spaces

---

backend/services/project_search_service.py

From #2887 - removed the redundant filter using author ID

Remove author filter from manage section on project search

---

backend/api/projects/resources.py

Add authorisation to project get

---

backend/services/messaging/message_service.py

closes #2904 
- **projects notifications:** For users that have a mapped task that was validated.
- **Mentions notifications** For users that receive any mention  within project/task comment textbox.
- **Comments notifications** For users that have contributed/favorited projects

Send messages according to user settings

---

.circleci/config.yml

This will bring staging back to 1 instance only.

Reduce staging stack to development autoscaling policy

---

backend/api/projects/resources.py
backend/services/project_search_service.py

Validate user role to include private projects in explore page

---

frontend/src/components/projectCreate/index.js
frontend/src/components/projectCreate/messages.js
frontend/src/components/projectCreate/setAOI.js
frontend/src/components/projectCreate/setTaskSizes.js
frontend/src/components/projectCreate/trimProject.js
frontend/src/locales/en.json

closes #2919  Also included fix when setting arbitrary tasks using uploaded file.

Array of polygons support in project creation

---

backend/models/postgis/project.py
backend/services/tags_service.py

Those functions are not used anymore

remove old organisation_tag and campaign_tag functions

---

backend/api/projects/resources.py
backend/models/postgis/project.py
backend/services/messaging/chat_service.py
backend/services/project_admin_service.py
backend/services/project_service.py
backend/services/team_service.py

From #2945
Is private? | Admin | Mapper | Project's org manager | Project's team manager | Project's allowed list
----------|--------|---------|-----------------------|--------------------------|--------------------
True | ✅ | ❌ |✅ |✅ |✅ 
False|✅ |✅ |✅ |✅ | N/A
Is draft? | Admin | Mapper | Project's org manager | Project's team manager |
----------|--------|---------|-----------------------|--------------------------
True | ✅ | ❌ |✅ |✅ |
False|✅ |✅ |✅ |✅ |

Project GET permissions for private & draft projects

---

backend/services/project_search_service.py

Validate admin role for project search on managed_by request

---

frontend/src/components/projectDetail/downloadButtons.js
frontend/src/components/projectDetail/index.js
frontend/src/components/projectDetail/messages.js
frontend/src/locales/en.json

- the buttons are visible only to logged in users with expert mode enabled

add download aoi & task grid buttons to the project detail page

---

backend/services/messaging/message_service.py
frontend/src/assets/styles/_extra.scss
frontend/src/components/notifications/notificationBodyCard.js
frontend/src/components/notifications/notificationCard.js

Notifications link fixes

---

frontend/src/hooks/UsePermissions.js
frontend/src/hooks/tests/UseEditOrgPermissions.test.js
frontend/src/views/messages.js
frontend/src/views/organisations.js

check if user is org manager on manage org page loading

---

frontend/public/index.html
frontend/src/components/editor.js
frontend/src/components/portal.js
frontend/src/components/taskSelection/action.js

iD was failing to load OSM data or other elements when it was loaded several times in the same session. This PR fixes it.

loads map/validation page inside a React Portal

---

frontend/src/utils/projectPermissions.js
frontend/src/utils/tests/permissionsToMap.test.js
frontend/src/utils/tests/permissionsToValidate.test.js

allow project author to map and validate their projects

---

frontend/src/utils/projectCompletenessCalc.js
frontend/src/utils/tests/projectCompletenessCalc.test.js

avoid tasks selection page to crash the app while tasks are loading

---

frontend/src/components/projectDetail/header.js
frontend/src/components/taskSelection/action.js
frontend/src/components/teamsAndOrgs/organisations.js

Fix other issue reported by @canunen https://github.com/hotosm/tasking-manager/issues/2864#issuecomment-629618359

avoid errors when project and org names in english are capitalized

---

backend/models/postgis/project.py
frontend/src/components/projectCreate/index.js

closes #2458. 
- In the project edit view, add categories and teams.
- Clone the project within the actions tab.
- Verify that categories, teams and others project fields are copied correctly

Project clone enhancements

---

client/index.html

A minor refresh of index.html replacing 'HOT' with  'TeachOSM'.

Update index with TeachOSM-specific pointers

---

frontend/src/hooks/UseTaskContributionAPI.js

This causes pagination within notifications view not working.

Include page stringParam for task Contributions

---

frontend/src/components/teamsAndOrgs/members.js
frontend/src/views/organisations.js
frontend/src/views/teams.js

Restore members when user cancel editing

---

backend/__init__.py
backend/services/messaging/chat_service.py
backend/services/project_service.py

Fix permissions related:
* Project GET
* task lock for validation/mapping
* post chat messages
Complete list of scenarios outlined here: https://docs.google.com/spreadsheets/d/1U5iFJLgBLW1h526bChamEqj0yGJ1-yZXye1V6kz1_Uo/edit#gid=0

Project permissions - GET/PATCH/POST

---

frontend/src/components/taskSelection/taskActivity.js
frontend/src/components/taskSelection/taskList.js

users allowed to validate a project can undo badimagery & finished tasks

---

frontend/package.json
frontend/yarn.lock

update iD react-tooltip, dompurify, shpjs, prettier

---

backend/__init__.py
backend/api/projects/actions.py
frontend/src/components/projectCreate/trimProject.js

Similar to TM3. The trim is performed within the backend. This solves the issue related to multipolygons with holes:

Implementation of project trim in the backend

---

frontend/src/components/taskSelection/action.js
frontend/src/components/taskSelection/actionSidebars.js
frontend/src/components/taskSelection/footer.js
frontend/src/components/taskSelection/lockedTasks.js
frontend/src/components/taskSelection/messages.js
frontend/src/components/taskSelection/tests/footer.test.js
frontend/src/components/taskSelection/tests/lockedTasks.test.js
frontend/src/locales/en.json
frontend/src/utils/openEditor.js
frontend/src/utils/testWithIntl.js

Resolves #2929, resolves #2582, resolves #2690 
Plus:
- Add tests to `LockedTasksModalContent` component
- Show message when JOSM is not running and with remote control enabled

improve JOSM loading and validation flow

---

.circleci/config.yml
frontend/package.json
frontend/src/components/editor.js
frontend/src/components/taskSelection/action.js
frontend/src/utils/openEditor.js
frontend/src/utils/tests/openEditor.test.js
frontend/src/views/taskAction.js
frontend/yarn.lock

- Update iD to 2.18.0-beta-3 and fix problem when loading iD Presets
- Fix problem map/validation page map when JOSM, Potlatch or Field Papers is the active editor
- Run deploy build command with some variables to avoid problems

4.0.9 deploy preparation

---

backend/api/projects/actions.py

remove parameter for set project as feature

---

backend/models/dtos/project_dto.py
backend/models/postgis/project.py
backend/services/project_search_service.py

list campaigns in projects

---

appspec.yml
scripts/aws/cloudformation/tasking-manager.template.js

- Remove unnecessary comments from appspec.yml
- Add example values for cfn-config parameter prompts
- Add resource tags to target group
- Get target group to use modern TLS ciphers with Forward Secrecy

Cleanup and simplify code

---

backend/services/messaging/templates/invalidation_message_en.txt
backend/services/messaging/templates/message_alert_en.html
backend/services/messaging/templates/message_alert_en.txt
backend/services/messaging/templates/validation_message_en.txt

update email notifications texts

---

frontend/src/components/paginator/index.js
frontend/src/components/paginator/tests/index.test.js

paginator style was breaking with more than 3 digits

---

frontend/src/components/projectDetail/questionsAndComments.js

Fix username popup in textarea component

---

backend/models/dtos/interests_dto.py
backend/models/postgis/interests.py
backend/services/interests_service.py
backend/services/users/user_service.py

removed from countProject and countUser of /api/v2/interests

---

frontend/package.json
frontend/src/components/taskSelection/taskList.js
frontend/src/components/taskSelection/tests/taskFilter.test.js
frontend/src/components/taskSelection/tests/taskStatus.test.js
frontend/yarn.lock

- Show task text search field and filters to all users (task selection page)
- Add tests
- Improve responsiveness

show tasks filters and text search to all users

---

backend/services/campaign_service.py

remove project in get campaign

---

backend/api/projects/resources.py
backend/models/dtos/project_dto.py
backend/services/project_search_service.py
frontend/src/views/campaigns.js
frontend/src/views/interests.js
frontend/src/views/management.js
frontend/src/views/organisations.js
frontend/src/views/teams.js

Include request parameter to omit map results in project search endpoint

---

backend/models/dtos/stats_dto.py
backend/services/stats_service.py
frontend/src/components/taskSelection/contributions.js

From https://github.com/hotosm/tasking-manager/issues/2983:
* replace left outer join with full outer join
* include both `mapped_by` and `validated_by` filter for user table join

Include all contributors for project_id/contributions

---

backend/models/postgis/message.py
backend/models/postgis/project.py
backend/models/postgis/task.py

Change from  sql to sqlalchemy queries

---

frontend/src/components/taskSelection/action.js

show number of task history actions on the sidebar of map/validate page

---

backend/models/postgis/project.py
backend/models/postgis/task.py

Related to #3213 
The times before and after:
Api test `api/v2/project/{project_id} `  data for example project_id = 6665
Times
| Before  (ms) | After (ms)  |
| ------------- | ------------- |
| 0.1387  | 0.0053  |

add lazy noload for relationship in project

---

backend/models/dtos/user_dto.py
backend/models/postgis/user.py
frontend/src/views/welcome.js

Per convo in https://github.com/hotosm/tasking-manager/issues/3175 - removed stats field from user DTO

Remove stats from user dto

---

backend/services/grid/split_service.py

Get project tasks

---

backend/services/project_admin_service.py

remove unneeded query

---

backend/models/postgis/user.py

change and  improve the query from  sql to sqlalchemy

---

backend/api/organisations/resources.py
frontend/src/assets/styles/_extra.scss
frontend/src/components/teamsAndOrgs/teams.js
frontend/src/components/teamsAndOrgs/tests/teams.test.js
frontend/src/components/user/messages.js
frontend/src/components/userDetail/headerProfile.js
frontend/src/components/userDetail/messages.js
frontend/src/components/userDetail/userTeamsOrgs.js
frontend/src/views/userDetail.js

Include organizations and teams in user profile

---

frontend/src/utils/openEditor.js
frontend/src/utils/tests/openEditor.test.js

Resolves #3272
Reference: https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#imagery

update imagery remote control command to JOSM

---

backend/api/annotations/resources.py
backend/api/comments/resources.py
backend/api/projects/activities.py
backend/api/projects/contributions.py
backend/models/postgis/project.py
backend/services/project_service.py

A small changes to improve endpoint response times.
Related to #3265

Existing project validation

---

backend/models/postgis/user.py

Change from sql to sqlalchemy in users to improve response times

change from sql to sqlalchemy in users

---

backend/models/dtos/stats_dto.py
backend/services/stats_service.py

closes #3282 
In this case to improve response time it is more convenient to use sql queries.
Before:    13000 ms
After:       329 ms

Improvement in statistics queries

---

backend/models/postgis/task.py
tests/backend/unit/services/test_mapping_service.py

Sort task history applying most recent first

---

frontend/src/components/projects/myProjectNav.js

- "Managed by me" - visible to PM team members and Org Managers
- "Created by Me" visible to everyone

show "Managed by me" and "Created by Me" filters on My Projects page

---

frontend/package.json
frontend/src/components/editor.js
frontend/src/components/taskSelection/action.js
frontend/src/components/taskSelection/actionSidebars.js
frontend/src/utils/openEditor.js
frontend/src/utils/tests/openEditor.test.js
frontend/yarn.lock

- Set locale programmatically instead of using the url query param
- Avoid iD from updating the document title

update iD to 2.18.2

---

backend/services/messaging/message_service.py

Store message in database even mention option is disabled

---

frontend/src/components/projectDetail/timeline.js
frontend/src/hooks/UseTimeDiff.js
frontend/src/hooks/tests/UseTimeDiff.test.js

format timeline X axes according to time interval between dates

---

backend/services/messaging/message_service.py
frontend/src/components/projectDetail/hashtagPaste.js
frontend/src/components/projectDetail/messages.js
frontend/src/components/projectDetail/questionsAndComments.js
frontend/src/components/projectDetail/tests/hashtagPaste.test.js
frontend/src/components/projectDetail/tests/osmchaButton.test.js
frontend/src/components/projectStats/tests/completion.test.js
frontend/src/components/projectStats/tests/taskStats.test.js
frontend/src/components/taskSelection/taskActivity.js
frontend/src/components/userDetail/tests/barListChart.test.js
frontend/src/components/userDetail/tests/editByNumbers.test.js
frontend/src/components/userDetail/tests/topCauses.test.js
frontend/src/components/userDetail/tests/topProjects.test.js
frontend/src/locales/en.json
frontend/src/utils/testWithIntl.js

Closes #3146. The trigger was modified to use # instead of @

Message managers feature

---

backend/models/postgis/team.py
backend/services/team_service.py

Segregation of functions between models and services

Change in get manager teams

---

backend/services/project_search_service.py

Improvement in project search
api : /api/v2/projects/?campaign=4+County+Digitization+Liberia
Also to improve pagination response times in project search, the [seq_page_cost](https://www.postgresql.org/docs/9.5/runtime-config-query.html#GUC-SEQ-PAGE-COST) parameter could be set in postgres.

improvement in project search

---

backend/models/dtos/organisation_dto.py
backend/models/dtos/team_dto.py
backend/models/postgis/team.py
backend/services/project_service.py
backend/services/team_service.py

Improving teams search queries

---

frontend/src/components/taskSelection/footer.js
frontend/src/components/taskSelection/messages.js
frontend/src/locales/en.json

handle plural case on "Validate selected tasks" button

---

frontend/src/components/taskSelection/taskActivity.js

parse markdown content on task history

---

backend/models/dtos/organisation_dto.py

Fix organisation update

---

backend/services/messaging/smtp_service.py
backend/services/messaging/template_service.py
tests/backend/unit/services/messaging/test_template_service.py

Resolves https://github.com/hotosm/tasking-manager/issues/3426

format username link on email content

---

backend/services/project_search_service.py

Project search case sensitive

---

backend/api/projects/actions.py
backend/api/utils.py
backend/models/postgis/notification.py
backend/services/messaging/message_service.py

Asynchronous sending messages

---

backend/api/projects/actions.py
backend/api/utils.py
backend/models/postgis/notification.py
backend/services/messaging/message_service.py

Reverts hotosm/tasking-manager#3332

Revert "Asynchronous sending messages"

---

backend/services/team_service.py

Per chat w/ @willemarcel - we've got a few issues on team filters and on further investigation fixed the table join type and filter conditions.

Filter and fetch team related

---

backend/services/messaging/message_service.py
frontend/src/components/comments/commentInput.js
frontend/src/components/comments/fileRejections.js
frontend/src/components/comments/hashtagPaste.js
frontend/src/components/comments/tests/fileRejections.test.js
frontend/src/components/comments/tests/hashtagPaste.test.js
frontend/src/components/comments/tests/uploadStatus.test.js
frontend/src/components/comments/uploadStatus.js
frontend/src/components/projectEdit/actionsForm.js
frontend/src/components/projectEdit/inputLocale.js
frontend/src/config/index.js
frontend/src/config/tests/config.test.js
tests/backend/unit/services/messaging/test_messaging_service.py

On "Message All Contributors" form:
- Add markdown support and drag & drop image upload
- On the email, add line stating that the message comes from the project managers
On project instructions/description fields:
- Add drag & drop image upload
Plus:
- mode dropzone settings to config file

Add markdown support and dropzone to project edit forms

---

frontend/src/components/taskSelection/taskList.js
frontend/src/components/taskSelection/tests/taskFilter.test.js

add unavailable tasks filter to validators

---

backend/services/messaging/smtp_service.py
frontend/src/views/verifyEmail.js

Frontend: Verify token and username variable before making Email Verification API request
Backend: generate verification token without converting email to lower case

Improve Email Verification

---

frontend/src/components/taskSelection/index.js
frontend/src/hooks/UseFetch.js

Resolves https://github.com/hotosm/tasking-manager/issues/1100

disable network requests if the app is not visible to user

---

backend/models/postgis/project.py

Per discussion updated the country serialisation approach

Handle country serialisation with inbuilt functions

---

frontend/src/components/button.js
frontend/src/components/formInputs.js
frontend/src/components/header/notificationBell.js
frontend/src/components/notifications/deleteNotificationsButton.js
frontend/src/components/notifications/inboxNav.js
frontend/src/components/notifications/messages.js
frontend/src/components/notifications/notificationCard.js
frontend/src/components/notifications/notificationResults.js
frontend/src/components/notifications/tests/deleteNotificationsButton.test.js
frontend/src/components/tests/checkBox.test.js
frontend/src/components/tests/selectAll.test.js
frontend/src/network/tests/server-handlers.js

Delete multiple messages feature

---

frontend/src/components/notifications/inboxNav.js
frontend/src/components/notifications/messages.js
frontend/src/locales/en.json

Add teams notifications filter

---

backend/services/messaging/message_service.py

don't send duplicated task comment messages

---

backend/services/messaging/chat_service.py
frontend/src/components/projectDetail/questionsAndComments.js

- Disable `Post` button while message is being sent
- Show success/error message
- Handle better comments update
- Avoid unneeded requests / component re-render

Refactor QuestionsAndComments component

---

frontend/src/components/projectStats/edits.js
frontend/src/views/projectStats.js

Change projectStats **edits** and **project timeline** section background color to tan.

Adjust section background color

---

docker-compose.yml

Fix Traefik version to 2.3

---

docker-compose.yml

Fix Traefik rule for backend

---

docs/setup-docker.md

how to setup a public host with persistent data and docker

---

frontend/src/components/userDetail/elementsMapped.js
frontend/src/components/userDetail/tests/elementsMapped.test.js

- Improve user tasks card display
- Add tests for ElementsMapped & TaskStats components
New layout

Improve user tasks card and add tests

---

frontend/src/components/taskSelection/messages.js
frontend/src/components/taskSelection/taskActivity.js
frontend/src/locales/en.json

Improve style of TaskActivity modal

---

docker-compose.yml

Restart containers automatically

---

frontend/package.json
frontend/src/components/editor.js
frontend/src/components/taskSelection/action.js
frontend/src/components/taskSelection/actionSidebars.js
frontend/src/store/actions/editor.js
frontend/src/store/reducers/editor.js
frontend/src/store/reducers/index.js
frontend/src/utils/openEditor.js
frontend/src/utils/tests/openEditor.test.js
frontend/yarn.lock

Resolves https://github.com/hotosm/tasking-manager/issues/2905

Save iD context to redux store to make it load correctly every time

---

backend/models/postgis/utils.py
backend/services/grid/split_service.py
backend/services/mapping_service.py
backend/services/messaging/message_service.py
backend/services/organisation_service.py
backend/services/project_admin_service.py
backend/services/project_search_service.py
backend/services/project_service.py
backend/services/team_service.py
backend/services/users/authentication_service.py
backend/services/users/osm_service.py
backend/services/users/user_service.py
backend/services/validator_service.py

Replace logger.error by .debug on Exceptions

---

backend/models/postgis/project.py

Fixes https://github.com/hotosm/tasking-manager/issues/3802

Handle NoneType condition check during project update

---

backend/models/postgis/project.py

During project clone copy interests, campaign and teams information to the cloned project without affecting the original project. To test:
* Choose a project with teams, interests and campaign information
* Clone a project with sufficient metadata info
* After clone, make sure both the clone and the original projects has the same metadata intact

Metadata copy for project clone

---

frontend/src/components/projectCreate/review.js

- Change colour of create button
- Improve vertical margins and text size

Improve style of Review step of project creation

---

backend/config.py
example.env

@d-rita is having difficulties to setup her environment, so I improve the text and the default values

Improve BASE and API URL instructions + delete TM_FRONTEND_BASE_URL

---

frontend/src/components/projectEdit/descriptionForm.js

Remove weekend restriction on Project's DueDate

---

frontend/src/components/projectCreate/index.js
frontend/src/components/projectCreate/projectCreationMap.js
frontend/src/components/projectCreate/setAOI.js

fixes: #2437
Please have a detailed look before merging. Users can drag and drop on either on the map or on the Input field

Added file dropdown feature to map creation

---

frontend/src/components/permissionsBlock.js
frontend/src/components/projectEdit/permissionsForm.js

**What does this PR do?** 
Refactor the validation and mapping permission sections of the PermissionsForm. 
**Steps Taken:**
- Create a PermissionsBlock component.
- Use the PermissionsBlock component for validation and mapping permissions.

Refactor validation and mapping permission blocks

---

frontend/src/components/header/notificationBell.js
frontend/src/hooks/UseOnResize.js
frontend/src/views/notifications.js

Co-Authored-By: Jonatan Asketorp <k3KAW8Pnf7mkmdSMPHz27@users.noreply.github.com>

Improve notification popup position

---

frontend/package.json
frontend/src/hooks/UseUploadImage.js
frontend/src/utils/slugifyFileName.js
frontend/src/utils/tests/slugifyFileName.test.js
frontend/yarn.lock

Slugify image filenames to upload

---

backend/__init__.py

Simplifies the operation and makes it slightly faster and more readable

Simplify leading, trailing slash strip

---

backend/services/messaging/smtp_service.py

Allow empty SMTP credentials

---

backend/api/projects/resources.py

Fixes https://github.com/hotosm/tasking-manager/issues/3973
Update signature for `NoGeometries` endpoint - set `authenticated_user_id` to `None` in the service function call. `/api/v2/projects/3597/queries/nogeometries/?as_file=false` should return a json. Right now it returns `500: Internal Server Error`

Update NoGeometries signature

---

frontend/src/components/editor.js
frontend/src/components/taskSelection/actionSidebars.js

Resolves #3916 
How to test: lock a task for mapping or validation in a project that has a custom imagery set, then lock in another project, test if both tasks are loaded on iD with the correct imagery. Best if tested in projects with different imagery.

Fix imagery loading in internal iD and className attrib on mapping sidebar

---

backend/models/dtos/project_dto.py
frontend/src/components/projects/myProjectNav.js
frontend/src/components/teamsAndOrgs/menu.js
frontend/src/components/userDetail/headerProfile.js
frontend/src/views/management.js
frontend/src/views/welcome.js

Avoid error on project list + set action=any on My / Manage projects pages

---

frontend/package.json
frontend/src/components/notifications/notificationBodyCard.js
frontend/src/components/user/content.js
frontend/src/utils/formattedRelativeTime.js
frontend/src/utils/selectUnit.js
frontend/src/utils/tests/formattedRelativeTime.test.js
frontend/src/utils/tests/selectUnit.test.js
frontend/yarn.lock

Improve Relative Time expressions

---

backend/__init__.py
backend/api/organisations/resources.py
backend/models/dtos/stats_dto.py
backend/services/organisation_service.py
backend/services/stats_service.py

Resolves https://github.com/hotosm/tasking-manager/issues/4053

Add organisation stats endpoint

---

frontend/src/components/taskSelection/action.js
frontend/src/components/taskSelection/multipleTaskHistories.js
frontend/src/components/taskSelection/taskActivity.js
frontend/src/components/taskSelection/tests/multipleTaskHistories.test.js

Load `TaskHistory` with the activities filter disabled by default to all users

Initialize TaskHistory with activities filter disabled to all users

---

backend/models/postgis/project.py

Remove trailing spaces on changeset comment when cloning project

---

backend/services/messaging/message_service.py
backend/services/messaging/smtp_service.py
tests/backend/integration/services/messaging/test_smtp_service.py

Not sure if this covers it (more places might need to be updated).
This should fix #3498.

Change email sending to only message verified users

---

frontend/package.json
frontend/src/components/contributions/taskCard.js
frontend/src/components/contributions/tests/taskCard.test.js
frontend/yarn.lock

Fix "Resume task" button link and add tests to TaskCard component

---

frontend/package.json
frontend/src/components/taskSelection/contributions.js
frontend/src/components/taskSelection/messages.js
frontend/src/components/taskSelection/tests/contributions.test.js
frontend/src/hooks/UseFilterContributors.js
frontend/src/hooks/tests/UseFilterContributors.test.js
frontend/src/locales/en.json
frontend/yarn.lock

Filter users by username on Project's contributors

---

backend/__init__.py
backend/api/tasks/statistics.py
backend/models/dtos/stats_dto.py
backend/services/stats_service.py

From https://github.com/hotosm/tasking-manager/issues/4011 -
How to test the PR?
- Using `http://127.0.0.1:5000/api/v2/tasks/statistics`, get task stats satisfying different query parameters, i.e. start_date, end_date, organisation_id, organisation_name, campaign, project_id, country

Task statistics feature

---

backend/api/tasks/statistics.py
backend/services/campaign_service.py
backend/services/stats_service.py

Query by campaign name rather than id for task stats

Task stats - campaign name query

---

backend/models/postgis/project.py

Avoid ZeroDivisionError in the percent mapped / validated / bad imagery

---

scripts/aws/cloudformation/tasking-manager.template.js

After review but before merging I need to update the infrastructure manually with the new parameter or the circleci update will fail.

Add TM_ORG_LOGO envvar to AWS backend

---

frontend/src/components/teamsAndOrgs/tasksStats.js
frontend/src/views/organisationStats.js

- Improve chart and error handling

Restrict organisation stats to only logged users

---

backend/__init__.py
backend/api/tasks/statistics.py
backend/api/users/statistics.py
backend/api/utils.py
backend/models/dtos/stats_dto.py
backend/services/stats_service.py

Resolves #4012
- It includes stats about level, gender, emailVerified (number of users that verified their email) and contributed (number of user that mapped at least one task)
@ramyaragupathy @d-rita I believe the queries are not the most performant ones, so let me know if we could improve it

User stats endpoint

---

backend/services/project_search_service.py

Fix contributor counting.

---

backend/services/organisation_service.py

Resolves https://github.com/hotosm/tasking-manager/issues/4232

fix error on PATCH organisation endpoint

---

frontend/src/components/teamsAndOrgs/messages.js
frontend/src/components/teamsAndOrgs/orgUsageLevel.js
frontend/src/components/teamsAndOrgs/tests/orgUsageLevel.test.js
frontend/src/hooks/UseOrganisationLevel.js
frontend/src/hooks/tests/UseOrganisationLevel.test.js

Show discounted cost for organisations under that type

---

frontend/src/views/campaigns.js
frontend/src/views/interests.js
frontend/src/views/licenses.js
frontend/src/views/organisations.js
frontend/src/views/teams.js

- Add titles to License management section
- Set titles with the name of the organization, team, campaign, category that is being edited

Improve some pages' title

---

frontend/src/components/contributions/myTasksNav.js
frontend/src/components/projectCreate/messages.js
frontend/src/components/projects/myProjectNav.js
frontend/src/components/teamsAndOrgs/management.js
frontend/src/components/teamsAndOrgs/messages.js
frontend/src/locales/en.json
frontend/src/views/contributions.js
frontend/src/views/licenses.js
frontend/src/views/organisations.js
frontend/src/views/users.js

Also fix alignment on Contributions section

Management section: rename "Add" buttons to "New" + fix alignment

---

frontend/src/components/interests/index.js
frontend/src/components/licenses/index.js
frontend/src/components/teamsAndOrgs/campaigns.js
frontend/src/components/teamsAndOrgs/organisations.js
frontend/src/components/teamsAndOrgs/teams.js
frontend/src/views/campaigns.js

Resolves https://github.com/hotosm/tasking-manager/issues/3231

Improve UX of orgs, teams, campaigns, licenses, categories editing forms

---

frontend/src/components/taskSelection/action.js

Adjust font size when the sidebar is hidden to avoid horizontal scroll

---

frontend/src/components/teamsAndOrgs/messages.js
frontend/src/components/teamsAndOrgs/organisations.js
frontend/src/locales/en.json
frontend/src/views/organisationManagement.js

- Show message when the organisation list is empty
- Enable the "All" orgs option by default to admin users

List all orgs to ADMIN users + add msg when orgs list is empty

---

backend/models/dtos/team_dto.py
backend/services/team_service.py
frontend/src/components/teamsAndOrgs/teams.js

Add public organisation page link to team membership page

---

frontend/src/components/projectCreate/index.js
frontend/src/components/projectCreate/navButtons.js
frontend/src/components/projectCreate/review.js

Move the Create button from review.js to navButtons.js because the other project creation step has all the buttons in the navButtons.js. This will ensure consistency and make it easier to allign the button on the same line.
Detailed Changes:
1. Move the handleCreate function from review.js to index.js.
2. Move button from the review.js to the navButton.js.
Result:
Fixes #3814

Change position of create/clone button

---

backend/api/users/resources.py
backend/models/postgis/user.py
backend/services/users/user_service.py
frontend/src/components/user/forms/personalInformation.js
frontend/src/components/user/messages.js
frontend/src/locales/en.json

Expose gender information only to the own user + add privacy note about it

Fix privacy issue on user detail API + add privacy notice

---

backend/models/dtos/mapping_dto.py
backend/models/postgis/task.py
backend/services/users/user_service.py
frontend/src/components/contributions/messages.js
frontend/src/components/contributions/taskCard.js
frontend/src/components/contributions/tests/taskCard.test.js
frontend/src/components/svgIcons/comment.js
frontend/src/components/svgIcons/index.js
frontend/src/locales/en.json

Fixes #4098 
Steps:
Screenshot:

Display number of comments per task on "My tasks" list

---

frontend/src/components/projectCreate/index.js
frontend/src/components/projectCreate/messages.js
frontend/src/components/projectCreate/navButtons.js
frontend/src/components/projectCreate/projectCreationMap.js
frontend/src/components/projectCreate/setAOI.js
frontend/src/components/projectCreate/setTaskSizes.js
frontend/src/components/projectCreate/trimProject.js
frontend/src/locales/en.json

Resolves #4118
This PR also contains a refactoring of the project creation sources and layers management and change the colours of the AoI and of the task grid.

Add option to discard tasks smaller than 2000m²

---

frontend/src/components/button.js
frontend/src/components/taskSelection/actionSidebars.js
frontend/src/hooks/UseAsync.js
frontend/src/hooks/tests/UseAsync.test.js

Resolves https://github.com/hotosm/tasking-manager/issues/2168

Show loading icon on buttons during mapping/validation API requests

---

frontend/src/assets/styles/_extra.scss
frontend/src/components/basemapMenu.js
frontend/src/components/projectCreate/projectCreationMap.js
frontend/src/components/projectEdit/messages.js
frontend/src/components/projectEdit/priorityAreasForm.js
frontend/src/components/svgIcons/index.js
frontend/src/components/svgIcons/mappedSquare.js
frontend/src/components/tests/basemapMenu.test.js

Add basemap options to Priority Areas form

---

frontend/src/components/header/signUp.js

Source of the solution: https://jsfiddle.net/ghvj4gy9/

Fix email validation regex

---

frontend/src/components/projectCreate/projectCreationMap.js
frontend/src/components/projectCreate/setTaskSizes.js

Remove fit map bounds to AoI during step 2 of project creation

---

backend/api/projects/resources.py
backend/models/dtos/project_dto.py
backend/services/project_search_service.py

Filter projects by last update

---

frontend/src/components/licenses/index.js
frontend/src/components/licenses/tests/licenses.test.js

- Test the licence-related components

Add tests for licences components

---

frontend/src/components/taskSelection/action.js
frontend/src/components/taskSelection/map.js

Show id of locked for validation tasks on the map when doing validation

---

frontend/src/components/teamsAndOrgs/messages.js
frontend/src/components/teamsAndOrgs/tests/tasksStats.test.js
frontend/src/locales/en.json

Fix spelling of "occurred"

---

frontend/src/components/projectDetail/downloadButtons.js
frontend/src/components/projectDetail/tests/downloadButtons.test.js
frontend/src/views/organisationManagement.js

- Add icon to download project aoi/grid buttons
- Improve style of Organisation Statistics button

Button styles and icons

---

frontend/src/components/projects/filterSelectFields.js

Make react-select component used on on stats and projects page clearable

---

frontend/src/components/taskSelection/taskActivity.js
frontend/src/components/taskSelection/tests/taskActivity.test.js

Validate taskHistory and add tests

---

frontend/src/components/taskSelection/index.js
frontend/src/components/taskSelection/tabSelector.js
frontend/src/components/taskSelection/tests/tabSelector.test.js

Separate the tasks selection page's TabSelector in a new component

---

frontend/src/components/comments/commentInput.js
frontend/src/components/taskSelection/actionSidebars.js

Resolves #4601 and always shows the `+ comment` button

Add option to autofocus when rendering the CommentInputField

---

frontend/src/hooks/UseContributorStats.js

https://sonarcloud.io/project/issues?id=hotosm_tasking-manager&issues=AXoO-bXoZjxed3Dzevpb&open=AXoO-bXoZjxed3Dzevpb

Use forEach instead of map in an array that doesn't return a result

---

backend/models/dtos/user_dto.py
backend/models/postgis/user.py

Remove redundant User DTO (missingMapsProfile and osmProfile) fields

---

frontend/src/components/projectEdit/actionsForm.js

Point to the right success message while messaging contributors

---

frontend/src/App.js
frontend/src/components/banner/index.js
frontend/src/components/banner/messages.js

Add notification banner for project archival

---

frontend/package.json
frontend/src/App.js
frontend/src/components/banner/index.js
frontend/src/components/banner/messages.js
frontend/src/components/projectEdit/actionsForm.js
frontend/yarn.lock
requirements.txt

Changes: 
- https://github.com/hotosm/tasking-manager/pull/4860 Fix success message for contributers (already deployed)
- https://github.com/hotosm/tasking-manager/pull/4867 Update apscheduler dependency (already deployed)
- https://github.com/hotosm/tasking-manager/pull/4931 Update iD version to 0.20.2 to fix Maxar Premium imagery in embedded iD
- https://github.com/hotosm/tasking-manager/pull/4919 Add homepage banner for announcements (thank you @ethan-nelson!)

Release 4.4.11

---

scripts/aws/cloudformation/tasking-manager.template.js

This PR will align the IaC with the current deployed setup.

Resize RDS for production

---

.github/ISSUE_TEMPLATE/feature_request.md

I added a PR for the BUG  template (https://github.com/hotosm/tasking-manager/pull/5026) and now adding for  a FEATURE.

Update issue templates- Feature

---

README.md

Reverts hotosm/tasking-manager#5034

Revert "Update READ.ME"

---

.circleci/config.yml

Just a little code cleanup- I also seem to have messed up the git history tree and was forced to make a merge commit on master, so pulling that back in so everything is aligned.

Cleans up some code I left in the last release, and rebases to master

---

frontend/src/components/user/list.js

Closes #4869 . This PR adds the 'Blocked' option to the dropdown to find blocked users.

Add 'blocked' option to dropdown

---

backend/models/postgis/project.py

set-default-permission-for-validation-to-intermediate-and-advanced

---

frontend/src/components/footer.js

This PR enables the support link to use the anchor tag on the footer section.

Fix support link in footer

---

backend/api/projects/actions.py
frontend/src/components/projectCreate/messages.js
frontend/src/components/projectCreate/trimProject.js
frontend/src/locales/en.json

Display error message for self intersecting AOI

---

docs/error_code.md

Adds a document that includes detailed descriptions of the error codes user might encounter when using the different endpoints of the Tasking Manager API.

Add tm error code document

---

frontend/src/components/taskSelection/taskList.js
frontend/src/store/actions/auth.js

Closes #4847 
Local storage value is cleared when the user logs out.

Store tasks sort order in local storage

---

frontend/src/components/notifications/inboxNav.js
frontend/src/components/notifications/notificationCard.js
frontend/src/components/notifications/notificationOrderBy.js
frontend/src/components/notifications/notificationResults.js
frontend/src/components/notifications/paginator.js
frontend/src/hooks/UseInboxQueryAPI.js
frontend/src/views/notifications.js

This PR does the following things:
- _Disable updating the notifications page with the notifications bell component._
The notifications page and notification bell component both make use of the redux store to list notifications. Hitting refresh on the popover component would update the notifications state in the redux store, consequently updating the notifications page. 
The use of redux store has been replaced with normal component states, which fix it.
- _Update the 'Sort by' dropdown with the newly selected value._
After fix:
- _Enable loading indicator whenever data is being fetched._
On the second screen capture from the top, you can see that the loading indicator is missing after a new dropdown option has been selected. This has been fixed, which can be seen on the third screen …

Notifications Page Enhancement

---

frontend/src/components/taskSelection/actionSidebars.js
frontend/src/components/taskSelection/index.js
frontend/src/components/taskSelection/map.js

Fit map bounds to just mapped/validated task(s)

---

frontend/src/components/notifications/notificationBodyCard.js

Fix displaced notification detail loading placeholder

---

frontend/src/components/taskSelection/actionSidebars.js
frontend/src/components/taskSelection/messages.js

Add radio button to validate all tasks at once

---

backend/models/postgis/project.py
frontend/yarn.lock

Populate project info locales only if not provided by user

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

New issue go to backlog:triage

---

frontend/src/views/learn.js

Closes #2871 
Screenshots for various screen widths:

Fix card heights in learn page

---

frontend/src/components/taskSelection/footer.js

Update editor only if allowed editors for mapping/validation doesn't contain that particular editor

---

backend/__init__.py
backend/config.py
backend/services/messaging/smtp_service.py
example.env
requirements.txt
tests/backend/integration/services/messaging/test_smtp_service.py

Closes #2501.
This PR is just a rework on #2506 as #2506 has too many conflicts to merge it directly

Use flask-mail instead of directly using smtplib [ Rework on #2506 ]

---

frontend/src/components/projectEdit/messages.js
frontend/src/locales/en.json
frontend/src/views/projectEdit.js

Add message if no editor is selected for mapping or validation

---

frontend/src/components/projectEdit/priorityAreasForm.js

Reset draw mode after clearing priority area

---

backend/services/messaging/chat_service.py
backend/services/messaging/message_service.py
backend/services/messaging/smtp_service.py
backend/services/messaging/templates/message_alert_en.html
tests/backend/integration/services/messaging/test_chat_service.py
tests/backend/integration/services/messaging/test_messaging_service.py

Show project title instead of project id in notifications

---

frontend/src/components/alert/index.js
frontend/src/components/messages.js
frontend/src/components/projectCreate/index.js
frontend/src/components/projectCreate/projectCreationMap.js
frontend/src/components/projectDetail/index.js
frontend/src/components/projectEdit/priorityAreasForm.js
frontend/src/components/projects/projectsMap.js
frontend/src/components/taskSelection/map.js
frontend/src/components/userDetail/countriesMapped.js
frontend/src/components/webglUnsupported.js
frontend/src/locales/en.json

Closes #4119 
**Screenshots:**
Project creation:
Countries Mapped in user's stats:
Task selection:
Explore:
Priority areas in project edit:

Add alert messages for unsupported WebGL context in map components

---

backend/models/postgis/team.py
backend/services/team_service.py
frontend/src/views/teams.js

Allow updating team member role

---

frontend/src/App.js
frontend/src/components/header/index.js
frontend/src/components/header/tests/menuItens.test.js
frontend/src/components/user/content.js
frontend/src/components/user/forms/settings.js
frontend/src/views/learn.js
frontend/src/views/quickstart.js

Make learn page sections linkable

---

backend/services/messaging/smtp_service.py

Handle SMTP errors and log in sentry

---

frontend/src/components/taskSelection/taskList.js

Position textfield clear icon inside input field on tasks selection page

---

backend/api/users/resources.py
backend/models/dtos/user_dto.py
backend/models/postgis/user.py
backend/services/project_admin_service.py
docs_old/error_code.md
frontend/src/components/projectEdit/actionsForm.js
frontend/src/components/projectEdit/messages.js

Add option to transfer project ownership to sys/super admins. Linked with #5250

Fix transfer project ownership to admins

---

frontend/package.json

Closes https://github.com/hotosm/tasking-manager/issues/5267

Run prettier on all JS files inside src

---

backend/config.py
backend/services/messaging/message_service.py
backend/services/messaging/templates/message_alert_en.html
tests/backend/unit/services/messaging/test_messaging_service.py

This PR adds the project name in addition to the project ID to make emails and notifications more meaningful.

Add project name and Id in notifications

---

backend/models/dtos/message_dto.py
backend/models/postgis/message.py
backend/services/messaging/message_service.py
backend/services/users/user_service.py
frontend/src/components/notifications/notificationBodyCard.js
frontend/src/components/notifications/notificationCard.js

Display user picture in notifications

---

frontend/src/components/projectEdit/metadataForm.js

Remove asterisk from extra iD params label

---

frontend/src/components/projectEdit/instructionsForm.js
frontend/src/components/projectEdit/messages.js
frontend/src/locales/en.json

Disable support to remove default generated changeset comment

---

frontend/src/App.js
frontend/src/components/banner/TopBanner.js
frontend/src/components/banner/styles.scss

This PR adds a component to display a banner on the top of the landing page.
Sample banner screenshot:

Add banner on the landing page

---

backend/services/messaging/message_service.py
backend/services/messaging/templates/encourage_mapper_en.html
tests/backend/unit/services/messaging/test_messaging_service.py

Format all links with default colour in emails

---

backend/models/postgis/custom_editors.py
backend/models/postgis/project.py
tests/backend/unit/models/postgis/test_custom_editor.py

Fix custom editor clears after project clone

---

backend/api/organisations/resources.py
backend/models/dtos/organisation_dto.py
backend/models/postgis/banner.py
backend/services/organisation_service.py
tests/backend/api/organisations/test_resources.py
tests/backend/integration/services/test_organisation_service.py
tests/backend/unit/models/postgis/test_organisation.py

Add stats in list all organisations endpoint

---

frontend/src/components/projectDetail/index.js

Make Download Tasks Grid and Download AOI buttons available to all users

---

backend/models/postgis/project.py
tests/backend/api/projects/test_resources.py
tests/backend/helpers/test_helpers.py

Fix failing project deletion due to custom editor

---

frontend/src/assets/styles/_extra.scss
frontend/src/views/swagger.js

Add height for swagger iframe for small screens

---

frontend/src/components/teamsAndOrgs/teams.js

Display organization icon as inline block

---

frontend/src/components/user/content.js

Remove interestsLead message from WelcomeCard

---

backend/models/postgis/user.py

Sort based on substring position asc in users filtering

---

frontend/src/components/taskSelection/taskList.js

Display username and formatted relative time on task list tooltip

---

frontend/src/components/teamsAndOrgs/members.js

Add button on dropdown option labels when editing team members list

---

.circleci/config.yml
requirements.txt

Set importlib-metadata version to 4.13.0

---

backend/__init__.py

Fix endpoint to fetch user invalidated tasks

---

frontend/src/components/user/forms/personalInformation.js

Allow '+' character in email address username

---

frontend/src/components/taskSelection/action.js

Include icons of types of mapping on the task action page

---

frontend/src/assets/styles/_extra.scss
frontend/src/assets/styles/contributions.scss
frontend/src/assets/styles/index.scss
frontend/src/components/projectStats/edits.js
frontend/src/components/statsCard.js
frontend/src/components/teamsAndOrgs/management.js
frontend/src/components/tests/statsCard.test.js
frontend/src/components/userDetail/contributionTimeline.js
frontend/src/components/userDetail/editsByNumbers.js
frontend/src/components/userDetail/elementsMapped.js
frontend/src/components/userDetail/headerProfile.js
frontend/src/components/userDetail/tests/editByNumbers.test.js
frontend/src/components/userDetail/tests/topCauses.test.js
frontend/src/components/userDetail/tests/topProjects.test.js
frontend/src/components/userDetail/topCauses.js
frontend/src/components/userDetail/topProjects.js
frontend/src/views/contributions.js
frontend/src/views/project.js
frontend/src/views/teams.js
frontend/src/views/userDetail.js

Large screens:
Medium screens:
Small screens:

Update styles for user stats under contributions section

---

frontend/src/components/user/content.js
frontend/src/components/userDetail/headerProfile.js
frontend/src/components/userDetail/tests/headerProfile.test.js

From `osmcha.mapbox.com` to `osmcha.org`

Update OSMCha URLs

---

backend/models/dtos/team_dto.py
frontend/src/components/teamsAndOrgs/members.js
frontend/src/views/teams.js

Resolves https://github.com/hotosm/tasking-manager/issues/5441

Include all team members on payload for team join notifications request

---

frontend/src/App.js

Closes https://github.com/hotosm/tasking-manager/issues/5456

Redirect from /learn to /learn/map

---

frontend/src/components/taskSelection/index.js
frontend/src/components/taskSelection/messages.js

Closes https://github.com/hotosm/tasking-manager/issues/3918
_Screenshot:_

Handle random task selection enforcement on task selection page

---

frontend/src/components/taskSelection/taskActivity.js
frontend/src/components/taskSelection/taskList.js

Closes #5486. Also, it updates the tasks list container overflow styling to auto.

Revise popup implementation for task detail

---

frontend/src/components/comments/commentInput.js

- Resolves https://github.com/hotosm/tasking-manager/issues/5491
- Adds support to allow space in the middle of mentions

Handle tab click event to select user handles

---

frontend/src/assets/styles/_extra.scss
frontend/src/components/button.js
frontend/src/components/comments/commentInput.js
frontend/src/components/comments/messages.js
frontend/src/components/progressBar.js
frontend/src/components/projectCard/projectProgressBar.js
frontend/src/components/projectCard/tests/projectProgressBar.test.js
frontend/src/components/projectDetail/bigProjectTeaser.js
frontend/src/components/projectDetail/downloadButtons.js
frontend/src/components/projectDetail/favorites.js
frontend/src/components/projectDetail/footer.js
frontend/src/components/projectDetail/header.js
frontend/src/components/projectDetail/index.js
frontend/src/components/projectDetail/infoPanel.js
frontend/src/components/projectDetail/questionsAndComments.js
frontend/src/components/projectDetail/shareButton.js
frontend/src/components/projectDetail/styles.scss
frontend/src/components/projectDetail/tests/favorites.test.js
frontend/src/components/taskSelection/imagery.js
frontend/src/components/taskSelection/map.js
frontend/src/components/taskSelection/resourcesTab.js
frontend/src/components/teamsAndOrgs/teams.js
frontend/src/components/user/tests/userAvatar.test.js
frontend/src/hooks/UseAvatarStyle.js
frontend/src/hooks/tests/UseAvatarStyle.test.js
frontend/src/views/userDetail.js

Large screens:
Medium screens:
Small screens:

Revise styles for the project detail page

---

backend/services/mapping_service.py

Fix issue with undo when multiple same status

---

frontend/src/components/projects/moreFiltersForm.js
frontend/src/components/teamsAndOrgs/tasksStats.js
frontend/src/utils/countries.js

Closes #5479 -- always use English locale value as payload.

Always use English locale as country payload

---

frontend/src/assets/styles/_extra.scss
frontend/src/components/header/burgerMenu.js
frontend/src/components/header/index.js
frontend/src/components/header/notificationBell.js
frontend/src/components/header/styles.scss
frontend/src/components/horizontalScroll/index.js
frontend/src/components/horizontalScroll/styles.scss
frontend/src/components/localeSelect.js
frontend/src/components/projectDetail/footer.js

The significant change in this PR is the inclusion of clickable arrow icons to support and handle horizontal scrolling of the overflowing navigation menus. Also, revises the spacing of the components and overall responsiveness.

Brush up on responsiveness of the navigation bar

---

frontend/src/components/taskSelection/lockedTasks.js

Revise conditionals for displaying the JOSM error on modal

---

frontend/src/components/projects/moreFiltersForm.js
frontend/src/components/projects/orderBy.js
frontend/src/components/projects/projectSearchBox.js
frontend/src/components/projects/projectSearchResults.js
frontend/src/components/projects/tests/filterSelectFields.test.js
frontend/src/components/projects/tests/mappingTypeFilterPicker.test.js
frontend/src/components/projects/tests/moreFiltersForm.test.js
frontend/src/components/projects/tests/myProjectNav.test.js
frontend/src/components/projects/tests/orderBy.test.js
frontend/src/components/projects/tests/projectNav.test.js
frontend/src/components/projects/tests/projectSearchBox.test.js
frontend/src/components/projects/tests/projectSearchResults.test.js
frontend/src/components/projects/tests/projectsMap.test.js
frontend/src/network/tests/mockData/projects.js
frontend/src/network/tests/server-handlers.js
frontend/src/network/tests/server.js
frontend/src/views/project.js
frontend/src/views/tests/project.test.js

This PR updates test cases and adds mock request handlers for endpoints used in the projects list page.
Something new worth mentioning in this pull request is the ability to mock error responses; it adds faulty handlers to mock errors in network requests.

Update tests for projects list page

---

frontend/src/views/login.js
frontend/src/views/organisationStats.js

Handle navigation from useEffect, not from conditional cases

---

frontend/src/components/taskSelection/styles.scss
frontend/src/components/taskSelection/taskActivity.js

Attempting to implement this layout:
Latest:

Revamp activities UI in task detail modal

---

frontend/src/views/management.js
frontend/src/views/projectEdit.js
frontend/src/views/stats.js
frontend/src/views/tests/taskSelection.test.js

Prompt user to login before showing permission errors

---

frontend/src/components/taskSelection/action.js

Display priority area in tasks map in task action page

---

frontend/src/components/taskSelection/map.js

Revise height and width of container that displayed hovered task ID in task action page while validating

---

backend/api/issues/resources.py
backend/models/postgis/mapping_issues.py
backend/services/mapping_issues_service.py
tests/backend/helpers/test_helpers.py
tests/backend/integration/api/issues/test_resources.py

This PR handles issues-related API endpoint tests.
- pull and checkout test branch using `git fetch origin && git checkout chore/add-issues-tests`

Add issues tests

---

scripts/aws/cloudformation/tasking-manager.template.js

AWS allows multiple layers of security for S3 buckets. This is an initial change to make the S3 bucket objects private and accessible only through CloudFront service (AWS CDN)
This change also introduces an OriginAccessPolicy that signs requests between CloudFront and S3

Secure and make Frontend S3 bucket private

---

backend/models/postgis/task.py

closes #2911 
How to test: 
Please make sure you have validation permission on project you're testing and you're not system admin.
- Go to projects tasks view and request re-validation on any validated task from task activity popup.
- Check if the task status is now changed to "MAPPED" i.e. ready for validation.
- Click on same task and click on `Validate selected task` button.
- Check if you can lock the task for validation.

Allow validator to revalidate task they have requested revalidation

---

frontend/src/components/progressBar.js
frontend/src/components/projectEdit/inputLocale.js
frontend/src/components/taskSelection/actionSidebars.js
frontend/src/components/taskSelection/tests/actionsTabsNav.test.js
frontend/src/components/taskSelection/tests/map.test.js
frontend/src/views/welcome.js

closes #5727 
How to test:
_**For code review, you can just review commit https://github.com/hotosm/tasking-manager/pull/5728/commits/2d1dfe871031649969c7922d4a435ad2e9572601 as other commit just contains code formatting changes.**_
- Comment the lines below as if user has mapped on any projects before they will be redirect to My Contributions page from welcome page.
https://github.com/hotosm/tasking-manager/blob/45e799e4b3d59ba831246c3b06e69a35d79b6a43/frontend/src/views/welcome.js#L82-L86
- Comment condition so that component `NewContributor` is displayed.
https://github.com/hotosm/tasking-manager/blob/45e799e4b3d59ba831246c3b06e69a35d79b6a43/frontend/src/views/welcome.js#L90-L94
- Go to` /welcome` page and verify if the projects are displayed on grid view.

Display recommended projects in grid view on the welcome page.

---

frontend/src/views/root.js

Fix footer collapse by wrapping root container with flex column

---

frontend/src/components/projects/projectSearchResults.js

Display list view for projects only if the section is management

---

frontend/src/components/taskSelection/taskList.js

Use keys for comments from taskIds

---

README.md
docs/contributing.md
docs/developers/contributing-guidelines.md
docs/developers/versions-and-releases.md
docs/sysadmins/ci-cd.md
docs/sysadmins/deployment.md

cc @petya-kangalova @robsavoye @willemarcel

fixing typos and removing trailing spaces in deployment.md

---

frontend/src/components/projectEdit/teamSelect.js

Add optional chaining to ensure availability of team list

---

frontend/src/components/teamsAndOrgs/management.js
frontend/src/components/teamsAndOrgs/organisations.js
frontend/src/components/teamsAndOrgs/teams.js
frontend/src/views/organisationManagement.js
frontend/src/views/teams.js
frontend/src/views/tests/organisationManagement.test.js

Handle tab selection for teams and orgs

---

backend/api/system/authentication.py
backend/api/system/general.py
backend/api/system/image_upload.py
backend/services/messaging/smtp_service.py
backend/services/users/authentication_service.py
tests/backend/integration/api/system/test_authentication.py
tests/backend/integration/api/system/test_general.py
tests/backend/integration/api/system/test_image_upload.py
tests/backend/integration/api/system/test_statistics.py

This PR ensures test cases for following endpoints associated with the system section:
| Transaction                                                       | Total hits in last 3 months |
| ----------------------------------------------------------------- | ----------- |
| backend.api.system.general:systemheartbeatapi                     | 2.8 million |
| backend.api.system.banner:systembannerapi                         | 257k        |
| backend.api.system.statistics:systemstatisticsapi                 | 184k        |
| backend.api.system.authentication:systemauthenticationloginapi    | 84.2k       |
| backend.api.system.authentication:systemauthenticationcallbackapi | 56.9k       |
| backend.api.system.authentication:systemauthenticationemailapi    | 13k         |
| …

Add test cases for endpoints associated with system section.

---

frontend/src/components/notifications/actionButtons.js
frontend/src/components/notifications/notificationResults.js
frontend/src/components/notifications/tests/actionButtons.test.js
frontend/src/views/notifications.js

Handle deletion of all notifications in the last page

---

frontend/src/components/taskSelection/actionSidebars.js

Conditionally render copy comment to other tasks button

---

docs/code_of_conduct.md

Fixing some preposition in the docs

Update Code of conduct.md

---

frontend/src/components/button.js
frontend/src/components/dropdown.js
frontend/src/hooks/UseOnClickOutside.js

Fixes issue #5864 
I have fixed the issue by referencing the correct component for using the "useOnClickOutside" hook, previously DropDownContent button was being referenced which was causing the bug and the click on the menu buttons was also being listened as an outside click. I referenced the menu button itself so now only the outside clicks are listened.
https://github.com/hotosm/tasking-manager/assets/57634631/6244219b-7099-4a80-9d44-4c8b99d6db16
@mojodna please review

solved the dropdown toggle bug

---

backend/services/messaging/templates/message_alert_en.html

Add task id and link to email when user is mentioned 

---

frontend/src/components/header/index.js
frontend/src/components/header/tests/menuItems.test.js
frontend/src/routes.js

This pull request attempts to enhance the navigation experience and address navigation inconsistencies in the 'learn' page.

Navigation enhancements: improve 'learn' page access and redirection

---

frontend/src/views/organisationDetail.js

Encode organisation name query parameter when navigating to the Explore Projects page

---

frontend/src/components/banner/topBanner.js
frontend/src/views/root.js

Reverts hotosm/tasking-manager#5930

Revert "Keep the footer at the bottom on a short page"

---

frontend/src/components/teamsAndOrgs/organisations.js

https://github.com/hotosm/tasking-manager/issues/5023#issuecomment-1653096473

Replace text 'administrators' with 'managers' on organisation card

---

.circleci/config.yml

fix for https://github.com/hotosm/tasking-manager/pull/6039

Enable sourcemaps for frontend deployments

---

frontend/src/assets/styles/_extra.scss

Fix markdown editor code tag style issue

---

frontend/src/components/projectDetail/questionsAndComments.js

Fix username tags not displaying issue in comment section in project Q&A

---

frontend/src/components/taskSelection/actionSidebars.js

Fix incomplete contributors list in task comments for multiple tasks validation case

---

frontend/src/components/projects/projectCardPaginator.js
frontend/src/components/projects/tests/projectCardPaginator.test.js
frontend/src/views/contributions.js

Fix Pagination links missing under My Tasks section

---

frontend/src/views/settings.js

Fix crash issue when user logout from settings page

---

scripts/aws/cloudformation/tasking-manager.template.js

- Increase API Backend load balancer timeout from 60s to 180s
- Bump PostgreSQL engine version for AWS RDS from 11.19 to 13.10
- Cleanup unused Route53 entry (must be removed)
- Enable HTTP/2 in API Backend load balancer explicitly (no infra change)
- Add experimental dummy Route53 entries to new tasks.hotosm.org hosted zone. Both A and AAAA resource records are added

Increase API load balancer timeout

---

.github/FUNDING.yml

Adds a sponsorship button to the repository.

Create Sponsorship Button

---

docs/developers/tmschema.md

This docs is being moved from the tm-admin project, as it's TM specific. It includes content on all of the database tables, and their functionality. This is a work in progress, I'll be expanding this doc over time as I dig deeper into the database.

Add doc on the database schema

---

README.md
docs/about.md
docs/index.md
docs/sysadmins/migration.md
mkdocs.yml

Minor bug fixes in docs, and add new content.

fix: Fix relative links, add new docs to the menu

---

.circleci/config.yml

Next release we should update this to 2024 version, changelog here: https://black.readthedocs.io/en/stable/change_log.html#id5

Fix version of black to last working version

---

frontend/src/components/projectDetail/downloadOsmData.js

- Tracks matomo event for each click on download 
- First deploy it in stage setup if it successfully shows up in matomo that means its working 
- None so far , looks like matomo works considerably okay

Feature:  Matomo Track for OSM Downloads

---

frontend/public/index.html

- This PR  updates matomo configuration , removing outdated pwink.js

Update Matomo Configurations 

---

frontend/src/components/userDetail/headerProfile.js
frontend/src/components/userDetail/tests/headerProfile.test.js
frontend/src/views/tests/contributions.test.js

Remove `Missing Maps` link and fix tests

---

frontend/src/components/projectStats/contributorsStats.js

Fix `Project Stats` page crash issue for `Archived` projects

---

example.env
frontend/package.json
frontend/src/api/projects.js
frontend/src/components/projectDetail/index.js
frontend/src/components/projectDetail/liveViewButton.js
frontend/src/components/projectDetail/messages.js
frontend/src/config/index.js
frontend/src/routes.js
frontend/src/views/projectLiveMonitoring.css
frontend/src/views/projectLiveMonitoring.js
frontend/yarn.lock

This PR adds the Live Monitoring view to the Tasking Manager.

Live Monitoring View

---

frontend/src/components/comments/commentInput.js

Fix `404 Network Error` in `Comments Section`

---

frontend/src/components/taskSelection/index.js

Add `Edit Project` button on `Task Selection` page

---

backend/__init__.py
backend/api/users/statistics.py
backend/config.py
frontend/src/api/stats.js
frontend/src/components/teamsAndOrgs/featureStats.js
frontend/src/config/index.js
frontend/src/network/genericJSONRequest.js

- fix #6271 
New api endpoint `users/statistics/ohsome/` to proxy ohsome api's through tasking manager

feat: ohsome proxy api for user stats

---

frontend/src/api/projects.js

Fix Project Instructions not picking up user opted language issue

---

backend/services/messaging/message_service.py
frontend/src/api/projects.js

A brief description of how this solves the issue.
Did you attempt any other approaches that are not documented in code?

Merge to main in preparation for release v4.7.2

---

frontend/src/views/projectLiveMonitoring.js

Wait for `project` and `areaOfInterest` to be ready before loading statistics and features list on the Live Monitoring View to prevent calling the Underpass API with empty request data.

Fix for loading Live Monitoring View

---

frontend/src/views/projectLiveMonitoring.js

Project's hashtag is configurable, for example`#hotosm-project` is used in production and `#hotosm-project-dev` in the development server. In the Live Monitoring view, the hashtag was harcoded, this PR adds the config variable to it.

+ Configurable project's hashtag on Live Monitoring

---

frontend/src/components/projectCreate/index.js

Fix project name validation error on cloning project

---

backend/api/campaigns/resources.py
backend/models/dtos/campaign_dto.py
backend/models/postgis/campaign.py
backend/services/campaign_service.py

Campaign Get api now works for fastapi app.

feat: Campaigns get api for fastapi app

---

scripts/aws/cloudformation/tasking-manager.template.js

Updates the AWS Resource tags to standardize for cost and project tracking. There are no feature or software changes in this PR.

Update AWS resource tags for cost tracking

---

backend/api/campaigns/resources.py
backend/api/system/authentication.py
backend/models/dtos/campaign_dto.py
backend/models/postgis/organisation.py
backend/services/campaign_service.py
backend/services/organisation_service.py
backend/services/users/authentication_service.py
backend/services/users/user_service.py

Campaign api post is now asynchronous for fastapi app.

feat: Async post for campaigns api

---

backend/api/projects/resources.py
backend/models/postgis/project.py
backend/models/postgis/task.py
backend/services/project_service.py

Project retrieve api works asynchronously.

Refac: Refactored project retrieve api to work asynchronously

---

backend/api/partners/resources.py

- 
Checking for admin role was missing on the Partners API.

Fix missing permissions check on Partners API

---

Dockerfile
backend/api/organisations/resources.py
backend/models/postgis/organisation.py
backend/services/organisation_service.py
docker-compose.yml

Organizations get and retrieve apis both authenticated and open along with organization statistics now works asynchronously.

feat: Organisations get apis with statistics

---

backend/api/organisations/campaigns.py
backend/api/projects/campaigns.py
backend/services/campaign_service.py

Organisation campaigns api and project campaign apis now works in async context.

feat: Organisation campaigns and project campaign get apis

---

backend/api/organisations/resources.py
backend/api/projects/resources.py
backend/api/projects/statistics.py
backend/models/dtos/organisation_dto.py
backend/models/postgis/organisation.py
backend/models/postgis/task.py
backend/models/postgis/user.py
backend/services/campaign_service.py
backend/services/organisation_service.py
backend/services/project_service.py

Organisation post and patch apis.

feat: Organisation post and patch patch apis

---

frontend/src/utils/internationalization.js

Fix mismatch value for language json file for Traditional Chinese

---

backend/api/campaigns/resources.py
backend/api/countries/resources.py
backend/api/organisations/campaigns.py
backend/api/organisations/resources.py
backend/api/projects/resources.py
backend/models/dtos/interests_dto.py
backend/models/dtos/project_dto.py
backend/models/dtos/team_dto.py
backend/models/postgis/project.py
backend/models/postgis/project_info.py
backend/models/postgis/task.py
backend/services/campaign_service.py
backend/services/project_service.py
backend/services/tags_service.py

Retrieve project and countries api refactored with encode databases and raw sql.

Fastapi refactor

---

backend/api/projects/resources.py
backend/models/dtos/project_dto.py
backend/models/dtos/stats_dto.py
backend/models/postgis/project.py
backend/models/postgis/project_info.py
backend/services/project_search_service.py
backend/services/project_service.py

Project list refactored to work asynchronously and pagination util refactored.

Project list api and pagination util refactored

---

README.md
docs/developers/development-setup.md

Corrected typo (docke -> docker)

---

.circleci/config.yml

A brief description of how this solves the issue.
Did you attempt any other approaches that are not documented in code?
- 🔠 Does this PR introduce or change any environment variables? If so, make sure to specify this change in the description.

Temporarily disable automatic deployment of dev branch to servers for e2e testing

---

backend/api/projects/resources.py
backend/api/projects/statistics.py
backend/api/system/general.py
backend/services/recommendation_service.py
backend/services/stats_service.py

Similar projects and popular projects apis refactored with encode databases and raw sql. Also, healthcheck api fixed.

Similar and Popular projects apis refactored and heartbeat api fixed

---

backend/models/dtos/campaign_dto.py
backend/models/dtos/organisation_dto.py

- Fastapi docs was not working because there was a serialization error
- To fix this changes previous filed validators to new method

Fastapi api migration fixes

---

backend/api/tasks/actions.py
backend/models/postgis/task.py
backend/services/mapping_service.py
backend/services/project_admin_service.py
backend/services/validator_service.py

Map all tasks, Validate all tasks and Reset all tasks refactored.

Map all tasks, Validate all tasks and Reset all tasks refactored

---

backend/api/tasks/resources.py
backend/models/postgis/task.py
backend/services/mapping_service.py

Export project tasks in xml and gpx.

Project tasks gpx and xml export

---

backend/api/comments/resources.py
backend/api/interests/resources.py
backend/api/issues/resources.py
backend/api/licenses/actions.py
backend/api/licenses/resources.py
backend/api/notifications/actions.py
backend/api/notifications/resources.py
backend/api/organisations/campaigns.py
backend/api/organisations/resources.py
backend/api/projects/activities.py
backend/api/projects/campaigns.py
backend/api/projects/contributions.py
backend/api/projects/favorites.py
backend/api/projects/resources.py
backend/api/projects/statistics.py
backend/api/system/applications.py
backend/api/system/authentication.py
backend/api/tasks/actions.py
backend/api/tasks/resources.py
backend/api/users/resources.py
backend/api/users/statistics.py
backend/models/postgis/utils.py
backend/services/campaign_service.py
backend/services/mapping_service.py
backend/services/organisation_service.py
backend/services/project_search_service.py
backend/services/project_service.py
backend/services/validator_service.py

JSONResponse handling, errors logs and cleanups.

JSONResponse handling and cleanups

---

backend/services/project_search_service.py

mapping types, interests, favorites project filters fixed.

fix project filters

---

backend/models/dtos/project_dto.py
backend/services/validator_service.py

fix project info dto

---

backend/models/postgis/project.py
backend/services/project_search_service.py

fix project teams patch

---

backend/api/projects/resources.py
backend/models/dtos/campaign_dto.py
backend/models/dtos/interests_dto.py
backend/models/dtos/message_dto.py
backend/models/dtos/organisation_dto.py
backend/models/dtos/project_dto.py
backend/models/dtos/team_dto.py
backend/models/dtos/user_dto.py
backend/models/postgis/priority_area.py
backend/models/postgis/project.py
backend/models/postgis/project_info.py
backend/models/postgis/team.py

Project patch now works and pydantic models refactored.

Project patch fixed and dtos refactored

---

backend/api/organisations/resources.py
backend/models/dtos/message_dto.py
backend/models/postgis/organisation.py
backend/models/postgis/task.py
backend/services/messaging/message_service.py
backend/services/organisation_service.py
backend/services/project_search_service.py

All messages, organisation retrieve and task activities issue fixes.

All messages, organisation retrieve and task activities fixes

---

backend/api/teams/resources.py
backend/api/users/resources.py
backend/models/postgis/project.py
backend/models/postgis/team.py
backend/models/postgis/user.py
backend/services/team_service.py

Teams managers and members assignment and retrieve query fixes.

Teams managers and members assignment and retrieve query fixed

---

backend/api/projects/actions.py
backend/api/projects/resources.py
backend/models/postgis/project.py
backend/services/project_admin_service.py

Project clone and transfer project ownership refactored.

Project clone and transfer project ownership refactored

---

backend/api/projects/teams.py
backend/models/dtos/project_dto.py
backend/models/postgis/project.py

Added root validator for project info dto to handle null initialization in attributes.

Added root validator for project info dto

---

frontend/src/locales/fr.json

Fixes a small typo in the FR translation

typo fixed in FR translation

---

backend/api/tasks/actions.py
backend/services/grid/split_service.py

Split task url and geom fixed.

Split task url and geom fixed

---

backend/api/comments/resources.py
backend/main.py
backend/services/messaging/chat_service.py
backend/services/users/authentication_service.py

Http exception handler for 401 errors in the app for token expiration handling.

Http exception handler in the app for token expiration handling

---

backend/models/postgis/application.py
backend/models/postgis/banner.py
backend/models/postgis/campaign.py
backend/models/postgis/interests.py
backend/models/postgis/licenses.py
backend/models/postgis/mapping_issues.py
backend/models/postgis/organisation.py
backend/models/postgis/partner.py
backend/models/postgis/priority_area.py
backend/models/postgis/task.py
backend/models/postgis/task_annotation.py
backend/models/postgis/team.py
backend/models/postgis/user.py
backend/services/messaging/chat_service.py

Update teams and files formatting.

fix: Update teams and formatting

---

backend/api/annotations/resources.py
backend/main.py
backend/services/users/authentication_service.py

Invalid token exception in TokenAuthBackend

fix: Invalid token exception in TokenAuthBackend

---

Dockerfile
docker-compose.yml

Python path for docker setup and mount the migrations to alembic script location path.

Add PYTHONPATH and bind mount for migrations

---

backend/api/projects/resources.py
backend/api/tasks/actions.py
backend/api/tasks/resources.py
backend/config.py
backend/cron.py
backend/main.py
backend/models/postgis/task.py
backend/services/project_service.py

* Asyncio cron job scheduler set up. 
* Auto unlock task refactored.
* Auto unlock task cron job. 
* Task geojson export.

* Asyncio cron job scheduler set up. * Auto unlock task refactored. * Auto unlock task cron job. * Task geojson export.

---

backend/services/validator_service.py

Remove atomic transaction from concurrent task validation.

Remove atomic transaction from concurrent task execution

---

backend/api/tasks/statistics.py
backend/models/dtos/stats_dto.py
backend/services/organisation_service.py
backend/services/project_search_service.py
backend/services/stats_service.py

Task statistics and filters refactored

Task statistics and filters refactored

---

backend/api/users/statistics.py
backend/models/dtos/user_dto.py
backend/services/users/user_service.py

User statistics refactored.

---

backend/cron.py

Cron job for auto unlock task refactored.

refactor: cron job for auto unlock task.

---

backend/services/users/user_service.py

User statistics query results casted to integer.

User statistics query results cast to int

---

backend/db.py

Removed sqlalchemy db configs.

Remove sqlalchemy db configs

---

README.md

2025 roadmap update

---

backend/services/project_search_service.py

Project to map and validate sorting zero division case handled.

project to map and validate sorting zero division case handled

---

frontend/src/components/projectDetail/tests/favorites.test.jsx

Fixes:
- Attempt to fix favorites test

fix(frontend/tests): favorites test

---

backend/api/issues/resources.py
backend/api/licenses/resources.py
backend/api/projects/actions.py
backend/api/users/actions.py
backend/services/users/authentication_service.py

Pm only resource dependency function and injection in the required functions.

pm only dependency function and injection in the required functions

---

frontend/src/components/projectEdit/permissionsBlock.js
frontend/src/components/projectEdit/teamSelect.js

- Fixes #6628
- Add `HOT Global Validators Team` by default for specific validation permissions
- Change teams API fetching to react-query

Add `HOT Global Validators Team` by default for Validation Permission restricted to Teams

---

frontend/package.json
frontend/src/components/projectEdit/permissionsBlock.jsx
frontend/src/components/projectEdit/teamSelect.jsx

- Merges latest develop changes
- Change the `start` script in `package.json` to start vite dev server

typescript-vite: fix,chore: merge latest develop changes, fix start command

---

backend/models/postgis/task.py
backend/services/interests_service.py
backend/services/license_service.py
docker-compose.yml

Interests and license deletion message response handled and cron service added to compose.

interests and license deletion message and cron service

---

backend/services/project_search_service.py

Project to validate filter fixed.

fix: project to validate filter

---

backend/services/users/user_service.py

User statistics mapping and validation time timestamp conversion.

fix: User statistics mapping and validation time timestamp conversion.

---

backend/api/projects/actions.py

Remove pm only dependency from intersecting tiles.

Remove pm only dependency from intersecting tiles.

---

backend/config.py
backend/main.py

TM_API_URL added to app config and application root path

TM_API_URL added to app config and application root path

---

backend/models/postgis/project.py

Set country info to handle wkb centroid.

set country info to handle wkb centroid

---

backend/api/users/statistics.py
backend/exceptions.py
backend/main.py

BaseException class extended from fastapi HTTPExeception class instead of werkzeug.exceptions.

BaseException class extended from fastapi HTTPExeception class

---

backend/services/messaging/message_service.py

Team managers query for bulk mentions fixed.

fix: bulk mentions team managers query

---

backend/models/dtos/project_dto.py
backend/services/users/user_service.py

Organisation made optional for project dto.

Organisation made optional for project dto

---

backend/services/project_search_service.py

Filter by only active team members in project action permission.

Filter by only active team members in project action permission

---

.circleci/config.yml
backend/api/teams/resources.py
backend/models/postgis/team.py
frontend/src/assets/styles/_colors.scss
frontend/src/components/partners/leaderboard.jsx
frontend/src/locales/en.json
frontend/src/locales/es.json
frontend/src/views/messages.ts
frontend/src/views/partnersStats.jsx
frontend/src/views/projectEdit.jsx
scripts/docker/Dockerfile.frontend
scripts/docker/Dockerfile.frontend_development

Merge and resolve conflicts with develop branch

Resolve merge conflicts with develop

---

.gitignore
backend/config.py
backend/cron_jobs.py
pdm.lock
pyproject.toml
tests/api/conftest.py
tests/api/test_hearbeat.py

Httpx and pytest added and lockfile regenerated.
Test cases init setup.
Cron Trigger in jobs changed to Interval Triggers.

httpx and pytest added and lockfile regenerated, test cases init setup

---

backend/config.py
backend/main.py
backend/models/dtos/project_dto.py
backend/models/dtos/settings_dto.py
backend/models/dtos/stats_dto.py

Sentry init handled from env.
Pydantic serialization warnings fixed.

Sentry init handled from env and pydantic serialization warnings fixed

---

backend/config.py

sentry variable config initialized with string instead of bool.

sentry variable config initialized with string

---

backend/services/project_search_service.py

pre-commit over-indent check failure fixed

pre-commit over-indent check failure fixed

---

backend/api/organisations/resources.py
backend/api/tasks/actions.py
backend/models/postgis/organisation.py
backend/services/messaging/template_service.py

* Organisation list order by name.
* Revert Validated task by user permission issue fixed.
* Org and teams in retrieve organisation by slug.

* Organisation list order by name.* Revert Validated task by user permission issue fixed. * Org and teams in retrieve organisation by slug.

---

backend/config.py
backend/services/organisation_service.py
docker-compose.yml
example.env

Update example env.
Add frontend to docker compose.
Sentry dns made optional in config.
Organisation stats query fixed.

Update example env, Add frontend to docker compose, Sentry dns made optional in config, organisation stats query fixed

---

frontend/src/components/projectDetail/header.js
frontend/src/components/projects/exploreProjectsTable.js

Handle crash issue when country field not present in the projects API

---

backend/services/stats_service.py

Update task stats project dict changed to record object.

Update task stats project dict changed to record object

---

example.env

Rename test database name in example env.

Test database in example env

---

tests/api/conftest.py

Removed str replace in test database url to handle cases where the test database name and user/password/host name is same.

String replace in test db url creation removed from test config

---

backend/api/system/general.py

Updates the release version from github release notes.

Post release version

---

backend/services/users/user_service.py

Advanced and intermediate changeset value from app config.

hotfix: Advanced and intermediate changeset value from app settings

---

Dockerfile
scripts/commands/update_user_level.py

Script to check the legitimacy of advanced user and demote to the actual level.
Add script to container.

script to check the legitimacy of advanced user

---

frontend/package.json
frontend/yarn.lock

- Closes #6744 
- Fixes #6792
This PR upgrades the iD editor to the latest version.
This PR also addresses the Mapillary issue mentioned above.

Upgrade iD editor version to latest (v2.33.0)

---

backend/services/project_search_service.py

Related to: #6836 #6828 
When draft project status filter was applied, the users could see the list of all the draft projects irrespective to their permission. Although the project couldn't be accessed and only be listed but the desired output is to see only those draft project which is managed by the user.

Draft project list filter by user permission

---

backend/api/organisations/resources.py
backend/api/projects/resources.py
backend/cron_jobs.py
backend/services/mapswipe_service.py
backend/services/recommendation_service.py

Better response and exception handling based on sentry logs.
Fixed project json download as file.

Better response and exception handling, fixed project json download as file.

---

scripts/aws/infra/production/non-purgeable/ec2/terragrunt.hcl
scripts/aws/infra/production/purgeable/common-ecs-env.hcl

Applies fixes to prod infra and adds more endpoints to CORS whitelist.

Add more endpoints to CORS list

---

frontend/src/components/projectCard/projectCard.js

Reverts hotosm/tasking-manager#6683 - accidentally merged the wrong one. @royallsilwallz and [@ashi](https://github.com/Ashik-AD)  fix is in another PR https://github.com/hotosm/tasking-manager/pull/6863

Revert "Fix: Render markdown correctly for short descriptions"

---

frontend/src/components/taskSelection/index.js

Fix tab change not working when search filter applied issue

---

backend/services/validator_service.py

Fixes #6870 
Single notification to users when validating multiple task by locking the message sent to with the multiple coroutines running in parallel.

Single notification to the users when validating multiple tasks at once

---

README.md

roadmap file update

---

frontend/package.json
frontend/yarn.lock

Upgrade iD editor version to latest (v2.34.0)

---

frontend/src/utils/tests/openEditor.test.js

This PR resolves the issue that was causing the test cases to fail on the CI.
The reason was static `API_URL` used in a test case, which caused it to only pass on `http://127.0.0.1:3000`
**Changes**
- Make static `API_URL` dynamic in `openEditor.test.js`
- Decode the encoded URIs to compare the URLs

Fix test cases failure on CI

---

frontend/src/components/header/tests/index.test.js
frontend/src/components/localeSelect.js
frontend/src/network/tests/mockData/header.js
frontend/src/network/tests/server-handlers.js

- Resolves #6908 
This PR resolves issue related to Arabic language option not being present on user settings page while it was available on project setting.
**Changes**
- The issue  was caused due to the usage of static json in the frontend
- The solution was to use supported language json fetched from the backend

Fix language options missing on settings page issue

---

backend/services/project_search_service.py
docker-compose.yml

Project to map and validate to only include the published projects.
Dockerfile path and build stage for migration and cron service.

Project to map and validate to only include the published projects and specify dockerfile path and build stage for migration and cron service

---

tests/api/conftest.py
tests/api/integration/api/system/test_banner.py
tests/api/integration/api/system/test_general.py
tests/api/integration/api/system/test_statistics.py
tests/api/unit/services/test_project_service.py

Test configuration and system integration test cases refactored.
Tried to isolate the test environment from accidental connections to production environment or settings.

Test configuration updated for test isolation and system integration test cases refactored

---

frontend/src/components/badges/index.js
frontend/src/components/projectDetail/index.js
frontend/src/components/projectEdit/permissionsForm.js
frontend/src/components/tests/rapidEditor.test.js
frontend/src/components/user/list.js
frontend/src/components/userDetail/userBadges.js
frontend/src/setupTests.js

Fixes eslint issues related to super mapper
The only delicate thing is the removal of a block of code (completely not related to the PR) that shouldn't be necessary since we are using node 22.

eslint fixes for super mapper feature

---

backend/services/grid/split_service.py

Project id fetched from dto instead of object.

project id from taskdto instead of task object

---

.github/workflows/pr_test_backend.yml
backend/cron_jobs.py

Run pre-commit on all files

---

backend/services/users/user_service.py
tests/api/unit/services/users/test_user_service.py

* badges are assigned to users even if they are at the highest level
* notifications about new level achieved are restored
* tests of the above

badges not assigned

---

backend/models/postgis/project.py

set default validation permission to any with intermediate level

---

frontend/src/components/tests/rapidEditor.test.js
frontend/src/components/user/list.js
frontend/src/components/user/tests/list.test.js
frontend/src/components/user/tests/topBar.test.js
frontend/src/components/userDetail/tests/headerProfile.test.js
frontend/src/hooks/tests/UseContributorStats.test.js
frontend/src/network/tests/mockData/userList.js
frontend/src/network/tests/server-handlers.js
frontend/src/views/tests/users.test.js

Updates the test cases to align with the recent super-mapper changes:
- Add mock data for user levels
- Mock API responses for consistent testing
- Add data-testid for easier element selection
- Update, remove, or add test cases as needed to reflect the changes

Adapt frontend test cases as per supper mapper changes

---

frontend/src/views/management.js

- #6906
This PR fixes an issue where users could access unauthorized pages directly via URL. Now, when such an attempt is made, the user is shown the "Unauthorized" page.

prevent accessing unauthorized pages through url
