client/app/admin/create-project/create-project.controller.js, client/app/admin/create-project/create-project.html, client/app/components/add-layer/add-layer.directive.js, client/app/components/add-layer/add-layer.html, client/app/services/draw.service.js, client/app/services/geospatial.service.js, client/app/services/map.service.js, client/app/services/project.service.js, client/assets/styles/sass/_admin.scss, client/assets/styles/sass/_map.scss, client/index.html, tests/client/unit/app/components/test.add-layer.directive.js
- Added ability to add 'temporary' layer on the fly during project creation. At the moment it only supports XYZ layers such as MapBox. To test, use this URL: https://api.mapbox.com/v4/openstreetmap.map-inh7ifmo/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJhNVlHd29ZIn0.ti6wATGDWOmCnCYen-Ip7Q
The layer is then also added to the layer switcher and can be switched off.
- Refactor of conversion between GeoJSON and ol features. A new geospatial service handles these conversions.
=> refactor, new geospatial service, ability to add temp layer

client/app/components/add-layer/add-layer.directive.js, client/app/components/add-layer/add-layer.html, client/app/services/map.service.js, client/taskingmanager.config.json
Add WMS support for adding layers on the fly. Also for adding them as default layers for the layer switcher, I've added a WMS in the config file for DEV for demo purposes.
To test:
WMS url: http://sedac.ciesin.columbia.edu/geoserver/wms
Layer name: gpw-v3:gpw-v3-population-density-future-estimates_2005
=> add WMS support adding layers on the fly

server/api/project_admin_api.py, server/models/postgis/project.py, server/services/project_admin_service.py, tests/server/unit/services/test_mapping_service.py, tests/server/unit/services/test_project_admin_service.py
System will enforce that all fields of project info for the default locale are complete prior to publication.
=> Validate that we have all fields on default locale info

server/api/authentication_apis.py, server/services/authentication_service.py, tests/server/unit/services/test_authentication_service.py
Add redirect_to param on authenticate to allow the app to redirect user back to the page they were at when they logged in.
=> Add redirect_to to query string on auth

client/app/login/login.controller.js, client/app/profile/profile.controller.js, client/app/project/project.controller.js, client/app/project/project.html, client/app/services/auth.service.js, client/app/services/task.service.js
- Show error when user needs to login when locking for mapping/validating
- Overpass Turbo link (it shows a no data available message in Overpass which is the same when opening a task in Overpass in TM2 when no edits have been made). Need to test this fully once we can launch the editors.
- Redirect parameter on logging in which brings the user back to where they came from when logging in
- show history user names
- shows who has locked the task (and 'you' if it was the logged in user). Users can map/validate their own locked task (API still needs to deal with this, so shows error at the moment)
=> Auth mappers validators part2

server/models/dtos/validator_dto.py, server/models/postgis/task.py
If user locks/unlocks a task multiple times API was counting each action.  Code now only counts distinct task ids.
=> Fix bug double counting mapped tasks

client/app/admin/dashboard/dashboard.controller.js, client/app/admin/dashboard/dashboard.html, client/app/project/project-dashboard.controller.js, client/app/project/project-dashboard.html, client/app/services/project.service.js, client/app/services/projectMap.service.js, client/app/services/style.service.js, client/app/taskingmanager.app.js, client/assets/styles/sass/_dashboard.scss, client/assets/styles/sass/_structure.scss, client/index.html, tests/client/unit/app/project/test.project-dashboard.controller.js
Project dashboard - work in progress
- project**s** dashboard for admins (/admin/dashboard) where users can see the projects that they have created. Data comes from the API. The lastUpdated date is hardcoded in the API still.
- individual project dashboard with stats on the project (project/528/dashboard). Data is mocked except the comments.  We could potentially use this page to display what is in the activity tab now? And link to it from the project page so any user can see this page? Just an idea.
=> Project dashboard admin

server/models/postgis/task.py, server/services/mapping_service.py, server/services/stats_service.py, server/services/validator_service.py, tests/server/unit/services/test_stats_service.py
Counters were not being correctly decremented when a task was invalidated.  This has been resolved.
=> Bugfix - Correct counters when invalidating

README.md, server/config.py
This lets people create and use their own oauth key.
By the way, since I don't have the `consumer_secret` for the currently provided key, I'm not able to login in my locally installed instance. Did I miss something?
=> Get consumer key from env variables

server/config.py
When using DevConfig for the Flask server, OAuth does not like a `localhost` callback. Changing the app base url to `127.0.0.1` fixes this problem. 
I've also added a config for those running only IPv6 locally and cannot use `127.0.0.1`, but was not personally able to verify that works properly.
=> localhost to numeric

client/app/contribute/contribute.html
@bgirardot the legend on the contribute page did not translate well and was generating Angular errors. I have reverted to non translatable strings for now. We'll probably have the same issue on the project page legend. I'll have a look at what is causing it when I get a moment.
=> revert legend translation

server/models/postgis/project.py, server/services/project_admin_service.py, tests/server/helpers/test_helpers.py
This should resolve issue #410 where the projectId was missing from the default changeset comment.
=> Bugfix for default comment

server/models/postgis/task.py
This should fix error #668 when attempting to stop mapping.
@bgirardot note that any tasks you previously attempted to stop mapping on will now contain a data error that will need to be cleaned up with a database fix.  To fix these you will need to run the following Update on the DB
update task_history
set action_text = NULL
where id in (select th.id
from tasks t,
task_history th
where t.id = th.task_id
and t.project_id = th.project_id
and t.locked_by = th.user_id
and t.locked_by is not null
and th.action_text is not null
and t.mapped_by is null
and th.action = 'LOCKED_FOR_MAPPING');
=> Incorrect null check, should check for empty list. 

client/app/profile/profile.html
This allows uses to see the badges they earn in a link.
=> include missing maps profile link

client/app/components/language/language-switch.html, client/app/contribute/contribute.html, client/app/project/project.html, client/assets/styles/sass/_structure.scss, client/index.html
Fixes #696
Changes the way the language switcher displays :
- no label "language" since it is in my opinion not required,
- style and behavior consistent with other elements in nav bar.
Show a pointer on hover on tab items.
=> Fix cursor pointer on some elements

client/app/admin/edit-project/edit-project.html
Fixes #729
This issue may have happened elsewhere when the big 164f58cb commit was merged.
Note: it's not possible to change an `<a href="...">`to a `<button href="...">`.
=> Fix Go to project link behavior

circle.yml, client/app/about/faq.html, client/app/about/what-is-new.html, client/app/taskingmanager.app.js, client/index.html
* Adds a FAQ page at `/faq`
* Rearranges the text on the what is new page
* Proposing a cosmetic change to the What is New Page --- move from `/whatisnew` to `/what-is-new`. It's a bit easier to read.
=> add faq page, update what is new page

client/assets/styles/sass/_contribute.scss
Adds `overflow: hidden` to a section of the individual contribute panels. This makes the panel longer. 
Fix makes the panel longer. May want to address this in a different way. Like limit title length.
=> fix text overflow for long titles

manage.py, server/models/postgis/user.py, server/services/users/user_service.py
Helper for #706   To allow us to set the mapper level for all users, I've added a wee helper that will initialise the level for all users in the db.  You will need to have an environment that can be connected to the live DB to run it.
Once updated the levels are recalculated everytime a users submits mapping so it should be fine.  You can run it from the solution as follows:
python manage.py refresh_levels
It will probably take an hour to run, but it will print out progress as it goes.  I seem to remember I had a clever hack to do this really fast previously, but I can't remember it.
@pgiraud @david-hotosm @bgirardot let me know if you have any questions
=> Refresh mapper level helper

server/__init__.py, server/api/project_apis.py, server/services/project_service.py
First half of #789: provide an API endpoint to access only the area of interest of a project as a JSON file.
Specific url endpoint is `/api/v1/project/#####/aoi`.
@bgirardot this doesn't completely match the url from TM2, but mostly follows naming scheme of other API endpoints. Please comment on yes/no for that.
Default behavior. Accessing the url as listed above will prompt download for a file, or if accessed via API GUI, a link to download the file will show up. File downloaded is named `project.json`:
By specifying ?as_file=false, the user can load the data in browser:
=> Add project AOI json endpoint

client/app/services/map.service.js, client/taskingmanager.config.json
Add bing imagery as a configureable layer option, enabled by default to appear
in the layer switcher
fixes: https://github.com/hotosm/tasking-manager/issues/793
Looks like this:
=> Add bing imagery to layer switcher

server/models/postgis/user.py, server/services/users/authentication_service.py, server/services/users/user_service.py, tests/server/helpers/test_files/osm_user_details_changed_name.xml, tests/server/helpers/test_helpers.py, tests/server/integration/services/users/test_authentication_service.py
Fixes #832 and other issues in Slack chat associated with users changing their OSM username then attempting to log into TM3 again.
I tested this manually and it worked. I'll write an automated test for this soon, but please feel free to review.
=> Fix username updates

server/models/postgis/project.py
It makes more sense to exclude the tasks locked for validation. Even more when we take into account that a validator can lock several tasks at a time.
=> Count only tasks locked for mapping

manage.py
Fixes #360. When using the `manage.py` script, we first check if the key environmental variables are set that will be necessary for development work.
I phrase it specifically that way because I am neglecting the three email/SMTP ones which are not required to work on backend stuff.
=> Check for env variables; fixes #360

client/app/contribute/contribute.html, client/app/project/project.html, client/assets/styles/sass/_contribute.scss, client/taskingmanager.config.json, server/models/dtos/project_dto.py, server/models/postgis/project.py, server/services/project_search_service.py
PR to show active mappers on contribute and project page to address #627  Couple of things to note:
* Counts use locked tasks as a proxy for active users (thanks @pgiraud for the awesome idea)
* Counts are cached for 30 seconds to reduce DB load, could reduce time a bit if needed
* @bgirardot you'll want to review the text I've used on the HTML and make sure it's translated as needed
* I'm not really a designer so someone might want to look at how counts are displayed, but works for now :)
Give me a shout if there's any questions
Thanks
Iain
=> Displays active mappers on contribute and mapping page

client/app/services/map.service.js
This avoids "mixed content" warnings.
=> Use protocol naive URL for map tiles

server/models/postgis/project.py
Rather than using the round function, int will floor the percent mapped or validated down to the nearest whole number--only 100% will happen when 100% are done. 99.9% will go to 99. 
Fixes #909, #829. Possibly the solution to #868 as well.
=> Round project percent done/validated down

server/models/dtos/project_dto.py
Currently, the hash for the project search that allows it to be cached does not include the recently introduced `is_project_manager` variable. This means some searches return draft and archived projects even for non-project managers.
The following PR should alleviate that by caching the project manager status in that hash.
=> Include pm status in search cache

client/app/admin/create-project/create-project.controller.js
Someone may try to upload a file with an uppercase extension, such as `.ZIP` or `.geoJSON`. This will make sure the upload doesn't fail simply because of that.
=> Allow uppercase project file imports

client/index.html
This PR replaces a deprecated css style to close the mobile banner with a style currently present in the code base.
Fixes #933 
Fixes #820
=> Fix mobile banner closer

tests/server/integration/models/postgis/test_project.py, tests/server/integration/services/messaging/test_smtp_service.py
Hi @ethan-nelson setup the project at home and saw the broken test issue for myself.  Looks like I left a bit of debug code in the test (oops) 😖 
I also made it possible to skip the SMTP integration tests, which I'm guessing most people won't have setup at home
Will at least make it easier to increase coverage for #951
=> Fix broken tests on empty db

LICENSE.txt
This adds a BSD-2 clause license file for the project to match the previous BSD-2 clause license that was on TM v2: https://github.com/hotosm/osm-tasking-manager2/blob/master/LICENSE.txt. 
From the discussion in #950, we had proposed to keep the same license and it seems that it is still compatible with all the dependencies. 
Fix #950
=> add BSD-2 license

client/app/profile/profile.html, server/models/postgis/statuses.py, server/services/project_service.py, server/services/users/user_service.py, tests/server/unit/services/test_project_service.py
In some cases, it may be necessary to limit the ability for a user to interact with the tasking manager. This adds that functionality.
=> Provide access limitation capability

client/index.html
This PR adds Piwik tracking code to enable tracking visit stats across the site. Fixes #786. Open to ideas for how we manage more custom HOT deployment code, but sticking this at the bottom of the main index.html for now.
=> add piwik tracking code, fix #786

client/app/home/home.html
This rearranges and adds text and a link to the HOT #MapTheDifference fundraising campaign. This is the first solution idea for #990. 
This may suffice as a good way going forward for custom text on the front page, but it isn't very eye-catching and blends in a bit. Open to other recommendations for how we can achieve the goal of highlight the text and link to the campaign.
=> update stories section to include donate

server/api/mapping_apis.py, server/models/postgis/task.py, server/services/mapping_service.py, tests/server/integration/services/test_mapping_service.py
The API endpoint that allows task downloads in GPX or OSM XML files currently requires task numbers to be specified. Some are interested in download all of the tasks in this form, so this PR allows for that.
Also these two endpoints did not have the best error handling in the event of a project or task specified not existing, so I've added a few checks for that.
For some reason I am unable to get tests running locally anymore, but I will try to add a test if I can get that fixed soon.
=> Update task GPX/XML file APIS to allow retrieval of all tasks

client/app/home/home.html, client/assets/styles/sass/_mobile.scss, client/index.html
Based on some feedback and request from Fundraising WG, we want to help promote linking to the end of the year campaign where it is visible and accessible. Previous implementation was too buried. So this is a new proposal for leveraging the banner used for Mapswipe temporarily. This has the same functionality and so it can be closed. 
Includes: 
* reverting back to the Red Cross story for front page 
* banner always shows up - desktop and mobile with the fundraising message and link
* adjusts the dark red to a lighter red
=> Change fundraising campaign to a banner

server/models/postgis/statuses.py, server/services/project_service.py
Originally, anyone was able to validate or invalidate tasks on a project whether it was in draft, archive, or published mode. This restricts validation in archived or draft statuses to only project managers.
Fixes #919. Part of #866 is also resolved with this (only the validating).
=> Disallow validation on projects in draft or archive status for mappers

server/__init__.py, server/api/mapping_apis.py, server/models/postgis/project.py, server/services/project_service.py
The API endpoint `/api/v1/{project_id}` currently returns a geojson stream that contains both project metadata and tasks with geometry and metadata. While #938 allows for one to download that information in a json format, it is still not a valid geojson file that can be opened in JOSM.
This PR provides that functionality. The hope is this endpoint can be used to reproduce the `Export` button as seen in TM2 for PMs.
=> Add api for geojson of all task features

server/services/validator_service.py
@smit1678 or @ethan-nelson If either one of you could quickly review this, I have tested it locally and merge it in. Pretty minor but needed clarification of an error message related to validation that currently says mapping.
Will affect the translation strings.
=> Changes validation error msg to say validation, not mapping

client/index.html
Updates the banner text to adjust to the last extended deadline of January 7. I cut some text to keep the banner at 2 lines on my laptop screen.
=> update banner text to january 7 deadline

server/config.py
Flask's [default](http://flask.pocoo.org/docs/0.12/api/#flask.Flask.send_file_max_age_default) is to set a 12 hour file cache header. This PR sets it to 0 so that users can immediately access new information from API file downloads.
=> Prevent file caching

client/assets/styles/sass/_mobile.scss, client/index.html
This PR adds back the original Mapswipe message on the banner as well as adds the restriction to only show the banner on mobile views. Reason for this change is that the end of the year campaign has been wrapped up. 
WIP - To be confirmed with Fundraising working group.
=> [WIP] update banner to revert to Mapswipe message

client/app/services/search.service.js, server/api/project_apis.py
The end goal of this PR and prior (#858) is to allow project managers to see archived and draft projects in searching. We _don't_ want regular users to see draft and archived projects. This could normally be achieved by just adding `@tm.pm_only(False)` and `@token_auth.login_required` wrappers around the call, except we **also** want anonymous users to search for projects.
Unfortunately, the current state does not support that. The `tm.authenticated_user_id` variable is not set on a search call because
1) no authorization header is supplied and
2) there is no authentication token wrapper to define `tm.authenticated_user_id` based on the current user.
So we want a function that is (pseudo) `@token_auth.refresh_credentials` to solve these two items.
(1) is solved by adding the …
=> Add authentication on search

tests/server/integration/models/postgis/test_project.py, tests/server/integration/models/postgis/test_user.py, tests/server/integration/services/grid/test_split_service.py, tests/server/integration/services/messaging/test_messaging_service.py, tests/server/integration/services/messaging/test_smtp_service.py, tests/server/integration/services/test_license_service.py, tests/server/integration/services/test_mapping_service.py, tests/server/integration/services/test_project_search_service.py, tests/server/integration/services/test_validation_service.py, tests/server/integration/services/users/test_authentication_service.py, tests/server/integration/services/users/test_user_service.py
See https://github.com/hotosm/tasking-manager/pull/1013#issuecomment-356638724 for background.
Since we are relying only on CircleCI now, we need to rely on another environmental variable to flag whether it's a CI build or not. (As an aside, developers should be running tests locally as well to ensure tests that require database access pass.)
The behavior that this fixes only surfaces on PRs from branches of forks because the CircleCI secure variables (including `SHIPPABLE=true` that we manually set) are not passed into those for security reasons. But, `CI` and `CIRCLECI` are set to `true` in the builds so we can use that instead. And we settled on `CI` to generalize it in case of future CI platform changes or for users using other platforms.
=> Update env var CI flag

client/app/contribute/contribute.controller.js, client/app/contribute/contribute.html, server/api/project_apis.py, server/models/dtos/project_dto.py, server/services/project_search_service.py
#858 added the initial ability for searches to include draft and archived projects in results for authenticated project managers.
#922 clarified this functionality by removing a reliance on a possibly out-of-date authentication variable in the API.
The next step as requested is to expose a filter for project managers that will include/exclude draft and/or archived projects in the results. This PR accomplishes that.
Filters turned off
Filters turned on:
=> Add ability to filter for archived or draft projects

tests/server/integration/services/test_stats_service.py
One more `SHIPPABLE` to `CI` transition in the tests since this was a recent merge. See #1020 for more info.
=> Change CI var in stats test

server/services/project_service.py, tests/server/unit/services/test_project_service.py
This provides project managers the ability to mark tiles as mapped or unmapped for projects that are either draft or archived. 
Fixes part of #866. This is a sibling to the #920 PR.
=> Allow project managers to map archived projects

server/config.py
Currently, the url that directs users to the Swagger API from `/api-docs` is hard-coded in the `server/config.py` file. This can present a problem if the app url is changed to another domain as users may be directed to the wrong Swagger API if the second url is not changed as well.
To mitigate this, the PR removes the hard-coded host and uses the `APP_BASE_URL` variable that is already used to define the first part of the url.
=> Remove hard-coded swagger url

manage.py
New and improved!
This time we ignore exceptions from the `init_counters` call and give a warning to the user if it didn't initialize.
=> Handle homepage stats error in manage.py

server/services/messaging/message_service.py
This hopefully fixes #961 - my suspicion is we're hitting AWS Rate Limits which are set at 14 emails per second.  So a a large project can easily have 50+ contributors - so when we can the AWS API to send all 50, Amazon will time us out.
This PR add a 0.5 seconds sleep after every 5 emails.  (Reduced number in case other emails being sent at same time)
=> Add fix for AWS rate limiting when sending messages to all

server/services/validator_service.py, tests/server/integration/services/test_validation_service.py
Made a feature branch for https://github.com/hotosm/tasking-manager/pull/1055
fixes issue #986 
----
According to the reported issue, when a project admin 'A' clicked "Validate all tasks", the application marked tasks as having been mapped by 'A' regardless of whether or not he/she actually mapped them.
The flow of this operation is as follows:
- The frontend sends a `POST` request to `/admin/project/<int:project_id>/validate-all`
- The backend calls `ValidatorService.validate_all_tasks` passing the project ID and the ID of the authenticated user (in this case the project admin, NOT the mapper). This ID is necessary to record the user performing the current action (validation).
- However, `validate_all_tasks` also sets the `mapped_by` value of each task to this user ID.
Removing the line …
=> Fix validate all tasks button causing contributors list to be lost

server/api/messaging/message_apis.py, server/services/messaging/message_service.py
This hopefully fixes #961 once and for all.
Testing demonstrated that message all is taking over 1 minute to run, our theory is that the AWS load balancer is killing the request at the 1 minute mark which means a lot of contributors are not getting messaged.
This PR now launches the message_all function on a background thread.  This will mean that when you message all contributors, the UI will report that messages have been sent instantly.  However, a background thread on the server will be running for circa 2 mins sending all the emails.
I've tested locally and seems to be working fine for me.
cc @bgirardot
=> Thread message-all function

Dockerfile
This pins to the `jessie` (Debian 8.10) variant of the `python:3.6` Docker image and removes the explicit installation of a `libgeos-dev` dependency for compatibility across versions.
Pinning to `jessie` will prevent other unexpected dependency changes.
=> Debian dependency fixes

circle.yml
This wasn't breaking CircleCI yet (`python:3.6` is probably cached since it only changed recently), but it will soon.
=> Match circle dependencies to Dockerfile

.ebextensions/aws.config, Dockerfile, circle.yml, migrations/alembic.ini
This PR creates a script in EB that will run the python db upgrade after deployment. Please note that this happens every time an instance is deployed which is not ideal but for the most part will do nothing. 
@smit1678 @bgirardot @ethan-nelson this is a precursor to being able to re-merge the dev changes (new relic, etc) into `master`.
=> EB db upgrade

client/app/profile/profile.html
Current link to "Missing Maps Badges" takes to invalid URL. This commit will fix the link
=> fix missing maps badges link in User profile section

server/models/postgis/project.py, server/services/project_search_service.py, server/services/validator_service.py
Currently, bad imagery is excluded from mapped percentages but is added to validated percentages in the UI. This is opposite of what we want because bad imagery tasks _can_ be validated.
A task that is "ready to be mapped" can be marked mapped or bad imagery; these two choices are on an equivalent level in terms of task completion but are disjointed. (These two choices are not collectively exhaustive, though, as a state can be re-marked as ready to be mapped.) We therefore want the percent mapped to include both mapped and bad imagery counts.
Tasks either in a mapped or bad imagery state can be validated, after which they share the same status. Thus, we want the validated percentage to only count validated tasks over all tasks.
The statistics calculated and returned to the UI have been …
=> Include bad imagery in mapped, validation stat calculations

server/services/stats_service.py
An unlocked task has the `locked_by` column value set to `None`, so this should be taken care of and all such entries should be ignored while calculating the online mapper count.
Noticed this on my development instance where the number of registered users was 1, but the online mapper count was showing 2.
=> Fix online mappers count

server/services/project_search_service.py
Fixes #1131 
The way the search query is structured, it finds projects either with information in English or information in another locale (in this case, English is the fall back language). Unfortunately this generates duplicate results when there is indeed more than one language supplied in project information. Here, I use a distinct clause to ensure that only one project per id is supplied. Distinct with only the id (and not including priority) would not work because the distinct clause must match the order clause.
=> Remove duplicates from results

server/models/dtos/user_dto.py, server/models/postgis/user.py
Currently the `/api/user` endpoint returns a DTO about a user that includes the counts of tasks validated and tasks mapped, but not tasks invalidated. This information is already in the database and is desired by data consumers, so this PR adds the tasks invalidated count to the base user DTO and also when the DTO is populated.
=> Add invalidated count to user DTO/API call

client/app/profile/profile.controller.js, client/app/profile/profile.html, client/app/services/user.service.js, server/__init__.py, server/api/stats_api.py, server/models/dtos/user_dto.py, server/services/users/user_service.py
=> Add time spent mapping on user profile

client/app/services/editor.service.js
Latest iD release doesn't load GPX files without an extension, so we add a fake one to the URL for now.
=> Spoof task outline gpx file extension for iD

client/assets/styles/sass/_helpers.scss
Add style for xmark controls, such as the control to dismiss the new-message notification and the control to remove users from a private project, to ensure they are displayed (as hot-design-system styles are no longer pulled in).
=> Show missing xmark (close, delete) controls.

client/app/admin/edit-project/edit-project.controller.js, client/app/admin/edit-project/edit-project.html, client/app/services/project.service.js, server/__init__.py, server/api/project_admin_api.py, server/models/postgis/task.py, server/services/project_admin_service.py, tests/server/unit/models/postgis/test_task.py, tests/server/unit/services/test_project_admin_service.py
* Add API endpoint for resetting all tasks in a project back to ready status while preserving task history
* Add comment to each task indicating it was reset.
* Add action to Edit Project page for project managers to reset all tasks
=> Option to reset project tasks, preserving history.

client/assets/styles/sass/_base.scss
Rather than having to change the colors of all sections,
have it only aimed for markdown-to-html directive.
So this would also allow it not to override other elements with
the same structure or classes.
This initial addition will set code to red.
Resolves #693
=> Create new common css entry for markdown-to-html

client/app/components/project-chat/project-chat.html, client/app/project/project-dashboard.html, client/app/project/project.html, client/assets/styles/sass/_status.scss, client/assets/styles/sass/_tables.scss, client/assets/styles/sass/taskingmanager.scss
* Change display of task history to a table structure, grouping together consecutive history entries from the same user with visual dividers between groups
* Show icons or color-coded status markers on entries based on status to make the history easier to scan
* Use table structure for Last Activity section of project Activity and Stats page, including color-coded status markers for entries
* Support rendering of Markdown in comments
=> Enhance readability of task history

client/app/project/comment-box.html, client/app/project/project.controller.js, client/app/project/project.html, client/app/services/task.service.js, server/__init__.py, server/api/mapping_apis.py, server/models/dtos/mapping_dto.py, server/services/mapping_service.py
* Add a comment box to tasks that is always present and can be used to comment on a task without first locking it for mapping or validation
* Extract comment box markup into a comment-box.html template to reduce duplication of markup
* Add new server API endpoint for adding a stand-alone comment to a task
=> Allow commenting on task without locking it

server/api/users/authentication_apis.py
From #1031:
> After encountering this a few times, I think I have figured it out. Scenario:
> 
> 1) Someone has previously logged in but their token is expired
> 2) They are presented with the log in or return screen (https://tasks.hotosm.org/login)
> 3) Though there is a login button in the body of the page, they click login at the top right
> 4) The login process is started and they log in as normal. However, the login button on the top right of the screen set the return url once logged in to https://tasks.hotosm.org/login since that is where they originated. 
This PR does not add the redirect parameter to the login process if `login` is part of the supplied redirect url. Instead, once the user logs in successfully, they will be redirected to the home page.
Fixes #1031
=> Prevent user getting stuck in login loop

requirements.txt
There is a security vulnerability in Flask versions < 0.12.3: https://nvd.nist.gov/vuln/detail/CVE-2018-1000656
Since it is a minor version change, hopefully nothing breaks, but let's check all the same.
=> Update flask version to 0.12.3

requirements.txt
Okay, apparently pip install failed when I updated and I didn't look closely enough. Adding that to my review checklist.
After 0.12.3 was correctly updated on my local machine, I confirmed that the same CircleCI error came up. Upgrading to 0.12.4 then fixed it. Sorry about that @dakotabenjamin !
=> Update Flask to 0.12.4

client/app/project/project.html, client/assets/styles/sass/_base.scss
From #1256 - Using SVG as a background img, icon isn't part of the DOM and doesn't let any property manipulation. So adding svg content to html file directly with a comment on the source.
=> Interactive SVG icons for button action text

server/services/mapping_service.py
Re #1266 switching back getting the size of a task query using the object function count instead of len. This is an undo to changes at https://github.com/hotosm/tasking-manager/pull/1211/files#diff-4864ec93a020afee0531607d8a0e7fa4
=> Bugfix for gpx generation error

server/services/mapping_service.py
When applying the fix in #1267, I changed `count` to `len` in an incorrect line. This PR fixes that by reverting the one wrong change and applying a correct one instead. With these changes, the file should be the same as e.g. https://github.com/hotosm/tasking-manager/blob/0ee74c637a61e7e874e2b087a24028a86f04163b/server/services/mapping_service.py
This needs some further investigation in the future as there have been at least two other instances of (presumably) len working on someone else's machine but not mine or the deployment in the context of the two that have been reverted between this PR and #1267.
=> Further bugfix for #1273

client/app/contribute/contribute.controller.js
When clicking on a new page in the search results, the screen position currently remains the same. This PR brings users back to the top of the page after loading a new page of results. 
This was carved out of the #1154 original PR.
=> Jump to top on search page switch

client/app/admin/create-project/create-project.controller.js, client/app/admin/create-project/create-project.html, client/index.html, client/package.json
Related to #1224 
Using https://github.com/tyrasd/osmtogeojson for converting osm to geojson
Translations for 'Import a GeoJSON, KML, or zipped SHP file.' were not changed. It can be done separately, if this solution is accepted.
=> Added support for importing osm files

client/assets/styles/sass/_map.scss
Fixes #699 
As map (class .map-container) and overview map (class .ol-overviewmap-map) both contain .ol-viewport it needs to be specified that only for map it should have min-height: 700px
=> Specify parent for ol-viewport style so overview map is not stretched. Fixes #699

client/assets/styles/sass/_map.scss
Fixes #843
Restrict max height of map.
If in some situation map must be larger, please let me know and I will try to find better solution.
=> Prevent map from being elongated. Fixes #843

CODE_OF_CONDUCT.md
We mention the Code of Conduct in the [contributing guidelines](https://github.com/hotosm/tasking-manager/blob/develop/CONTRIBUTING.md), but GitHub suggests in their [recommended community standards](https://opensource.guide/) to add a file with that information. This PR adds the full HOT CoC and complaint handling process in its own file.
=> Include HOT Code of Conduct file

server/models/dtos/stats_dto.py, server/services/stats_service.py
This PR focuses on the list of stats proposed in #1147 for the homepage section.
> Homepage
> - [x] Mappers online
> - [x] Tasks mapped
> - [ ] Tasks validated
> - [x] Total mappers
> - [ ] Total number of users who validate
> - [ ] Total area mapped and validated
> - [ ] Average task completion time
> - [ ] Number of projects by organization
> - [ ] Enable querying by date
- Added tasks validated
- Added total number of users who validate
- Added number of projects by organization
=> Add more homepage stats

server/models/dtos/user_dto.py, server/models/postgis/user.py
Hi folks
Thought I'd try and help out for Hacktoberfest 😄 
This PR should fix issue #792 The original query was somewhat naive and expected at least 1 mapped contribution on each project.  So in cases were users were only validating these counts were missed.
The fixed query looks much more complex, but essentially we're just joining the results from all mapping contributions for a user and all validation contributions.
My local testing showed the query to be performant on large datasets, and fixes cases where I only validated tasks
=> Fixes #792 where validation and mapping counts incorrect on profile

client/app/project/project.controller.js, server/api/project_apis.py, server/config.py, server/models/dtos/mapping_dto.py, server/models/postgis/task.py, server/models/postgis/utils.py
* Add `TASK_AUTOUNLOCK_AFTER` configuration setting to server that
allows task auto-unlock delay to be configured (defaults to 2 hours,
preserving prior behavior)
* Include configured delay in task data sent to front-end
* Update front-end task timer to make use of delay duration provided by
server instead of using hard-coded 2 hours
=> Make task auto-unlock duration configurable

client/app/about/about.html, client/app/about/faq.html
UPDATED TO ONLY INCLUDE RELEVANT COMMITS:
Fixes some spacing issues noted in #1292 
cc @smit1678 @ethan-nelson 
Once approved and merged, we can finish that release.
=> Add missing spaces to About and FAQ pages

client/app/project/project.controller.js, client/app/project/project.html, client/assets/styles/sass/_project.scss, client/taskingmanager.config.json
* Add new control for users in expert mode to each history entry in task
history table for viewing an augmented diff between two entries or attic
query data for a single entry
* Selecting two separate entries will show an augmented diff of the
changes between those entries in Achavi in a new browser tab
* Selecting the same entry twice will perform an attic query and open
the data in either JOSM (if the user has selected it as their editor) or
Overpass Turbo in a new browser tab
* Add new `atticQueryOffsetMinutes` config setting for adjusting history
entry timestamps for the purpose of querying attic data to ensure that
data has had time to become available (defaults to 10 minutes)
* Reorganize some of the projectController bbox code into separate
methods to facilitate easier reuse
=> Add expert augmented diff and attic query controls

devops/ci/circleci_deploy.sh
The new demo/testing environment is called `taskingmanager-test`. We must update this in order for CircleCI to deploy the `tm4ml` branch to tasks-test.hotosm.org
=> Make the demo branch push to the correct EB env

client/app/project/project.controller.js, client/app/project/project.html
As a follow up to the [configurable task unlock time changes](https://github.com/hotosm/tasking-manager/pull/1274), raised a point to [format time display](https://github.com/hotosm/tasking-manager/issues/1291). This PR fixes the same. Attaching screenshots:
cc @nrotstan @ethan-nelson
=> #1291 Format time display

client/index.html
Let's get this one in for 3.1.1 please. We updated Matomo to account for individual subdomains (tasks., etc) so the site id changed here.
=> Change matomo site id to TM site

client/assets/styles/sass/_base.scss
A lot of buttons like those below didn't have the `cursor:pointer` css property
=> add "cursor: pointer" to buttons and remove unneeded blank lines

client/app/components/account-nav/account-nav.directive.js, client/app/components/account-nav/account-nav.html
Ex->When we click on Profile, In goToProfile showDropdown = false and then toggleMenu again converts showDropdown = true, that's why menu was not closing.
After Changes->
=> Fix user menu not closing automatically on-click issue

circle.yml
Currently our continous integrations [failes]https://circleci.com/gh/hotosm/tasking-manager/1454?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link() with
```
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found
```
In the container for circle ci we were relying on Debian 8  codename Jessie. This PR updates to Debian 9 codename Stretch.
=> Update debian version for the circleci environment

Dockerfile
For some reason, #1393 refuses to build on CircleCI...even though #1394 is. Testing out a fresh branch PR to see if this can resolve it.
=> Update python version in Dockerfile

.ebextensions/aws.config
Synopsis so far:
* We have been experiencing latency issues on the main TM instance. (I still think this is because docker image builds are failing when EBS tries to scale up since the Dockerfile and circleci.yml files use Debian jessie on master at the moment.)
* Based on failing builds for other PRs that were cropping up around the time of the issues, @xamanu determined we need to update the debian version. That was done for the CircleCI deployment in #1411.
* Updates to the debian version in the Dockerfile were also made by him in #1393. However, CircleCI would refuse to build this PR even when using a fresh cache. That is despite #1394 building just fine with a very similar Dockerfile (one may be picking up the CircleCI config changes while the other isn't?? Not sure)
* In any case, I …
=> Generalize python version in db aws upgrade

.ebextensions/environment.config, .ebextensions/https.config, Dockerfile, devops/docker/tasking-manager/Dockerfile, docker-compose.yml
This PR fixes the issues we were having with the AWS Elastic Beanstalk deployment. It has been tested [in another branch](https://github.com/hotosm/tasking-manager/commits/modify/Dockerfile), which contains some temporal configuration on top of this PR to get the deployment testing going.
Please make sure the (new) environment variables are set for the staging and live site. Particularly these two:
* `TM_APP_BASE_URL`=`https://tasks.hotosm.org` (or similar)
* `TM_LOG_DIR`=`/var/log/tasking-manager-logs`
=> Fix Elastic Beanstalk deployment

cloudformation/tasking-manager.template.js
Currently, the tasking manager does not enforce the use of https. This PR enforces https use - the stack is currently set up at https://tasks-secure.hotosm.org/. You can see that `http://tasks-secure.hotosm.org/` does not work, while `https://tasks-secure.hotosm.org/` does. 
Fixes https://github.com/hotosm/tasking-manager/issues/1457
cc/ @dakotabenjamin @willemarcel @xamanu @smit1678 @russdeffner @ethan-nelson
=> Allow only HTTPS access to the tasking manager

server/api/messaging/project_chat_apis.py, server/services/messaging/chat_service.py
@willemarcel & I paired on to get a quick fix at the backend that prevents blocked users to post messages in project chat.
We would still rely on https://github.com/hotosm/tasking-manager/pull/1431 from @uwaiszaki for a holistic implementation.
cc @xamanu
=> Quick fix for [#1438] - Prevent blocked users from posting messages

example.env, server/config.py
The project configuration file does not define the postgres port as parameter to establish connection with the database and sets by default the port 5432.
This PR includes within the **config.py** file, the variable POSTGRES_PORT, which could be read as environment variable. This parameter was also set in the _example.env_ template file
=> Include postgres port as configuration parameter

client/app/services/stats.service.js, requirements.txt, server/__init__.py, server/models/dtos/stats_dto.py, server/services/stats_service.py
From #1147 - developing on @sunidhiraheja's work to add more home page stats. Similar to organisation summary, added 
Pending:
cc @smit1678 @ethan-nelson
=> Pending stats for home-page endpoint

client/app/admin/create-project/create-project.html, client/app/admin/edit-project/edit-project.html, server/models/postgis/project.py
Despite the instructions saying so, project metadata was not cloned during the cloning process. Additionally, users were required to add a title to submit the clone project form that was not actually copied to the cloned project. This PR solves those problems.
Fixes #1061 and fixes #1046 
Note the changeset comment is really difficult to handle in this situation. If a TM host changes the default changeset comment from when the original project was created to when the new project is cloned, we cannot easily remove that statement. But, for most intents and purposes (when the TM host does not change the default changeset comment often), the best effort attempt of searching for the default changeset comment with the old project id should be okay.
=> Improve cloning process

server/models/postgis/user.py
#1348 made it impossible for users without any involvement in any projects to login. The following error is was thrown:
```
User GET - unhandled error: object of type 'NoneType' has no len() [in /home/user/Code/HOT/tasking-manager/server/api/users/user_apis.py:48]
```
This was caused by a `len()` calculation. This PR introduces a basic test and allows the login to proceed.
=> Fix login for users without project activity

server/services/messaging/templates/level_upgrade_message_en.txt, server/services/users/user_service.py, tests/server/integration/services/users/test_user_service.py
Per conversation in https://github.com/hotosm/tasking-manager/issues/796, 
Snapshot of the message
=> Message users on level upgrade

server/services/messaging/chat_service.py
When posting a comment on a project an error message is presented that the comment was not added.
The log file presented:
```
CRITICAL: Chat PUT - unhandled error: name 'tm' is not defined [in /home/user/Code/HOT/tasking-manager/server/api/messaging/project_chat_apis.py:71]
```
This PR includes a necessary dependency declaration in order to fix this error.
=> Fix posting message when commenting

client/app/components/account-nav/account-nav.html, client/app/profile/profile.html, client/assets/styles/sass/_accountnav.scss, client/assets/styles/sass/_helpers.scss
* Show an exclamation-point icon in the top-nav next to the user's name if
they haven't provided an email address yet to receive notifications.
* Show the same icon on the drop-down menu next to the Profile menu-item,
and add a message to the Profile page asking the user to provide an
email address
=> Encourage user to provide email. Closes #1365

.circleci/config.yml
@arunasank merging this will trigger a build to the cloudformation production stack. 
Before merging, however, we need to have the RDS instance given a name that can be tracked by CircleCI so that snapshots can be made. . Hardcoding it to "tasking-manager-production" would be ideal.
=> Fix config string formatting

.circleci/config.yml
https://docs.aws.amazon.com/cli/latest/reference/rds/wait/db-snapshot-completed.html
Used db-snapshot-completed instead of `sleep 2m`. Throws an error and exits if snapshot does not exist.
cc/ @dakotabenjamin
=> Explicitly check that db-snapshot creation was complete

server/models/postgis/project.py
Fixes https://github.com/hotosm/tasking-manager/issues/1506 - Now project deletion will go through on task reset irrespective of whether there is discussion/comment within project. This is handled by defining a cascading relationship for `project_chat` table similar to how `project_info` and other tables relations are stated in the code.
**How to test?**
- Pick a test project that has mapping and discussions/comments
- Check deletion
- Deletion should throw an error message about contributions
- Now reset all tasks
- Try deletion again and this time it should get through without any error
=> Define cascade relation for project chat

client/app/project/project.controller.js
This Pull request fixes issue #924: When a task is marked as bad imagery, mapped, validated or invalidated, the selection mark of the task is lost.
**Steps for testing**
- Create a project.
- Select task to map.
- Mark task as mapped or bad imagery with or without comments.
- Validate task as valid or invalid
=> Keep task selection when changes applied

client/app/project/project.controller.js, client/app/services/project.service.js, server/api/project_apis.py, server/models/postgis/project.py, server/models/postgis/task.py, server/services/project_service.py
Add abbreviated project API. Rerolled PR by @ethan-nelson from #1368 on a local branch, squashed commit messages and based on latest `develop`.
> Please see #1153 for full background
> 
> This PR implements an "abbreviated" project API endpoint that does not contain geometry for the individual tasks and updates to the frontend to handle this. This behavior is only used for routine refreshing (the ~10 second idling refresh when a user is viewing the project screen without any interaction).
> 
> For routine refreshing, this is sufficient to change the states of tasks on a user's screen as they change state in the database. The core exception to this is when tasks are split, which is handled on the frontend by checking the length of the task layer currently loaded versus that sent by the …
=> Task diff update

server/models/postgis/task.py
This pull request fixes issue #1552. The **get_last_mapped_action** method from TaskHistory class returned only tasks with MAPPED status, making the error defined in the issue for BADIMAGERY ones.
- Create a project.
- Map some tasks as bad imagery.
- When validating mark task as invalid.
=> fix when Invalidating badimagery tasks

.circleci/config.yml
This PR solves a deployment issue where the RDS instance has changed (thus has a new ID), but the manual snapshots of the old RDS instance have not been deleted. This caused the deployment to fail because the snapshot names were not unique to the database instance. The script checks for a snapshot for the new database, finds none, and attempts to make a new snapshot with the same name as the old snapshot. Snapshot IDs have to be unique, so the command fails. 
In this PR, I make snapshot names unique to avoid that issue. I also check in the cleanup step if the database instance has been changed, and delete the manual snapshot `tm3-<< parameters.stack_name >>-$RDS_ID-latest`
=> Cfn ci snapshot ids

client/app/profile/profile.controller.js, client/app/profile/profile.html, client/app/services/project.service.js
This PR fixes #1529. In the profile view, when the overpass function is executed for a given project, there will be a call to the server to get the project aoi. Then this information is used to create the overpass turbo url
=> Get project aoi from service in overpass function

devops/scripts/install_on_debian_10_buster.sh, devops/scripts/install_on_debian_9_stretch.sh, devops/scripts/install_on_ubuntu_18_04.sh
* Moves basic install scripts from the wiki into the repo `devops`/`scripts`
* Upgrades install script for Ubuntu fro 16.04 to 18.04
* Adds install scripts for Debian 9 Stretch and 10 Buster
* Deprecates Cent OS 7 install script.
=> Add install scripts for Debian 9, 10 and Ubuntu 18.04

client/app/project/project.controller.js
This Pull request modifies the `unlockTaskValidation` function within the client with the purpose of keeping the task history after it is validated.
- Create a project.
- Select a task and select as bad imagery or mapped.
- Go to validation tab.
- Mark as valid or invalid
The reviewer should see the task history, without additional action.
=> Keep task history when task is validated

server/models/postgis/task.py
This Pull request fixes the following issue:
When a project task has been previously validated, it becomes impossible to reset the task status to READY, because the current method returns the second-last status that the task has. 
The commit checks on an un-mark request to return a READY when the current status of the task is set to BADIMAGERY or MAPPED
**Steps:**
1. Create a project.
2. Set a task status to MAPPED or BADIMAGERY.
3. Unmark the task. You will see on history that the the task has now a status of READY.
4. Map a task and validate it.
5. Unmark the task. It will now have a MAPPED or BADIMAGERY status.
6. Unmark again the task. It will now have a ready status.
=> Reset status to ready when map has been previously validated

.circleci/config.yml, devops/cloudformation/tasking-manager.template.js
Fixes https://github.com/hotosm/tasking-manager/issues/1632 when done.
=> Add the default changeset comment env variable to CloudFormation

client/gulpfile.js
Optimize gulp watch to only track files inside our project and not the whole node_modules dir, it uses less CPU this way.
=> Optimize gulp watch 

client/app/components/mapper-encouragement/mapper-encouragement.directive.js, client/app/components/mapper-encouragement/mapper-encouragement.html, client/app/components/mapper-level-indicator/mapper-level-indicator.directive.js, client/app/components/mapper-level-indicator/mapper-level-indicator.html, client/app/home/home.html, client/app/profile/profile.html, client/assets/styles/sass/_landingpage.scss, client/assets/styles/sass/_mapper_encouragement.scss, client/assets/styles/sass/_mapperlevel.scss, client/assets/styles/sass/_profile.scss, client/assets/styles/sass/_structure.scss, client/assets/styles/sass/_variables.scss, client/assets/styles/sass/taskingmanager.scss, client/index.html
* Closes #1381 
* Show a trophy icon in the top-nav in a color representing the
logged-in user's mapping level (bronze, silver, or gold for beginner,
intermediate, or advanced respectively), and also prominently display
user's mapping level on their profile page
* Show message on home page and profile page encouraging mappers to
continue mapping and advance to the next level (or to try validating in
the case of advanced mappers)
=> Mapper-level icons and encouragement messages

devops/cloudformation/tasking-manager.template.js
Instead of making the instance type a configurable parameter, we're keeping them constant across non-production stacks.
I also modified the capacity requirements across stacks to be different for production and the others.
cc/ @smit1678 @xamanu @ramyaragupathy
=> Use smaller RDS instances for non production stacks

client/app/admin/dashboard/dashboard.html, client/app/components/ng-click-copy/ng-click-copy.js, client/app/components/project-chat/project-chat.html, client/app/components/tm-timestamp/tm-timestamp.directive.js, client/app/components/tm-timestamp/tm-timestamp.html, client/app/message/inbox.html, client/app/message/message.html, client/app/profile/profile.html, client/app/project/project-dashboard.html, client/app/project/project.html, client/app/taskingmanager.app.js, client/assets/icons/clippy.svg, client/assets/styles/sass/_tables.scss, client/assets/styles/sass/_tmtimestamp.scss, client/assets/styles/sass/taskingmanager.scss, client/index.html
* Closes #1359 
* Users in expert mode can hover over a timestamp to view it in IS08601
format
* Clicking the ISO8601 timestamp copies it to the user's clipboard
* Users who are not in expert mode continue to experience existing
behavior
* Introduces a new `tm-timestamp` directive that should be used in place of the old `am-time-ago | amUtc | amLocal` filter chain
=> Show expert users ISO8601 timestamps on hover

server/models/postgis/message.py, server/models/postgis/project.py, server/models/postgis/user.py, server/services/stats_service.py, server/services/users/user_service.py, server/services/validator_service.py
Fixes #1659 - using Postgres timestamp function in
- project/summary (this affects dashboard)
- stats/user/{username}
- stats/project/{id}/contributions
- user-id/{userid}
Fixes #1668 - using `text()` for `order_by` clause
Fixes #1676 - Define cascade relation for Messages table
=> Version 3.3.1 Release

devops/cloudformation/tasking-manager.template.js
Increasing from t2.micro to t2.small will bump the DB instance memory from 1GB to 2GB and improve page load times for the staging stack. 
See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.Types for more details.
=> Increase staging DB Instance Class to db.t2.small

devops/cloudformation/tasking-manager.template.js, server/services/messaging/message_service.py
Enabling verboser logging inadvertently caused the RDS instance storage to fill up. This PR will revert those changes.
=> Remove verbose RDS logging

docs/setup-development.md
Update readme for the fix of #1479.
=> update readme to add local dev postgres environment instruction

migrations/versions/b25f088d40c2_.py, server/models/postgis/message.py, server/services/messaging/message_service.py
This Pr removes the cascade deletion on message model.
1. Apply required migration.
2. Alter your user as admin in your local instance.
3. Create a toy project. 
4. In _Questions and comments_ tab, reference yourself and send messages.
5. Then go to your inbox. The messages will appear.
6. Delete messages.
7. Go back to the project view. Also, you can verify executing a query to get the project from projects table.
=> Do not apply cascade deletion on message model

devops/cloudformation/tasking-manager.template.js
Resolved the RDS part of https://github.com/hotosm/tasking-manager/issues/1693
The database is currently at 100GB so it shouldn't fill up like before. The logs are stored temporarily on the file system before being pushed to s3, so as long as they are not massive, it should be fine.
=> Enable RDS Cloudwatch Logging and transactional logs

client/package.json, example.env
* Eslint has a security update, which is included here
* Further, I sneak in here some minor changes on the example configuration file to support Korean (related to #1717)
=> Update eslint to 4.18.2

client/app/services/project.service.js, client/app/services/stats.service.js, server/__init__.py, server/api/project_apis.py, server/api/stats_api.py, server/models/dtos/project_dto.py, server/models/dtos/stats_dto.py, server/models/dtos/user_dto.py, server/models/postgis/project.py, server/services/project_search_service.py, server/services/project_service.py, server/services/stats_service.py
#1685
Adds an abbreviated parameter to:
Both these endpoint defaults to `abbreviated=true`.
Setting abbreviated to true, would fetch only results that are not computationally intensive and satisfies the bare minimum requirement for the page that invokes the endpoint. To implement this moves the time computations to a separate class and added a condition check to the respective functions.
=> Improve contribution stats endpoint

migrations/versions/451f6bd05a19_.py
This PR fixes #1723 . Current database status with latest migration file does not have automatic trigger to index information into the `text_searchable` column from project_info table. This disallows project search since text_searchable column is NULL
The commit enables and automatic trigger which indexes before an insert or update in project info table.
**how to test**:
1. Create a fresh database.
2. Run migrations
```python manage.py db upgrade```
3. Downgrade
```python manage.py db downgrade```
4. Create a project with description and short description.
5. Verify that text_searchable column is null.
```SELECT text_searchable FROM project_info```
6. Update migrations
```python manage.py db upgrade```
7. Edit project_info again
8. Verify that information is indexed
```SELECT …
```
=> Include automatic trigger for indexing text_searchable

manage.py
Aiming for version 4 of the TM, we can deprecate the former environment variables for the configuration and rely only on the one introduced in version 3.2.0
=> Deprecate former environment schema

server/models/dtos/project_dto.py, server/services/project_search_service.py
This PR includes a hotfix which includes within project search results, the _last_updated_ field from database. It is related to https://github.com/hotosm/tasking-manager/issues/1628#issuecomment-513908693
=> Return project last_updated field in project search endpoint

server/web/controller.py
api-docs was failing to load if we access with a trailing backslash
=> make api-docs url load even with trailing backslash

.circleci/config.yml
Introduce a random string nonce for the temporary snapshot name to
avoid collision.
=> Fix #1622: Circle-ci RDS snapshot replacement is buggy

devops/cloudformation/tasking-manager.template.js
Fixes #1510 
This solves the issue where new CFN stacks are created with a blank database or via dump where postgis isn't initially installed already.
=> Add PostGIS initialization to deployment script

server/__init__.py, server/api/users/user_apis.py, server/models/dtos/user_dto.py, server/services/users/user_service.py
This PR closes #1604. Within the API, when hitting:
```
'/api/v1/user-id/<int:userid>/contributions
```
The server will return the number of contributions by day for the last 365 days. Dates without contributions will have the value of 0.
=> List contributions from a user by day

requirements.txt
This PR solves the following error when executing gunicorn with multiple workers:
```
RuntimeError: You need gevent installed to use this worker.
```
=> Include missing libraries for gunicorn

frontend/src/serviceWorker.js
It was reported that with the new frontend the backend api call weren't always successful. While I had a difficult time reproducing it, I was able to do so in a Chromium. API calls aren't successful, but when force uncached reload with CTRL+SHIFTR+R (or SHIFT+F5) it worked.
This if-clause for localhosts is causing the problem. Taking it out here. But not completely sure whether we will need this or not.
=> Fix api path loading on localhost

server/api/projects/resources.py, server/models/postgis/project.py
This PR covers the following endpoints:
* `/api/v1/project/{project_id}/summary`-> `/api/v2/projects/{project_id}/queries/summary`
* `/api/v1/project/{project_id}?abbreviated=True` -> `/api/v2/projects/{project_id}/queries/nogeometries`
* `/api/v1/admin/project/{project_id}` -> `/api/v2/projects/{project_id}/queries/notasks`
* `/api/v1/project/{project_id}/aoi` -> `/api/v2/projects/{project_id}/queries/aoi`
* `/api/v1/project/{project_id}/tasks` -> `/api/v2/projects/{project_id}/tasks`
@willemarcel - for project fetch let's use:
`/api/v2/projects/{project_id}/queries/nogeometries` and `/api/v2/projects/{project_id}/tasks`
to reduce delays in low bandwidth.
=> Redesign - Projects data fetch

scripts/database/duplicate-priority-area-cleanup.sql
From #1789 - using a script to remove duplicate entries of priority areas. Tested the script against a local DB - database operation and subsequent interaction in localhost went well.
Number of projects with duplicate priority areas: 808
Table|Entries in the Current State|Entries After Script Execution
-----|--------------|----------------------
`priority_areas`| 858 | 858
`project_priority_areas`|4888| 848 
* 808 projects- each had 6 entries for one of their priority area, so after removing - 5x808 = 4040 entries in total, `project_priority_areas` will have 848 entries in total
* Other observation - there is a mismatch of about 10 priority areas between tables` priority_areas` and `project_priority_areas`. This is because 10 priority area IDs( 4112, 3876, 3827, 3826, 3825, 3824, 2708, 6, …
=> Remove duplicate priority geometries

server/services/project_search_service.py, server/services/project_service.py
This PR optimizes the project search endpoint stated within issue #1849 . The taskhistory join table is executed only for the paginated results query.
=> Perform taskhistory join only within paginated results query

frontend/src/components/taskSelection/mappingTypes.js, server/models/postgis/project.py
Updated `summary` endpoint to check if `mapping_types` field has some value before iteration begins. Thanks for the flag @thadk
=> Check field availability before processing

migrations/versions/0eee8c1abd3a_.py
This issue closes #1894. 
- Run migrations script: `python manage.py db upgrade`
=> Force files to be read with utf-8 encoding

server/models/dtos/project_dto.py, server/models/postgis/project.py
Per chat w/ @willemarcel - added a new field to summary endpoint that lists allowed users for private project.
```
"allowedUsers": [
"Abdul-Basit_eHA",
"kazeem",
"ugwuzor chinwe",
"seyeabrahams",
"Junaid Ibrahim",
"tobiwonderful",
"Hadeezah Musa",
"kerry_o"
]
```
@willemarcel - what do you think will be useful here - user id or username? At present this returns username, I feel it should return IDs though
=> Include allowedUsers list for private projects

server/models/postgis/statuses.py, server/services/project_service.py
This PR closes #1902 
**How to test**:
1. Load the database dump from _tests_ folder.
2. Alter projects and set allow_non_beginners = True
```
UPDATE projects SET allow_non_beginners=true;
```
3. Alter a single user and set mapping level as begginer:
```
UPDATE users set mapping_level=1 where user_id=94253
```
4. using flask shell command, import service method
```
python manage.py shell
In [1]: from server.services.project_service import ProjectService                                                                             
In [2]: ProjectService.is_user_permitted_to_validate(1, 360183)                                                                                
Out[2]: (True, 'User allowed to validate')
In [3]: ProjectService.is_user_permitted_to_validate(1, 94253) …
```
=> Validate user mapping level for projects with allownonbeginners

server/__init__.py, server/api/projects/statistics.py, server/services/project_search_service.py, server/services/stats_service.py
This PR fixes #1613 . The established logic corresponds to list 30 most popular projects. The popularity level consists on projects with most tasks changes for the past 30 days.
Using a database dump, hit `/api/v1/stats/popular/projects`
=> List popular projects

frontend/src/components/projects/projectsMap.js
If no Mapbox API key is set for a custom instance of TM4, then this raster fallback map will appear with the old HOT Humanitarian raster layer, after this tiny pull request adds HTTPS support.
=> make fallback raster style work with https

frontend/src/components/header/createPopup.js, frontend/src/components/header/index.js, frontend/src/store/actions/auth.js, frontend/src/views/authorized.js, server/api/system/authentication.py, server/services/users/authentication_service.py, tests/server/unit/services/users/test_authentication_service.py
This PR closes #1892  and #1914. 
**Server side**:
- The api endpoints to login and callback were modified to return oauth params instead of making redirections.
- The api returns openstreetmap login url, OSM oauth_token and oauth_token_secret.
- The login url must have the request parameter _callback_url_. clients should be able to handle this endpoint.
**Client side**:
- The login url is now created within a popup window, which is closed automatically after successfull login
=> Login user from popup

scripts/docker/tasking-manager/Dockerfile
Change allows Docker image to build - previously Python 3.8 would cause error when installing pyproj.
=> Specify Python 3.7 in tasking-manager Dockerfile

devops/cloudformation/tasking-manager.template.js
This update addresses some drift that has occurred in the production application stack. @xamanu in the unlikely event of a rollback on the cloudformation update, the database would fail to rollback properly and we would probably have to rebuild from scratch. These changes address that drift.
=> Change cfn database instance type and update engine

frontend/src/hooks/UseTagAPI.js
Make it so the contribute page gracefully handles the backend being down. 
Specifically the API that gets the organisation list, UseTagAPI, needed to check for the `content-type` of the response. The other frontend APIs already check for this.
=> TM4 contribute page shows error, not blank, if backend down

.circleci/config.yml
Without the correct stack name, we cannot update the Cloudformation Stack. This fixes the issue with the deployment last night. 
@eternaltyro and I discussed parameterizing this, which we will look into in TM4
=> Change circleci production app stack name to current

server/api/interests/resources.py, server/api/projects/actions.py, server/api/users/actions.py
Related to https://github.com/hotosm/tasking-manager/issues/1926#issuecomment-551311538
- Only PM's can create, update and delete interests
- Only PM's can associate projects with interests
- Only the user can associate themselves with interests
=> review permissions of interests api endpoints

frontend/src/store/actions/auth.js, server/__init__.py, server/api/users/actions.py
The interests of a user can only be changed by themselves, so we don't need the `user_id` param on the URL. I updated it from `/api/v2/users/<int:user_id>/actions/set-interests/` to `/api/v2/users/actions/set-interests/`.
=> fix set-interest for user URL

frontend/src/App.js, frontend/src/components/header/index.js, frontend/src/components/homepage/jumbotron.js, frontend/src/components/projects/moreFiltersForm.js, frontend/src/components/projects/projectNav.js, frontend/src/hooks/UseProjectsQueryAPI.js, frontend/src/views/project.js
@willemarcel We haven't talked about it. But I thought I would propose this via code. Is much faster :smile:
With the new structure we will have a "My contributions" in parallel to the "Explore" or "Explore Projects" section. So using the old path of `contribute` might become misleading. So proposing here to change the path to `explore`.
=> Rename explore projects path

server/models/postgis/project.py, server/models/postgis/user.py, server/services/users/user_service.py
=> Include auto unlock operations for time aggregates

devops/cloudformation/tasking-manager.template.js
As of December 11, the [PPA we were using to install Python 3.6](https://launchpad.net/~jonathonf) on our AWS Cloudformation stacks took all of their packages private. We have replaced that PPA repo with a [new one](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa). 
This change only affects AWS deployments. I didn't see this repo being used anywhere else. I tested the changes on a fresh cloudformation stack with no errors- the logs showed that Python3.6 was installed and the rest of the installation went well. I was able to connect to the running instance from my browser. 
These changes affect the TM infrastructure- changes to the LaunchConfiguration resource will replace all running instances in the Autoscaling Group. No other resources are affected.
=> Replace jonathonf python ppa with deadsnakes

scripts/aws/cloudformation/tasking-manager.template.js
This will fix `staging`, then we can push to `deployment/redesign-tasking-manager` to fix tm4.
=> Replace python3.6 repository for Cloudformation template

frontend/src/App.js, frontend/src/components/header/topBar.js, frontend/src/components/projectDetail/messages.js, frontend/src/components/user/content.js, frontend/src/locales/en.json, frontend/src/locales/pt.json, frontend/src/views/about.js, frontend/src/views/learn.js, frontend/src/views/messages.js
This PR adds initial content to the about and learn page. It also removes the help page.
Missing:
Text is being worked on [here](https://docs.google.com/document/d/1TiijUgKZLUB6ui39tfjg_AZYXX4iE0DN1k4kbTbpDFI/edit?usp=sharing)
FYI @willemarcel
=> Add about and learn pages

server/api/users/openstreetmap.py
Removed the login requirement on an endpoint that fetches OpenStreetMap details during user login. Testing it with a new non-PM OpenStreetMap login and it was successful.
cc @xamanu @willemarcel @dakotabenjamin
=> Fix user login on TM4

frontend/src/components/taskSelection/footer.js, frontend/src/components/taskSelection/index.js, frontend/src/utils/openEditor.js, frontend/src/utils/tasksGeometry.js, frontend/src/utils/tests/openEditor.test.js, frontend/src/utils/tests/snippets/tasksGeometry.js, frontend/src/utils/tests/tasksGeometry.test.js
It's missing to add other editors, but iD is ready. @xamanu feel free to merge it now or wait for the other editors. I think I can implement the other editors this Thursday.
=> open id editor when user locks a task for mapping/validation

server/services/project_service.py
From #2063 - implementing a check in lock-for-validation to know if user has any tasks locked for mapping/validation. 
cc @willemarcel @xamanu
=> Check locked tasks before validation

server/api/tasks/resources.py, server/services/project_service.py, tests/server/unit/services/test_project_service.py
Per chat w/ @willemarcel - updating the endpoint `/api/v2/projects/tasks/queries/own/locked/` to return an empty array when a user has no locked tasks. At present this returns 404 - modified this to return `{"lockedTasks": []}`
=> Handle no locked tasks scenario as 200 instead of 404

server/services/project_search_service.py, server/services/stats_service.py
From #2095 -  add group by clause to include project id. Endpoint affected: `/api/v2/projects/queries/popular/`
=> Fix popular projects endpoint

server/api/projects/resources.py, server/models/dtos/project_dto.py, server/services/project_search_service.py, server/services/users/user_service.py
From #2094 - 
* Introduced a filter under `/api/v2/projects/` to filter results from projects mapped/validated by user
* Updated the user model function `get_projects_mapped` to get the pre-computed `projects_mapped` column from users table - it is an array field that captures all projects with at least one task mapped/validated by the user. This function was earlier using TaskHistory model to filter rows every time the function is called. Using pre-computed values will improve search result performance.
=> Projects mapped filter under project search

server/services/mapping_service.py, server/services/messaging/message_service.py
Per chat w/ @willemarcel -  endpoint `/api/v2/projects/{project_id}/comments/tasks/{task_id}/` was returning `Task Comment API - unhandled error: 'ResultProxy' object is not subscriptable`. fixed the same.
=> Fix task comments endpoint

frontend/src/components/projectEdit/settingsForm.js, frontend/src/components/taskSelection/footer.js, frontend/src/config/index.js, frontend/src/utils/editorsList.js, frontend/src/utils/openEditor.js
* use the same values on frontend for the user default_editor option and the project editors for mapping and validation 
* define the selected option automatically according to the user preference and with the options available to the action the user is taking.
=> change user's default_editor values

frontend/src/components/header/signUp.js, frontend/src/utils/login.js, server/api/system/authentication.py, server/services/users/authentication_service.py, server/services/users/user_service.py, tests/server/integration/services/users/test_authentication_service.py, tests/server/integration/services/users/test_user_service.py, tests/server/unit/services/users/test_authentication_service.py
This PR closes #2092 .
When a new user signs up into Tasking Manager, the client stores within  **LocalStorage** the registered email. Then, when the user goes back from OSM login, the client validates the email_address within localstorage and sends it to the server, which is then saved into the database. This happens only for new users.
**how to test**: The reviewer needs a clean migrated database. In other case, the reviewer OSM username removed from **users** table.
- Sign up into Tasking Manager. If success, the client redirects to OSM website.
- Login to Tasking Manager. If success, you will see automatically, the email address
=> Read registered user email from localstorage

server/models/postgis/task.py, server/services/messaging/message_service.py, server/services/users/authentication_service.py, tests/server/integration/models/postgis/test_project.py, tests/server/unit/services/users/test_authentication_service.py
…ts variable as array
These tests need to be run locally using a fresh database.
**Notes:**
1.  I think we would have to review the _UserService.get_projects_mapped_ function, since **projects_mapped** db column is repeated twice within the User model. This might cause the **None** value returned in tests
- https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/user.py#L37
- https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/user.py#L41 
2. The CI environment check does not need to be done within the **server** folder for two reasons: 
a. Not all TM forks might use CI/CD
b. The check removes the _send_favorite_project_activities_ function to be tested locally.
=> Local tests fixes

frontend/src/components/projectCreate/projectCreationMap.js, frontend/src/components/projects/projectsMap.js, frontend/src/components/taskSelection/map.js
Even in smaller screens, the OSM attribution will be always visible and never replaced by the compact attribution.
=> assure OSM attribution is always visible

server/services/project_service.py
From https://github.com/hotosm/tasking-manager/issues/2191 - issue arises because of a missing field check. While [introducing additional fields for user's locked tasks DTO](https://github.com/hotosm/tasking-manager/pull/2107), we have the task list included in a new array field called `locked_tasks`. However [`is_user_permitted_to_validate`](https://github.com/hotosm/tasking-manager/blob/develop/server/services/project_service.py#L230) - still has conditional checks for the old DTO, updated the condition check field.
=> Update locked tasks DTO field check

frontend/src/components/taskSelection/footer.js
- open editor when user resumes mapping or validation
=> Improvements to open editor functionality

server/services/users/user_service.py
This returns an empty list in case the user does not have projects_mapped. Removed the iteration since the query _should_ always return a single element
=> Validate no projects mapped from user

frontend/src/components/taskSelection/action.js, frontend/src/components/taskSelection/footer.js, frontend/src/components/taskSelection/messages.js, frontend/src/utils/editorsList.js, frontend/src/utils/openEditor.js, frontend/src/utils/tests/editorsList.test.js, frontend/src/utils/tests/openEditor.test.js, server/models/dtos/project_dto.py, server/models/postgis/project.py
- add dropdown to reopen editor on map/validation pages (solves #2088)
- add customEditor field to project summary endpoint
- add customEditor to editors list on task selection, map and validation page (it's missing to add it on the project edit) (related to #1924)
=> Reopen editor + customEditor

frontend/src/components/projectDetail/index.js, frontend/src/components/projectDetail/messages.js, frontend/src/components/projectDetail/projectDetailFooter.js, frontend/src/components/projectDetail/showReadMoreButton.js, frontend/src/views/project.js
It solves #2165, #2160, #2161 and #1942
- fix the position of the bar with the Contribute button on the bottom of the window
- add the contributors avatars
- reduce the number of endpoints fetched from 6 to 5.
- improve the behaviour of the "read more" button and of the project overview section
=> fix problems on the style of the project detail page

server/models/dtos/interests_dto.py, server/models/dtos/user_dto.py, server/services/users/user_service.py
this PR closes #2231 .
You can test using a database dump from _tests_ folde and run `python manage.py shell`
1. Create some interests:
```
from server.models.postgis.interests import Interest
items = ['Water', 'Sanitation', 'Disaster Risk Reduction', 'environment', 'disaster Response', 'public health', 'gender equality'] 
[Interest(name=i).create() for i in items]
```
2. Asociate interests with projects.
```
from server import db
proj = Project.query.get(1)
proj.interests = [Interest.query.get(i) for i in [1, 2, 3]]
db.session.commit()
proj = Project.query.get(2)
proj.interests = [Interest.query.get(i) for i in [1, 2, 4, 5]]
db.session.commit()
```
3. Perform API  request to `/users/wille/statistics/` and `/users/xamanu/statistics/`. The response shows an additional field. Interests …
=> Projects contributed by interest backend

frontend/src/components/projectcard/projectCard.js, frontend/src/components/projects/projectNav.js
- on project cards 
- avoid priority text going out of the box 
- give more space between org logo and project id
- on nav bar, avoid `show map` from going to the top of the toggle switch + set more breakpoints
=> improve responsiveness of explore projects page

server/services/stats_service.py
Per chat w/ @willemarcel - removing COMMENT as a task activity for `projects/{project_id}/activities/latest/` endpoint
=> Remove comment status from latest activity

frontend/src/components/notifications/notificationCard.js, frontend/src/components/projectDetail/index.js, frontend/src/components/projectDetail/questionsAndComments.js, frontend/src/components/teamsAndOrgs/campaigns.js, frontend/src/components/teamsAndOrgs/management.js, frontend/src/components/teamsAndOrgs/members.js, frontend/src/components/teamsAndOrgs/messages.js, frontend/src/components/teamsAndOrgs/organisations.js, frontend/src/components/teamsAndOrgs/projects.js, frontend/src/components/teamsAndOrgs/teams.js, frontend/src/components/teamsAndOrgs/tests/members.test.js, frontend/src/components/teamsAndOrgs/tests/organisations.test.js, frontend/src/components/user/avatar.js, frontend/src/components/user/tests/userAvatar.test.js, frontend/src/utils/teamMembersDiff.js, frontend/src/utils/tests/teamMembersDiff.test.js, frontend/src/views/campaigns.js, frontend/src/views/management.js, frontend/src/views/messages.js, frontend/src/views/organisations.js, frontend/src/views/teams.js, server/__init__.py, server/api/teams/actions.py, server/models/postgis/statuses.py, server/services/team_service.py
- add section to manage team join requests
- fixes on join team api
- set the correct methods on the `__init__.py`
- rename response field to accept on the payload
- Remove `secret` option from team visibility field (both frontend and backend)
- changes in the team membership page
- add box if the team is `inviteOnly`
- update button to show `Cancel request` instead of `Leave team` if the team is invite only
- show message if the user has already asked to join the team
- set a max width to the organisation logo
- show organisation name
- add `visibility` and `inviteOnly` information to team cards
- add management submenu on all management pages
- Link UserAvatars
- remove `Add+` button from edit team/organisation pages
=> Team membership improvements

frontend/src/components/projectDetail/index.js, frontend/src/components/projectEdit/messages.js, frontend/src/components/projectEdit/permissionsForm.js, frontend/src/components/projectEdit/teamSelect.js, frontend/src/components/taskSelection/index.js, frontend/src/utils/projectPermissions.js, frontend/src/utils/tests/permissionsToMap.test.js, frontend/src/utils/tests/permissionsToValidate.test.js, frontend/src/utils/tests/taskAction.test.js, frontend/src/views/projectEdit.js, migrations/versions/c40e1fdf6b70_.py, server/models/dtos/project_dto.py, server/models/postgis/project.py, server/models/postgis/statuses.py, server/services/messaging/message_service.py, server/services/project_service.py, server/services/team_service.py, tests/server/unit/services/test_project_service.py
- update permissions on the frontend to the new schema based on teams and/or level
- add teams to project summary endpoint
- rename `projectTeams` field to `teams` on the projectsDTO
- update project edit and project code views to fit the new field name
:stop_sign:  To be merged and to work, we depend on some changes on the backend.
=> update permissions to the new schema based on teams and/or level

frontend/src/components/projectCreate/projectCreationMap.js, frontend/src/components/projectEdit/priorityAreasForm.js, frontend/src/components/projects/projectsMap.js, frontend/src/components/taskSelection/map.js, frontend/src/components/userDetail/countriesMapped.js
We had a problem with center location of the Mapbox Style we are using. The style will be fixed, but in order to avoid problems with other styles, I found a solution (and probably a bug in mapbox-gl-js: https://github.com/mapbox/mapbox-gl-js/issues/9299).
=> avoid maps from loading in the wrong location

server/services/project_search_service.py
As discussed in this [issue](https://github.com/hotosm/tasking-manager/issues/2132), fix project search by status.
The projects were always including `PUBLISHED` projects even when using filters for `DRAFT` and `ARCHIVED` projects statuses.
This happened because of an array that always started with data from `PUBLISHED` projects, as shown below:
https://github.com/hotosm/tasking-manager/blob/bfc609c0cf6ae639f7c0e5ebae128aa9a4594627/server/services/project_search_service.py#L194-L199
=> Fix project search by status

frontend/src/components/taskSelection/index.js, frontend/src/components/taskSelection/taskList.js, frontend/src/views/userDetail.js
The search by username on the task selection page was considering only the last user that interacted with that task, so I changed it in order to return all the tasks a user has contributed to.
=> improve user filtering on task selection page list

server/api/annotations/resources.py, server/api/comments/resources.py, server/api/projects/activities.py, server/api/projects/contributions.py, server/models/postgis/project_chat.py, server/models/postgis/task_annotation.py, server/services/project_service.py, server/services/stats_service.py
Closes #2047 
Fix `list endpoints which were returning 404 errors if the project exists, but without activity or contribution associated with them.
I took some code from @fitoria's [branch](https://github.com/hotosm/tasking-manager/tree/bugfix/return-values-fixes) and added the contents that were missing.
I added this if statement in the `ProjectsContributionsAPI` class in the `/server/api/contributions.py` file
```py
class ProjectsContributionsAPI(Resource):
def get(self, project_id)
if not ProjectService.exists(project_id):
return {"Error": "Project not found"}, 404
```
And the same for the  `ProjectsActivitiesAPI` class in the `/server/api/contributions.py` file.
```py
class ProjectsActivitiesAPI(Resource):
def get(self, project_id):
if not ProjectService.exists(project_id):
return …
```
=> Fix list endpoints return values

scripts/aws/cloudformation/tasking-manager.template.js
Improve instance profile for tasking manager instances by replacing
inline policies with AWS Managed IAM Policies wherever possible.
Add additional policies to facilitate better management and monitoring.
Policies:
- AWS SSM Managed Instance Core Policy
- CloudWatch Agent Server Policy
- CodeDeploy EC2 Role Policy
- RDS Describe Instances (left intact)
- CloudFormation signalling permissions (left intact)
=> Improve tasking manager IAM profiles

server/api/system/statistics.py, server/models/dtos/stats_dto.py, server/models/dtos/user_dto.py, server/models/postgis/task.py, server/models/postgis/user.py, server/services/stats_service.py, server/services/users/authentication_service.py, tests/server/unit/services/users/test_authentication_service.py
Per chat w/ @willemarcel: 
* removed the `send_favorite_project_activities` function call during login. This should make the login very quick. 
* Also removed the `projectsMapped` field from UserDTO. This is still available under `UserStatsDTO`
* removed time computations from userDTO. These are available through userStats
* removed order by last update on tasks as part of project/id endpoint. This should save some time on project load
=> Remove project check during login

.circleci/config.yml
With this single line change to the CircleCI configuration, we can adjust the autoscaling policy for the TM4 AWS infrastructure. After this test is complete, let's revert back to the `demo` setting until necessary.
=> Change TM4 autoscaling policy to production

server/api/projects/resources.py, server/models/postgis/user.py
On `projects/queries/<string:username>/touched/`:
* return 404 for a user not found
* return empty array when the user has not touched any project. This is similar to how we handle projects with zero task activity
=> Fix projects touched error code for no mapping

frontend/src/components/projectEdit/inputLocale.js
The project edit form fields that can have translation were causing the app to break when the value was empty. I fixed it and also pushed a little improvement to the style.
=> fix bug in project edit form fields and improve style

frontend/src/components/taskSelection/action.js, frontend/src/components/taskSelection/footer.js, frontend/src/components/taskSelection/messages.js, frontend/src/components/taskSelection/taskList.js, frontend/src/locales/en.json, frontend/src/views/taskAction.js
Resolves https://github.com/hotosm/tasking-manager/issues/2017, resolves https://github.com/hotosm/tasking-manager/issues/2344
Plus:
- fixes bug: editor was not opening when user was going to resume mapping/validation.
- avoid the pagination to return automatically to the selected task page when the tasks status are updated
=> multiple tasks validation + show all tasks on map/validate page

frontend/src/components/projectCreate/setAOI.js
The split problem comes from the zoom level value given in the project creation section. Zoom level must be an integer in order to generate correctly the taskGrid an a successfull task split.
I have tested using different aoi geometries and zoom levels. 
**How to test**:
- Create and edit a project.
- Select a task for mapping/validating.
- Click Task Split.
This pr fixed the splitting bug for new projects created. However, does not solve the issue for old projects
=> Transform zoom level value to integer in project creation view

docs/contributing-code.md, docs/contributing.md, docs/customize.md, docs/migration-from-tm2.md, docs/setup-development.md, docs/setup-docker.md
Closes #2432
As discussed in this [issue](https://github.com/hotosm/tasking-manager/issues/2432), fix some links that are broken in the documentation.
Errors fixed:
* [`contributing-code.md`](https://github.com/hotosm/tasking-manager/blob/8f05eef7cb008c680a82dc9884ab7a83a12ab1f8/docs/contributing-code.md): The link for `meaningful commit messages` is not working, I suggest another article like this [one](https://medium.com/@nawarpianist/git-commit-best-practices-dab8d722de99) or a suggestion from the maintainers.
https://github.com/hotosm/tasking-manager/blob/8f05eef7cb008c680a82dc9884ab7a83a12ab1f8/docs/contributing-code.md#L25
* [`contributing.md`](https://github.com/hotosm/tasking-manager/blob/8f05eef7cb008c680a82dc9884ab7a83a12ab1f8/docs/contributing.md): The `Contributor Covenant …
=> Fix documentation links

backend/services/messaging/chat_service.py, backend/services/project_admin_service.py
Project update on TM4 failing with `TypeError: get_organisation_by_id_as_dto() missing 1 required positional argument: 'user_id'` fixed through this PR
=> Update org fetch parameters while invocation

.circleci/config.yml, scripts/aws/cloudformation/tasking-manager.template.js
Fixes an issue with setting the Alternative CNAME on the Cloudfront Distribution
Notes: 
- ~~I still need to set the variables in CircleCI~~
- We will need to *DELETE* the following route53 records prior to deployment (the record will be recreated by cloudformation)
- tasks-stage.hotosm.org
- tm4.hotosm.org
- tasks.hotosm.org
- tasks-assisted.hotosm.org
- tasks.teachosm.org (need to doublecheck this one actually)
=> Add route53 record to configure cloudfront distro for frontend deployment

.circleci/config.yml, scripts/aws/cloudformation/tasking-manager.template.js
The variable for TM_LOGGING_LEVEL was parsing to `${INFO} instead of `"INFO"`, which was causing it to be blank in the Cloudformation Template. This PR fixes that, and sets a default logging level of "INFO" as a backup.
=> Fix logging level variable in circleci

backend/models/postgis/project.py, backend/services/project_search_service.py
From #2454:
* Introduced a new function to compute per project distinct user ID count
* Commented out earlier method call which returns an ascending list of contributor count irrespective of the sort order in the API call. This resulted in count mixup between projects
=> Fix contributor count on  project sort 

scripts/aws/cloudformation/tasking-manager.template.js
Fixes #2556 
I have tested this on an AWS stack and can confirm it works:
=> Replace health check path with working endpoint

frontend/src/components/editor.js
This addresses feedback we got during the testing:
> Scale bar: When I'm training, or giving feedback I instruct the mappers to make sure they zoom in so that the scale bar reads 20 meters before they try to do any mapping, however there is no scale bar visible on my screen at the moment. The scale at which new people try to map is an important point in my opinion, and I've seen new mappers fail to zoom in enough and then map many buildings as one large building because they couldn't see to do anything different.
=> fix initial height of id-container div to solve scrolling problems

example.env, scripts/install/install_on_debian_10_buster.sh, scripts/install/install_on_ubuntu_18_04.sh
closes #2592 
Verify if the contributor already made a copy of `example.env`, before it was always copying the `example.env` for a `tasking-manager.env` even if the user already had a copy. 
Before:
https://github.com/hotosm/tasking-manager/blob/1b3e39c1c6cdf631257a9464507b5854f083464c/scripts/install/install_on_debian_10_buster.sh#L40
Now:
```sh
if ! test -f tasking-manager.env
then
cp example.env tasking-manager.env
fi
``` 
Export the environment variables. I may be wrong, but when I checked the source code the environment variables weren't being used, so I exported it to use later in the script.
```sh
. ./tasking-manager.env
``` 
That's the main part and why I wanted to improve the script. As mentioned before the script was always creating the database with hard coded user and database …
=> Improvements to install scripts

backend/services/messaging/chat_service.py
Since project chat limits the number of messages per request, is now possible to update the project chat with a new comment within the view. Closes #2487
=> Remove ttl cache in project chat service

backend/services/project_search_service.py
Closes #2593 
Fix `favorited_by_me filter, which was always returning all projects in `PUBLISHED` state.
All the discussion is located in the [issue](https://github.com/hotosm/tasking-manager/issues/2593).
=> Fix projects favorited by me filter

migrations/versions/14340f1e0d6b_.py
This PR fixes two alembic migrations pointing at the same parent.
=> fix migrations of organization and role migrations

backend/models/postgis/interests.py, backend/models/postgis/licenses.py, backend/models/postgis/project.py, backend/models/postgis/user.py, backend/services/interests_service.py, backend/services/project_search_service.py, backend/services/users/user_service.py, migrations/versions/2d6a7ad4e1eb_.py
* Introduce a migration to rename tables:
* `users_license` -> `user_license`
* `projects_interests` -> `project_interests`
* `users_interests` -> `user_interests`
=> Consistency in table names

scripts/aws/cloudformation/tasking-manager.template.js
Closes #2557
After running some load tests on the TM4 instance, I think the following configuration will work well for the release- it should more than handle a user load similar to the current capacity on TM3, with room to improve on after launch. 
Production Capacity (number of instances):
- min 2
- max 9
Autoscaling Tracking Target:
RequestsPerTarget: 500
Cooldown: 300s
The cooldown reduction from 600 should speed up the autoscaling process.
=> Optimize autoscaling for TM4

backend/services/project_search_service.py, frontend/src/components/projectDetail/header.js, frontend/src/components/projectDetail/statusBox.js, frontend/src/components/projectcard/projectCard.js, frontend/src/components/projects/myProjectNav.js, frontend/src/components/teamsAndOrgs/menu.js, frontend/src/hooks/tests/UseMetaTags.test.js, frontend/src/views/project.js
- Resolves #2663
- status filter is not applied if `createdBy` query param is true
- show status on projectCard if it is draft or archived
- improve status box style
=> Fix managedBy, createdBy and status project filters

.circleci/config.yml
part 1 of https://github.com/hotosm/tasking-manager/issues/2686
Fixes privacy policy links, the variable name was incorrect.
In addition, I changed to Environment Variable name for the matomo endpoint to its correct value, `https://matomo.hotosm.org/`
=> Fix privacy policy link variable name

frontend/src/components/editor.js
iD was not behaving well after loaded for the 2nd, 3rd or 4th time, this PR tries to solve it.
=> avoid editorRef redefinition

scripts/aws/cloudformation/tasking-manager.template.js
I created a maintenance page that can give access to users with authentication, but the app was configured to forward the `Authentication` header to the s3 bucket hosting the frontend. S3 doesn't allow this header for Basic Authentication (only AWS type auths), so I have to remove this from the Cloudfront Forwarded Values.
=> Remove authorization header from being forwarded to react app

backend/services/project_service.py, backend/services/validator_service.py
From https://github.com/hotosm/tasking-manager/issues/2559 - fixed validation task lock on multiple projects. User can lock multiple tasks on one project in a single selection.
=> Disable validation task lock across projects

frontend/src/components/taskSelection/action.js
Closes #2601 : 
After mapping task as either of ['BADIMAGERY', 'READY', 'MAPPED'] the variable `lockedTasks` must update. But the function `fetchLockedTasks` which is responsible for the above, is never invoked due to which `Resume Mapping` wasn't working.
Closes #2577 : 
**Initially**, the api calls were as follows : 
- BADIMAGERY: hit `/stop-mapping` and restore the previous status.
- READY: hit `/stop-mapping` and restore the previous status.
- MAPPED: hit `unlock-after-mapping` and unlock it.
Here `/stop-mapping` prevented the updation in status to ['BADIMAGERY', 'READY'] coz it just restored the previous status.
@xamanu @willemarcel please correct me if I missed something or am wrong !
=> Fix resume mapping and task status updation.

frontend/src/components/projectDetail/index.js, frontend/src/components/projectDetail/questionsAndComments.js, frontend/src/components/projectEdit/inputLocale.js, frontend/src/components/taskSelection/action.js, frontend/src/components/taskSelection/actionSidebars.js, frontend/src/components/taskSelection/messages.js, frontend/src/locales/en.json
- add perTaskInstruction info on mapping/validation page
- hide history tab when validating multiple tasks
- format markdown content correctly across all system
=> add perTaskInstructions + handle better multiple tasks validation

backend/api/tasks/resources.py, backend/models/postgis/task.py
From #2320 - instead of returning 404 when there is no activity on a project, let it return 200 with an empty array
=> Handle projects with no mapped task

backend/__init__.py, manage.py, requirements.txt
This PR addresses #2108 by setting up a cron job which runs in background once every 2 hours while the server is up.
=> Run auto unlock operation as background thread

example.env, frontend/src/components/projectCreate/messages.js, frontend/src/components/projectCreate/setAOI.js, frontend/src/config/index.js, frontend/src/locales/en.json
Superseeds #2810 and closes #2808
* Disallow to upload files that are larger than 1MB in the project creation.
* Adjust wording of error message when hitting the file limit
=> Limit upload size of project geometry files to 1MB

migrations/versions/0eee8c1abd3a_.py
during trial migration we came across a project with missing geometry, which caused a migration script to fail. The project is 8475. This fix makes sure the migration doesn't fail in that instance.
=> Add exception for projects mission geom record

backend/models/postgis/project.py
Closes #2670 
Restrict access to the endpoint `/api/v2/projects/<id>/`, based on the following conditions:
- admins can access all draft projects
- org admins can access draft projects of the ones assigned to their organization(s)
- members of a team that has been assigned with project manager status to the project can access a draft project
=> Restrict access to project details for draft projects

backend/services/stats_service.py, frontend/src/components/projectDetail/index.js, frontend/src/components/projectcard/messages.js, frontend/src/components/projectcard/projectProgressBar.js, frontend/src/components/taskSelection/contributions.js, frontend/src/utils/projectCompletenessCalc.js, frontend/src/utils/projectPermissions.js, frontend/src/utils/tests/projectCompletenessCalc.test.js, scripts/database/update-task-stats.sql
Per chat w/ @willemarcel, there is a discrepancy in numbers for a project on TM4 instance.
* Project 31 has a total of 83 tasks - 
* 76 validated
* 2 bad imagery
* 3 mapped
That gets the percentages to - 95% mapped, 91% validated and 2% bad imagery
However the project ID endpoint retruns:
```
"percentMapped": 87,
"percentValidated": 96,
"percentBadImagery": 4,
```
Because  validated  + bad imagery = 100%, contribute button is not enabled on the frontend.
On closer investigation, `update_stats_after_task_state_change` method invokes the `_update_tasks_stats` only if TaskStatus is not in READY, LOCKED_FOR_MAPPING and LOCKED_FOR_VALIDATION. For undo eg: when a BADIMAGERY is set to READY, per current logic this function is not invoked and hence the bad imagery count on projects table never …
=> Update task count on undo

frontend/src/components/teamsAndOrgs/organisations.js, frontend/src/components/teamsAndOrgs/teams.js
- remove organization link from card, as it's not possible to click on the organisation link inside the card and it was breaking the page style when an org doesn't have the url set
- reduce org logo size on card
- show only active managers/members on team cards (related to https://github.com/hotosm/tasking-manager/issues/2832)
=> remove organization link from card + filter active members on team card

backend/models/dtos/project_dto.py, backend/models/postgis/project.py, backend/services/project_admin_service.py, backend/services/project_service.py, backend/services/team_service.py, frontend/src/components/taskSelection/index.js, frontend/src/utils/projectPermissions.js, frontend/src/utils/tests/permissionsToMap.test.js, frontend/src/utils/tests/permissionsToValidate.test.js, tests/backend/unit/services/test_project_service.py
As reported by Ralph, for projects with team permissions on mapping/validation  - admin users were not permitted to lock tasks for validation.
Expected behaviour: users with managerial permissions for a project - admins, org managers, PM team members, author can choose to map/validate tasks irrespective of whether they're part of mapper and validation team.
Permission matrix  for mapping a project between users at various access levels and mapping_permissions set in the backend:
User Access | LEVEL - Only users with intermediate or advanced level | TEAMS - Only team members | TEAMS_LEVEL - Only intermediate and advanced team members
-------------|---------------------------------------------------------|-------------------------------|------------------------------------------------------- …
=> Let users with manage permissions to map/validate

.circleci/config.yml
We can marge this to `master` via release but do not merge to `deployment/hot-tasking-manager` until the correct time during the deployment window. 
We will need to make sure the following envvars in CircleCI are correct before pushing:
```
POSTGRES_DB_PRODUCTION: tm
POSTGRES_PASSWORD_PRODUCTION: *MUST BE ROTATED*
POSTGRES_USER_PRODUCTION: *redacted*
TM_APP_BASE_URL_PRODUCTION: https://tasks.hotosm.org/
TM_APP_URL_PRODUCTION: tasks.hotosm.org
TM_APP_API_VERSION_PRODUCTION: "v2"
TM_CONSUMER_KEY_PRODUCTION: from OSM
TM_CONSUMER_SECRET_PRODUCTION: from OSM
TM_SECRET_PRODUCTION: *MUST BE ROTATED*
TM_EMAIL_FROM_ADDRESS_PRODUCTION: noreply@hotosmmail.org
TM_EMAIL_CONTACT_ADDRESS_PRODUCTION: sysadmin@hotosm.org
TM_SMTP_HOST_PRODUCTION: no change
TM_SMTP_PASSWORD_PRODUCTION: no change …
```
=> Update production stack name for new tm4 stack

manage.py
Per chat w/ @xamanu - updated the `manage.py` method to insert only primary category of interests.
=> project_interests mapping update for just primary category

frontend/src/components/projectCreate/navButtons.js, frontend/src/components/projectCreate/projectCreationMap.js
- Fixes bug that does not render taskgrid on a  basemap change in trim project and set project name steps for project creation.
- Fixes the taskgrid not reset after being clipped or trimmed and **previous** button is clicked.
=> Fixes in project creation view

backend/services/project_search_service.py
Closes #2861. To test this PR, you would need to disable server cache.
**how to test:**
- Using the example db dump.
- Go to explore page.
- Set projects as private. ie
```update projects set private=true where id in (1, 2);```
- You will not see projects 1 and 2.
```update projects set private=false where id in (1, 2);```
- You will see projects 1 and 2.
=> Include private project filter correctly

frontend/src/utils/promise.js
For the next release we would need to modify all catch errors with status code instead of responseText
=> Handle license error with status code

frontend/src/components/taskSelection/imagery.js, frontend/src/components/taskSelection/tests/imagery.test.js, frontend/src/utils/openEditor.js
- Accept TMS urls starting with `tms:https://` (the same to WMS and WMTS) as valid urls
- Avoid imagery info area to have more than one line
- Launch JOSM with the imagery URL as title of the layer
=> Improvements to imagery handle

backend/services/messaging/smtp_service.py
This causes to be considered as an html tag, making it not being rendered
=> Replace <> within email contact form template

backend/api/campaigns/resources.py, backend/api/comments/resources.py, backend/api/interests/resources.py, backend/api/licenses/actions.py, backend/api/notifications/actions.py, backend/api/notifications/resources.py, backend/api/organisations/campaigns.py, backend/api/organisations/resources.py, backend/api/projects/actions.py, backend/api/projects/campaigns.py, backend/api/projects/favorites.py, backend/api/projects/resources.py, backend/api/projects/teams.py, backend/api/system/applications.py, backend/api/system/image_upload.py, backend/api/tasks/actions.py, backend/api/tasks/resources.py, backend/api/teams/actions.py, backend/api/teams/resources.py, backend/api/users/actions.py, backend/api/users/resources.py, backend/models/postgis/project.py, backend/services/project_admin_service.py, backend/services/users/authentication_service.py
In line with #2894,
* updated the project api resources file to fetch authenticated_user_id into a var, rather than calling the TMDecorator Object everytime we need user id
* Within the permissions check method, change the checking order. Now we check for all the four types of permissions - is_admin, is_author, is_team_manager, is_org_manager. Instead get on team and org manager check only if the user is not an admin or author. Here we save some repeated querying and make the process faster
=> Updates to project edit permissions check

scripts/aws/cloudformation/tasking-manager.template.js
According to https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html this will compress javascript files so long as the viewer request header contains `Accept-Encoding: gzip` and the following factors are true:
- The file must be of a type that CloudFront compresses.
- The file size must be between 1,000 and 10,000,000 bytes.
- The response must include a `Content-Length` header so CloudFront can determine whether the size of the file is in the range that CloudFront compresses. If the `Content-Length` header is missing, CloudFront won't compress the file.
- The response must not include a `Content-Encoding` header.
=> Enable file compression in Cloudfront Behavior

backend/models/postgis/task.py
closes #2922 a missing field in the backend causes an invalid date in the frontend...making the timer not being rendered
=> Include last updated field in locked tasks dto

frontend/src/components/projectCreate/projectCreationMap.js
This avoid frontend crash when a mapbox token is not provided.
=> Validate mapbox token on basemap change in project creation

scripts/aws/cloudformation/tasking-manager.template.js
@ramyaragupathy noticed that the tasking manager logs on AWS Cloudwatch was being overwritten by the gunicorn logs (stemming from #2939 )
Renamed the gunicorn log stream name to have a separate stream file.
=> Rename gunicorn access log filename

frontend/package.json, frontend/src/components/editor.js, frontend/src/utils/openEditor.js, frontend/src/utils/tests/openEditor.test.js
- Update iD editor to 2.18.0-beta-1
- Fix problem with changesetComment (Resolves #2650 )
- Only load imagery on iD and JOSM if `project.imagery` contains 'http'
=> update iD editor and fix problems with comments and imagery

backend/models/postgis/project.py, backend/services/users/user_service.py
From #2824 - 
updated the query for 
* project stats section
* user stats
* user stats for each project
Sample from project stats endpoint:
With timestamps from simultaneously locked tasks | after the query update to remove timestamps from tasks locked together
----------------------------------------------------|--------------------------------------------------------------------------
totalValidationTime: 463873 </br> totalTimeSpent:965400 </br> averageMappingTime: 524 </br> averageValidationTime: 2712 </br>| totalValidationTime: 425268 </br>totalTimeSpent: 926795 </br>averageMappingTime: 524 </br> averageValidationTime: 2486
=> Modify query to remove timestamps from simultaneously locked validation tasks

scripts/aws/cloudformation/tasking-manager.template.js
Closes #1454 
Adds a tag to the autoscaling group to propagate the stack name to the EC2 instance name.
=> Add Name tag to EC2 instances

.circleci/config.yml
As the build is the step that takes more time, I moved it to after the frontend tests, so we can have a failing test result faster.
=> move frontend build to the end of frontend tests

frontend/src/components/taskSelection/footer.js
In https://tasks-stage.hotosm.org/projects/6489/ the "Select another project" button isn't redirecting. It happens because JOSM is the only editor possible and it's checking if JOSM is open instead of redirecting. This PR fixes it.
=> change order of task action evaluation

.circleci/config.yml
fix indentation in YAML config for circleci to get filters working
properly.
=> Fix indentation in circleci YAML config

Makefile, docker-compose.override.yml, docker-compose.yml, scripts/docker/Dockerfile.backend, scripts/docker/Dockerfile.frontend, scripts/docker/Dockerfile.frontend_development
For tasking manager 4, since frontend and backend are separated within the project, this PR makes two dockerfiles with their own runtimes and environments. Also, the docker-compose file includes a reverse proxy configurable within the same file.
**Backend:** Image size reduced from 1.0Gb to 400Mb
- Modified python runtime from buster to python-3.7-alpine.
- main command set to gunicorn.
**Frontend:**
- The development dockerfile comes with node.
- The production dockerfile compiles the source code to a bundle which is served by nginx.
=> Docker improvements

tests/backend/integration/services/test_project_search_service.py
Trying to make the test less brittle across Linux platforms by using `assertAlmostEqual` for floating point comparisons to prevent failures like this:
```
======================================================================
FAIL: test_get_area_from_3857_bbox (tests.backend.integration.services.test_project_search_service.TestProjectSearchService)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/src/tasking-manager/tests/backend/integration/services/test_project_search_service.py", line 150, in test_get_area_from_3857_bbox
self.assertEqual(expected, 28276407740.2797)
AssertionError: 28276407740.2798 != 28276407740.2797
======================================================================
FAIL: …
```
=> Fix some floating point comparisons to be less brittle

backend/api/organisations/resources.py, backend/api/teams/resources.py, backend/models/dtos/organisation_dto.py, backend/models/postgis/organisation.py, backend/services/organisation_service.py, backend/services/team_service.py, frontend/src/components/formInputs.js, frontend/src/components/projectEdit/metadataForm.js, frontend/src/components/projectEdit/teamSelect.js, frontend/src/components/projects/myProjectNav.js, frontend/src/components/taskSelection/index.js, frontend/src/hooks/UseTagAPI.js, frontend/src/store/actions/auth.js, frontend/src/views/organisations.js, frontend/src/views/project.js
Closes #3177 . Included a request parameter **abbreviated**. When set to True, hides information according to the given endpoint.
**/v2/organisations/:** Hides managers for each organization.
**/v2/organisations/<id>:** Hides managers, teams and projects associated to the organization.
**/v2/teams/:** Hides team members.
**/v2/teams/<id>:** Hides team members, team projects and organization projects.
=> Include abbreviated response for teams and orgs endpoints

backend/services/project_search_service.py
closes #2869 .
Search for projects based on user organization moved to global search and removed union query. This fixes the bug related to sorting.
=> Search projects without tables union for correct sorting

backend/services/team_service.py, frontend/src/components/projectEdit/teamSelect.js, frontend/src/components/taskSelection/index.js, frontend/src/store/actions/auth.js
Per chat w/ project managers for 8999 - we figured out that with the new query parameter `omitMemberList`, private team details are not appended for a user since permissions check is overridden because of a conditional placement check.
As a result if a user is a member of a private team and if `omitMemberList=True` then team data is not appended to the final list, thereby interrupting the user from contributing to the project. This fix updates the logic in team_service.
=> Handle member omission for private teams

backend/services/team_service.py, frontend/src/components/projectEdit/teamSelect.js, frontend/src/components/taskSelection/index.js, frontend/src/store/actions/auth.js
While fetching teams, exclude membership check after the first match with the current user ID. If this check is repeated the flag is overwritten per the status of last member check, thereby affecting DTO append for private teams
=> Skip membership check after first match

.circleci/config.yml
All backend tests are skipped because we don't have a test db configured (https://github.com/hotosm/tasking-manager/issues/3230). Also, it seems the tests are outdated and are not reliable anymore.
I'm disabling it because someone could think that the code is being tested.
=> disable backend tests on circle-ci

frontend/src/views/organisations.js
Per chat w/ @russdeffner - removing `omitManagerList` query parameter from org fetch so that manager list is displayed in cards
=> Include manager list for manage orgs page

backend/__init__.py, backend/api/notifications/resources.py, backend/models/postgis/notification.py, backend/services/notification_service.py, frontend/src/components/header/notificationBell.js
This PR modifies backend and frontend to get and update unread messages.
- Notification model is updated to check new messages that were created after the value set within the **date** field.
- Created an API endpoint that updates the **date** field in the notification model.
- The frontend checks if the user has not pressed the notification bell. Given the event that the user presses the bell icon, there is a request to the backend to update the notification date field.
=> Notifications enhancements

backend/models/postgis/project.py
This avoids not-null constraint error for project geometry and centroid included in new release
=> Do not set geometry and centroid as None when cloning projects

backend/models/postgis/project_chat.py, requirements.txt
Per chat w/ @willemarcel - some of the markdown features are not supported with bleach methods. Here we're testing the possibility of including images, breaks in the project comment.
=> Complete markdown support in project chat

backend/__init__.py
As it causes a lot of errors on the logs and also is confusing to maintain those views on the project without using it effectively.
Added a redirect to the heartbeat, instead.
=> Remove frontend views from backend server

backend/models/postgis/project.py
@ramyaragupathy I found one of the reasons why some projects received a country name in another language: https://nominatim.org/release-docs/develop/api/Reverse/#language-of-results
If we don't pass the language it will return the content of the "name" tag on OSM. You can confirm querying a location in Norway.
=> force nominatim to return results in English

backend/api/notifications/resources.py, backend/services/messaging/message_service.py, frontend/src/components/header/notificationBell.js, frontend/src/components/notifications/notificationResults.js, frontend/src/hooks/UseInboxQueryAPI.js, frontend/src/store/reducers/notifications.js
Ordering notifications by `read` status to load it on the notification bell caused the date ordering to be inconsistent:
So I added a status filter on the endpoint and updated the frontend to use that query param, so now the notification bell is more consistent.
=> add notification status filter and use that query on the notification bell

frontend/package.json, frontend/src/assets/styles/_datepicker.scss, frontend/src/assets/styles/index.scss, frontend/src/components/projectCard/dueDateBox.js, frontend/src/components/projectCard/projectCard.js, frontend/src/components/projectDetail/infoPanel.js, frontend/src/components/projectEdit/descriptionForm.js, frontend/src/components/projectEdit/messages.js, frontend/src/locales/en.json, frontend/src/views/projectEdit.js, frontend/yarn.lock
Closes #3132 
This Pull Request is part of the [issue of adding and updating fields according to Organised Editing Guidelines](https://github.com/hotosm/tasking-manager/issues/3132)
Add project `due_date` field in frontend.
=> Add project due date

docs/contributing-code.md
I could not find any guidelines on updating the documentation, so I'll try to update any outdated parts when I stumble upon them and feel comfortable that the update is correct and relevant.
The PR contains very minor changes to the frontend guidelines. It currently recommends using JSLint, which produces a rather large amount of warnings/errors,
which can be confusing to someone new to the project (e.g., me 😳 ).
ESLint/Prettier is the [current default create-react-app approach](https://create-react-app.dev/docs/setting-up-your-editor/).
As always, add/remove/change/discard/comment on this PR, whichever suits best.
=> Update frontend guidelines for ESLint and prettier

backend/models/postgis/project.py
To test, try saving a project with null campaigns and this should get through
=> Handle null campaigns in PATCH

scripts/docker/Dockerfile.backend
=> Add timezone setting

scripts/docker/Dockerfile.backend, scripts/docker/Dockerfile.frontend
Fixes #3638 and greatly improves existing Dockerfiles: images are way smaller, faster to recreate and some backend options (like workers/threads/timeout) can be also set by using environmental variables.
The newly added variables for the backend could be added to the compose file too (commented?), to make them more visible to the user.
=> Improve dockerfiles

.circleci/config.yml
Despite the branch name, the primary feature here is the improvement on the circleci config. Using [contexts](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-context), we simplify the circleci script. The context will be set on CircleCI for each deployment (so far only for staging frontend, hence WIP) removing the need for most of the parameters, except the stack name. CircleCI does not allow us to use the reserved "name" key for the job parameters. 
Incidentally this PR will also fix the missing frontend environment variable for Sentry integration by simplifying the envvar setting. We can use `${STACK_NAME}` for the frontend and backend sentry `environment` parameter.
=> Simplify CircleCI config and fix sentry envvar setting

backend/models/postgis/project.py
Remove Potlatch and FieldPapers from the default values, as they are not used often.
=> Set default mapping/validation editors as iD, JOSM and custom

example.env
- Add the ampersand (&) to the ID Editor URL to ensure that the frontend tests are not affected.
=> Comment out the iD Editor URL on example.env

frontend/src/components/projectEdit/customEditorForm.js
Refactor text inputs in the CustomEditorForm
**Steps Taken**
- Create a CustomEditorTextInput component
- Add conditional rendering of the input label
- Refactor name and URL inputs using the new component
=> Refactor name and URL CustomEditorForm inputs

frontend/src/views/taskAction.js
- Edit a project and set the Per Task Instructions in another language apart from English.
- Switch your TM settings to that same language
- Lock a task for mapping or validation
The specific task instructions section should show information on that other language, not in English.
- With TM language in Spanish 🇪🇸 :
- TM in English 🇬🇧
=> Load perTaskInstructions in the user locale

frontend/src/components/projectEdit/metadataForm.js, frontend/src/components/projectEdit/settingsForm.js
- Styles the checkbox inputs in the Project Edit section to match the ones in the Notifications. 
**Issues:**
Fixes #3799 
**Screenshot:**
- Settings Form: Editors for mapping and validation
- Metadata Form: Mapping types
=> Style project edit section checkbox inputs

.circleci/config.yml
This branch will be useful for testing changes that could affect the server or database performance without merging into `develop`, or for testing infrastructure changes. 
Other than this time, the `staging-test` branch should not generally be merged into `develop` branch. but any feature tested on this branch should be merged upstream to `develop` directly after testing.
=> Add staging-test branch to staging deployment

backend/api/organisations/campaigns.py, backend/models/postgis/campaign.py, backend/services/campaign_service.py, backend/services/organisation_service.py
This PR refactors the Campaign and Campaign Service static methods.
**Steps Taken:** 
- Add a new static method in the Organisation Service class to get all the organisations under a campaign
- Add a new static method to convert a collection of campaigns to a List DTO
- Move replicated static methods from the Campaign model to the Campaign Service class
- Refactor methods to make use of newly added ones.
**Some of the URLs to test:**
1) Via Postman. Method: `GET`. 
- `http://127.0.0.1:5000/api/v2/campaigns/`
- `http://127.0.0.1:5000/api/v2/campaigns/<int:campaign_id>/`
- `http://127.0.0.1:5000/api/v2/organisations/<int:organisation_id>/campaigns/`
- `http://127.0.0.1:5000/api/v2/projects/<int:project_id>/campaigns/`
2) Frontend
- …
=> Refactor Campaign Service and Campaign static methods

backend/models/postgis/user.py
=> Use .contains instead of .ilike on user filtering

frontend/package.json, frontend/src/utils/internationalization.js, frontend/yarn.lock
Tasking Manager was failing on some browsers like Safari 13 and below. With the `Intl.Locale` polyfill we expand the browser support.
=> Polyfill Intl.Locale when needed

frontend/src/components/svgIcons/index.js, frontend/src/components/svgIcons/info.js, frontend/src/components/taskSelection/action.js, frontend/src/components/taskSelection/actionSidebars.js, frontend/src/components/taskSelection/messages.js, frontend/src/hooks/tests/useReadTaskComments.test.js, frontend/src/hooks/useReadTaskComments.js, frontend/src/locales/en.json, frontend/src/network/tests/mockData/taskHistory.js
What does this PR do?
Resolves #3507 
Steps taken:
- Create a custom hook for conditional render of request to read comments if the task was previously invalidated and has comments to guide the mapper.
Screenshot:
=> Request users to view task history comments

migrations/versions/7937dae319b5_.py
Per discussion w/ @willemarcel - setting up a migration to move existing country names to English. Backend changes have already been made to fetch English names during project creation.
=> Update existing country names for projects

frontend/src/components/formInputs.js, frontend/src/components/taskSelection/action.js, frontend/src/components/taskSelection/actionSidebars.js, frontend/src/components/taskSelection/messages.js, frontend/src/components/taskSelection/taskActivity.js
**What does this PR do?** 
Resolves #3977 
**Screenshots:**
- Comments only
- State Changes only
=> Allow users to filter task history comments and state changes

backend/models/postgis/task.py
The task history was ordered by id, what lead to errors sometimes. Link: https://tasking-manager-tm4-production-api.hotosm.org/api/v2/projects/9507/tasks/1832/
=> Order task history by action_date instead of id

backend/services/messaging/message_service.py, backend/services/messaging/smtp_service.py, backend/services/messaging/templates/message_alert_en.html
* Modified `send_message_after_chat` to send messages to contributed and favorited users of a project when a comment is left in project chat
* Improved `send_message_after_chat` function to continue sending messages even if there are no usernames mentioned
* Updated the html message template
=> Ensure mappers receive notifications on project chat

scripts/aws/cloudformation/tasking-manager.template.js
In order to allow for non-hotosm urls (such as tasks.teachosm.org) in the cfn template, we add a condition for the url parameter to check if its a hotosm.org domain. We will not create the Route53 record in the case that it is an external url. 
In this case currently it only works when we also control the ssl certificate in ACM, so it is not fully generalized. that should come with future development. 
@willemarcel I would like to test this with `staging-test` before merging.
=> Add condition for custom URL in cfn template

example.env
It looks like the rest of the app is looking for "tasking-manager.env", but the comment in the env file says "Copy to 'example.env'".
=> Correct the setup documentation in example.env

example.env
Noticed that without setting this variable the system won't send email, so I made its status a bit more clear.
=> Pointing out that email won't send without a from address

frontend/src/components/taskSelection/action.js, frontend/src/components/taskSelection/actionSidebars.js, frontend/src/hooks/UseDisableBadImagery.js, frontend/src/hooks/UseReadTaskComments.js, frontend/src/hooks/tests/UseDisableBadImagery.test.js, frontend/src/hooks/tests/UseReadTaskComments.test.js, frontend/src/network/tests/mockData/taskHistory.js
In the case a task was marked as bad imagery and a validator reverted it to ready, we only show the option to set the task again as bad imagery to advanced users. So beginners and intermediate can not mark it as bad imagery again.
Resolves #4082
=> Hide the option to mark task as BADIMAGERY if it was previously reverted

backend/models/postgis/utils.py, backend/services/grid/split_service.py, frontend/src/components/taskSelection/actionSidebars.js, frontend/src/components/taskSelection/messages.js, frontend/src/locales/en.json
=> Forbid to split tasks with zoom level >=18 or area < 25k m²

frontend/src/components/taskSelection/footer.js, frontend/src/components/taskSelection/index.js, frontend/src/components/taskSelection/lockedTasks.js, frontend/src/components/taskSelection/messages.js, frontend/src/locales/en.json
Resolves https://github.com/hotosm/tasking-manager/issues/4128
- **Case 1:** Select the tasks mapped by a user:
Although it shows "Validate 16 selected tasks" on the button, with that PR we are excluding the tasks that are not on the mapped status and lock only the mapped ones.
- **Case 2:** If the selected user has not tasks on mapped status, it will show an error message
=> Exclude tasks that are not on mapped status, when locking tasks of a user

backend/api/tasks/statistics.py
When an exception is known, we don't need to log it, as it is not a bug in the software and shouldn't generate an entry on Sentry
=> Don't log known exceptions on tasks stats endpoint

docker-compose.override.yml, scripts/docker/Dockerfile.frontend, scripts/docker/Dockerfile.frontend_development
Fix #4009.
Docker does not support the `env_file` parameter at build time, so the variables have been copied like it has been done with `TM_APP_API_URL` and the defaults too. It is a bit redundant and setting those frontend arguments in `tasking-manager.env` has no effect. This PR does not change how those variables are handled in the Docker frontend, it just adds two more to allow the user to set them.
To avoid such kind of redundancy, it would be enough to rename `tasking-manager.env` as `.env`, but that would be a major change which is out of the scope of this PR.
=> Add Docker support for additional frontend parameters

frontend/src/components/projectCreate/index.js
When we imported a file and enabled the "Arbitrary tasks" option, it was keeping that option active even if we reset the AoI and draw a new one. That PR fixes it by resetting the "Arbitrary tasks" option when clicking on reset
=> Reset arbitrary tasks option when clicking the Reset button

frontend/src/components/projectCreate/index.js, frontend/src/components/projectCreate/navButtons.js, frontend/src/components/projectCreate/review.js, frontend/src/components/projectCreate/setTaskSizes.js, frontend/src/components/projectCreate/trimProject.js
After trimming the tasks grid on the Step 3 of project creation and going back to step 2, the number of tasks were not being updated. This PR fixes it.
=> Rename tasksNo to tasksNumber and update it when going back to Step 2

frontend/package.json, frontend/src/components/projectCreate/review.js, frontend/yarn.lock
This will reduce the size of the project's task grid and improve TM performance.
=> Truncate Project AoI and Task Grid to 6 decimal places

frontend/src/components/teamsAndOrgs/orgUsageLevel.js
It was showing the predicted tier instead of the next tier.
=> Fix tier information on progress bar tooltip

backend/services/stats_service.py, backend/services/validator_service.py
Update the TaskStatus list so that tasks that have been validated already are not locked for validtation again. This could help with the project statistics update on the backend
=> Exclude  already validated tasks to be locked for validation again

frontend/src/views/projectStats.js
I am having a CORS error on Firefox when accessing some projects' stats page. As useFetch was designed to deal only with local endpoints, I'm switching it to use another fetch function.
=> Avoid CORS errors when fetching osm stats api

Dockerfile
- Solve for the broken auto builds caused by Docker's new rate-limiting by pulling the python base image from quay.io.
=> Replace TM Dockerfile base image

scripts/aws/cloudformation/tasking-manager.template.js
- Cloudfront for TeachOSM points to tasks.teachosm.org
- Backend API points to tasking-manager-tm4-teachosm.hotosm.org
- Different domains need different certificates from ACM
This commit splits the single SSL Certificate Identifier variable
into separate Frontend and Backend SSL Certificate ID variables.
Relevant cfn parameter JSON file in S3 has been modified to include
two new parameters `FrontendSSLCertID` and `BackendSSLCertID`
=> Split up Frontend and Backend certificate manager certificates

frontend/src/utils/openEditor.js
Change needed after #4404 
It's only supported by JOSM 17655 or superior (https://josm.openstreetmap.de/ticket/20660)
=> Load imagery on JOSM using its id instead of the url

requirements.txt
Based on security alert we received updated the following dependency versions:
* Bleach 3.2.1 -> 3.3.0
* Jinja2 2.11.2 -> 2.11.3
These libraries impact the chat and the api-docs section. I don't see any issues with the version upgrade.
=> Bleach & Jinja version update

frontend/src/components/projectEdit/descriptionForm.js, frontend/src/components/projectEdit/inputLocale.js, frontend/src/components/projectEdit/localeOption.js, frontend/src/components/projectEdit/messages.js, frontend/src/components/projectEdit/tests/localeOption.test.js, frontend/src/locales/en.json, frontend/src/views/projectEdit.js
=> Modify language switch on project edit page

frontend/src/components/taskSelection/footer.js
Resolves #4464 
As the `lockTasks` function is a bit complex, I decided to add an `isPending` state instead of using the `useAsync` hook.
=> Show loading indicator when locking tasks to map or validate

backend/config.py, example.env
Problem:
There's no straightforward way to prevent PostgreSQL password 
from being displayed in AWS console (our current application host).
This is a shortcoming of AWS Cloudformation and available options
for AWS ECS `ValueFrom` field.
Solution:
Instead of trying to parse the secrets manager entry and pick specific 
parameters in the CloudFormation template, we do the parsing in 
config.py and pass the whole JSON stored in secrets manager. 
This is agnostic of AWS and can be extended to any cloud provider or
server host in the future.
=> Parse new database connection parameters

frontend/src/assets/styles/_extra.scss
I have noticed that in the production instance, the link to the "Improve this map" has been shown, so I improved the CSS rule to hide it.
=> Add new CSS rule to hide "Improve this map" link

backend/api/projects/resources.py, backend/models/postgis/project.py, frontend/src/components/projectEdit/settingsForm.js, frontend/src/views/projectEdit.js
=> Avoid errors when changing default locale of projects

frontend/src/components/taskSelection/taskList.js
How to reproduce the bug: go the task selection page, click on a task on the map, then click on a filter like "unavailable", start typing some letters on the search field until the result got empty. The application will break, or you'll see some errors messages on the console.
This PR fixes the problem by improving the logic on when the pagination should be reset.
=> Improve logic of reset pagination in the TaskList component

frontend/src/components/projectEdit/priorityAreasForm.js
To test: go to the priority areas form, zoom the map to some region, press the "Draw polygon" button, draw something. The map view should remain on the same place all the time.
=> Don't change map bounds when the user press the "Draw polygon" button

.circleci/config.yml
via https://www.opsgenie.com/docs/integrations/circleci-integration
This will set up the integration with OpsGenie so we can pass CI alerts such as build failures through that platform.
=> Add opsgenie integration to CircleCI to push alerts there

backend/services/messaging/message_service.py
Resolves #3902
With that change, the `#managers` hashtag will notify the project author and the members of the teams with Project Management permission on the project. The organization managers will not receive that notification any more.
=> Remove Organization Managers from notifications triggered by #managers

frontend/src/components/projectEdit/actionsForm.js
This adds the loading indicators and disabled button look to the action buttons on the "Edit Project" page. Access this page by navigating from `Manage > Select a project > Edit Project > Actions`
Resolves #4462
I closely referred to the code written in the PR [here](https://github.com/hotosm/tasking-manager/pull/4447/files) which was very helpful as advised by @willemarcel, and used the `useAsync` hook to initiate the API calls. Once this was done for 1 button, the others were straightforward to implement.
I also did a minor renaming of some local functions within the Modal components so that the naming follows those `useAsync` functions in `actionSidebars.js`.
* Get access to edit projects in the staging environment from a member of the HOTOSM team
* Run `yarn start` in the `./frontend` …
=> Show loading icon on buttons during edit project API requests

frontend/src/components/taskSelection/action.js
This ensures that task IDs on the Validate Multiple Tasks page are sorted in ascending order for a better UX. This PR performs the sort on both the title and the `TaskValidationSelector` components, so that they are aligned.
Resolves #4689
Sorting is done on the task IDs array in `action.js` since that is the array that gets passed into all child components. I thought that placing the sort function there would make it more convenient in the future, so you don't need to worry about having to sort individual child components on their own anymore (the array is sorted, just display).
(Sidenote) Javascript's `Array.prototype.sort` does a lexicographic sort by default ([docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)). Since the `tasksIds` …
=> Fix task IDs are not sorted on multiple tasks validation sidebar

frontend/src/components/projects/myProjectNav.js
This PR's main goal is to solve the linked issue by creating a new status filter called "Managed by Me", so that users can select projects managed by them that have been archived. Currently, there's no way to do so because "Archived" and "Created by Me" filters are mutually exclusive.
We also improve the status filter toggling behaviour by making "Active", "Draft" & "Archived" filters separate from "Created by Me" and "Managed by Me". These filters have also been tested on mobile-sized screens to make sure they aren't awkwardly aligned.
_(Beware: Unfamiliar with business logic)_
Feel free to comment if I might have misunderstood the requirements here. I think it's easier to implement what I think should be the logic in code, and then work on this from here as a baseline.
Fixes #3829 
* …
=> Improve status filters by making them independent on manage project page

frontend/src/components/comments/commentInput.js, frontend/src/components/taskSelection/action.js, frontend/src/components/taskSelection/actionSidebars.js, frontend/src/components/taskSelection/taskActivity.js, frontend/src/utils/getTaskContributors.js, frontend/src/utils/tests/getTaskContributors.test.js
=> Autofill OSM usernames in comment box based on project contributors

frontend/src/components/contributions/myTasksNav.js
=> Fix responsivity and improve display logic for the buttons on My Tasks

frontend/src/components/header/index.js
OSM allows up to 255 characters in the username. It's better to limit the space and avoid the style from breaking
=> Limit space available to usernames on the header

frontend/src/components/dropdown.js
This PR updates any internal link within a Dropdown component to use `@react/router`'s `navigate` instead of a `Link`. Instead of having to click on the text of the link, a user can just click the "box" that it lives in
(must click the text)
(can click the surrounding area)
Closes #4781
=> Update internal links in Dropdowns to allow clicking on the entire span

frontend/package.json, frontend/yarn.lock
This PR updates the version of iD to 2.20.2, which will fix the connection to Maxar Premium, among other improvements. 
fixes #4910 , #4895, #4846
=> Update iD version to fix Maxar imagery

frontend/src/App.js, frontend/src/components/banner/index.js
Per Russ, I've created a banner for the HOT Summit to add to the tasking manager. I'm not sure if this should be merged upstream or if there is a separate deployment for the HOT-specific TM. 
First time a user visits the site:
Hiding behind that first banner is information about the summit:
In the past, we've had issues with temporary banners not retaining user's close preference and getting annoying; based on brief testing, the browser seems to hold the preferences since I mimicked the tracking banner's browser storage.
I originally wanted to do a broader solution based on a database table for announcements, but wasn't able to get that finished up in time. That may come down the road.
=> Add second banner for summit

frontend/src/components/teamsAndOrgs/tests/orgUsageLevel.test.js
CircleCi was failing due to a failed JS test. I'm not sure exactly why this particular test started failing all of a sudden but it seems the reason is because the specific check was using `getAllByText()` which gets all elements whose **entire** content is "Low". As the second element with "Low" in it had full content of "Actions remaining on the Low tier" it wasn't being caught by the function. 
Assuming the purpose of this check is to find the "Low"'s circled in this image, this fix should work:
=> Fix for failing test/Unblock CircleCI

.circleci/config.yml
The Docker images currently used for CircleCI will be deprecated on Dec 31, 2021. This simply updates the usage as stated by CircleCI
Closes #4950
=> Update CircleCI image namespace 

.circleci/config.yml
Simple change to switch the name of the deployment jobs to be more descriptive:
**frontend** => `frontend-staging`/`frontend-production`
**backend** => `backend-staging`/`backend-production`
closes #4952
=> Update CircleCI job names for deployments

backend/services/mapping_service.py, tests/backend/helpers/test_helpers.py, tests/backend/integration/models/postgis/test_project.py, tests/backend/integration/services/test_mapping_service.py, tests/backend/unit/services/messaging/test_template_service.py
The main purpose of this PR is for fixing the API itself but it also adds a test for `reset_all_bad_imagery()` and fixes a few broken tests.
As stated in issue #5011, the API was incorrectly changing  resetting all tasks for **ALL PROJECTS** in the instance. It may be worth someone on the HOT tech team to make sure there aren't any severe ramifications of this API being used.
Closes #5011
=> Fix reset-all-bad-imagery API

docs/contributing.md
I have now simplified the labels list.   As discussed,  I have updated the contributing guidelines to reflect the changes and explain the different ways in which people can contribute.
The plan is to keep this page up to date with any changes/updates as we continue the collaboration with the collective.
=> Updating contributing guidelines

.circleci/config.yml
We were not getting OpsGenie integration working, so this should fix it.
=> Enable OpsGenie webhook by fixing yaml syntax

.circleci/config.yml
This update to the CircleCI script slightly changes how files are updated in the static aws s3 bucket that hosts the frontend. We will now be explicitly adding headers to all files for Cache-Control, according to (these docs)[https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html#expiration-individual-objects]. All files will be cached with a long max-age, except for html files which will not be cached. This should prevent the missing translation errors that were presented when we tried to deploy v4.4.13. 
I will be testing on tasks-test today and then will move this PR from WIP to ready to review.
=> Do not cache html files in the browser

frontend/package.json, frontend/src/components/rapidEditor.js, frontend/src/components/taskSelection/action.js, frontend/src/components/taskSelection/actionSidebars.js, frontend/src/components/taskSelection/messages.js, frontend/src/store/actions/editor.js, frontend/src/store/reducers/editor.js, frontend/yarn.lock
There was a problem reported with the RapiD integration when a user would attempt to switch editors from RapiD to iD when the user still had unsaved edits (#5025)
This PR does 3 main things to solve this issue:
1. Uses the `UnsavedMapChangesModalContent` component to show an alert if a user still has unsaved edits and tries to switch editors
2. To make the actual component switch more performant, I changed how the editor switch is handled. Before, if you switched between RapiD and iD, it would reload the entire page; now it will only reload the single editor components.
3. To allow (2) to happen, I had to add a RAPIDCONTEXT to the redux store so the contexts don't get confused during the switch since they have slightly different values in their contexts.
Closes #5025
=> Handle switching editors with unsaved edits

frontend/src/components/taskSelection/footer.js
#5096 solves the issue in case of reloading the editor. i.e. when the user has already locked a task, but JOSM not loading OSM data was present while starting an editor also. i.e. while locking a task for mapping. This PR fixes the latter issue by not reloading the window if JOSM is selected as editor while locking a task for mapping.
=> Fix JOSM doesn't load OSM data when attempting to map a task

backend/services/users/user_service.py
Currently, user task stats is being calculated from the task_history table.
This PR fixes #3895 by adding a filter to count distinct rows by project_id, task_id, and action_text so that the same action on a task of the project cannot be counted more than once while calculating user tasks stats.
=> Fix user tasks stats

frontend/src/components/header/index.js, frontend/src/components/header/tests/menuItens.test.js
If the SERVICE_DESK env var wasn't configured, it was generating a wrong link. This PR makes that navigation link optional to each instance.
=> Only show SERVICE_DESK link if variable is configured

frontend/src/utils/htmlFromMarkdown.js, frontend/src/utils/tests/htmlFromMarkdown.test.js
Enable embedding YouTube videos in project's description and instructions. The sintax is `::youtube[video-id]`, it needs one line of spacing from other content (both up and down) to work.
**Project editing:**
**Project task's page:**
=> Enable adding YouTube videos with the ::youtube[] markdown tag

frontend/src/views/teams.js
Closes #2334 
Appends logged in user details to the members' state and renders that rather than updating state with an API call.
=> Update team members list when joining or leaving

frontend/src/components/taskSelection/action.js, frontend/src/components/taskSelection/actionSidebars.js, frontend/src/components/taskSelection/lockedTasks.js, frontend/src/components/taskSelection/messages.js, frontend/src/components/taskSelection/tests/lockedTasks.test.js
If I'm trying to map a task in Project X, but I have a task locked in Project Y, I'd have to unlock the task in Project Y first to map the task in Project X. After unlocking the task in Project Y, there wasn't an option to be redirected to Project X.
This PR adds a checkbox input field that can be toggled to be redirected to Project X after unlocking the task in Project Y.
=> Add checkbox to redirect to previous project after unlocking task in another project

frontend/src/components/header/index.js, frontend/src/components/menu.js, frontend/src/components/teamsAndOrgs/menu.js, frontend/src/components/teamsAndOrgs/messages.js, frontend/src/components/teamsAndOrgs/tests/menu.test.js, frontend/src/components/userDetail/headerProfile.js
This PR does the following two things:
- Improves the logic to calculate if a tab route is currently active.
- Adds an 'Overview' tab to the management section for an overall consistent navigation landing experience.
**Improves the logic to calculate if a tab route is currently active.**
When you click on the 'My Contributions' navigation menu on the header, you can see that the active tab indicator (the underline thingy) below 'My Contributions' and 'My Stats' is present, which is correct.
But for other tabs, the indicators were missing. You can see that the indicator on 'My Contributions' on the navbar gets removed when you navigate to other tabs. The 'Projects' tab doesn't show any indicator at all. 
Fixed:
**Adds an 'Overview' tab to the management section for an overall consistent …
=> Fix active nav bar and tab indicator

backend/services/project_search_service.py
This PR fixes #5118 by removing special characters found on searched text as some of the special characters work as text search operators in Postgres which leads to an error  [more info](https://github.com/hotosm/tasking-manager/issues/5118#issuecomment-1120673593).
=> Handle special chars in project search text

frontend/src/components/comments/commentInput.js
Textarea outline for the comment textarea in validation status section is displaced. 
This PR fixes that.
=> Fixed conditionals for commend textarea outline

frontend/src/components/taskSelection/map.js
Closes #3512 
Canvas size has been fixed but seems to still have issues with the project boundary not being zoomed as expected occasionally though. The previously small map canvas would look like the below.
But it should have looked like this
Seems to be a known [issue](https://github.com/mapbox/mapbox-gl-js/issues/3265) in mapbox-gl-js
=> Resize map canvas on map load

frontend/src/views/project.js
The project not found error, like on the screenshot below, is being shown even when project detail loads successfully. This PR fixes it.
.
=> Fix logic to not show error on project detail page

example.env
`TM_ORG_PRIVACY_POLICY_URL` shouldn't have `http://` or `https://`, but the comment is misleading.
=> Improve comments on .env

frontend/src/locales/en.json, frontend/src/views/messages.js, frontend/src/views/projectEdit.js
Closes https://github.com/hotosm/tasking-manager/issues/3143
The message is shown on the left bottom side of the screenshot above. Users won't be able to save the project until a team is assigned.
=> Display message when project's mapping/validation permissions are set to team only but no team is added

frontend/src/components/homepage/mappingFlow.js
This PR adds a fix to make the heights of cards in the mapping flow section consistent. It also removes the whitespace on the outer edges.
Before:
After:
=> Consistent cards heights in the mapping flow section

frontend/src/components/teamsAndOrgs/members.js, frontend/src/components/teamsAndOrgs/messages.js, frontend/src/locales/en.json
Closes #5257.
Also adds an `autoFocus` prop to the dropdown that would automatically focus the dropdown textfield when it mounts.
=> Remove default options to not prepopulate options without a query

backend/services/messaging/smtp_service.py, backend/services/messaging/templates/encourage_mapper_en.html, tests/backend/integration/services/messaging/test_smtp_service.py
Recommended projects logic needs some review so removing this on project progress emails for now. Related to #5262
=> Remove recommended projects from project progress emails

README.md, docs/sysadmins/ci-cd.md
This PR does 2 things:
1. fixes the paths in the README for the new docs structure (these will need to change again once the new doc content is finalized)
2. it adds two more necessary env vars for circle tests to pass. Most notably, [`test_variable_replacing` in `TestTemplateService`](https://github.com/hotosm/tasking-manager/blob/49632fbad1633effbc6237205271576ae01a9e60/tests/backend/unit/services/messaging/test_template_service.py#L19-L20) needs the org env vars to be able to pass
=> Fix readme

frontend/src/components/teamsAndOrgs/teams.js, frontend/src/components/teamsAndOrgs/tests/teams.test.js
Closes #5294
Updates link of team cards on the 'Teams' tab to be the same as the link in the 'Overview' tab on the management section.
=> Emend link for teams tab to be consistent with overview tab

frontend/src/assets/styles/_typography.scss, frontend/src/components/projectCard/dueDateBox.js, frontend/src/components/projectCard/messages.js, frontend/src/components/projectCard/projectCard.js, frontend/src/components/projectCard/tests/dueDateBox.test.js, frontend/src/components/projectDetail/infoPanel.js, frontend/src/components/svgIcons/timer.js, frontend/src/components/taskSelection/action.js, frontend/src/locales/en.json
Closes #5236 
- Displays the due date of the project on the project card. Due dates are not displayed if they have already passed.
- Adds a timer icon - this icon is used when the component is on the task status page. And on pages where project detail is shown, the clock icon, which is already present in the project, is used.
For project details:
For the task action page:
- Adds message when the project has no due date or the due date has expired. This message will be shown only on the project detail page.
No due date specified:
Due date expired:
- Some styling modifications have been made referencing the Figma design.
=> Display project due date on project card

frontend/src/components/projects/projectsActionFilter.js, frontend/src/components/projects/tests/projectsActionFilter.test.js, frontend/src/components/taskSelection/footer.js, frontend/src/components/taskSelection/index.js, frontend/src/components/taskSelection/instructions.js, frontend/src/components/taskSelection/messages.js, frontend/src/locales/en.json
Closes #5128 
An option has been added to the dropdown. 
The following hint is shown under the 'Instructions' tab on the task selection page.
'Select another project' will be used as the right bottom button, directing the user to the 'explore' page.
=> Filter by archived projects, add hint for archived projects

frontend/src/components/projectEdit/messages.js, frontend/src/components/projectEdit/permissionsForm.js, frontend/src/locales/en.json, frontend/src/views/projectEdit.js
- Revise actions permissions for assigned teams. Because validators can also map, assigning a team for validation means they have access to mapping and validation, eliminating the need to assign a separate team for mapping. This would also allow for a single team to map and validate at the same time.
- Add helpful note text - _"Note: Mappers have mapping permissions. Validators have mapping and validation permissions. Project managers have mapping and validation permissions and access to the management sections."_
=> Revise assigned teams actions permissions

frontend/src/components/footer/index.js
This PR implements `useMatch` from `@reach/router` to check for conditions to enable/disable the footer. This way, we can directly use app routes to render the footer conditionally.
=> Use useMatch to conditionally render footer

.circleci/config.yml, requirements.txt
Currently we are using `cimg/python:3.7-node` as base image for deployment which is alias for `cimg/python:3.7.15-node`. This uses node version 18.12.0 on which our deployment fails. This PR fixes frontend deployment by using  `cimg/python:3.7.14-node`
as base image which uses node 16.17.0. Related to #5395
=> Change deploy base image tag to 3.7.14-node

frontend/src/components/comments/commentInput.js, frontend/src/components/comments/editorIconConfig.js, frontend/src/components/projectDetail/tests/questionsAndComments.test.js
This pull request will add an image upload icon to the toolbar of the markdown editor, allowing the user to select a local image to upload.
Closes one of the tasks from https://github.com/hotosm/tasking-manager/issues/5390
=> Add icon on toolbar to upload an image for comment input

frontend/src/components/taskSelection/action.js
Related to the second item from https://github.com/hotosm/tasking-manager/issues/5149
Per task instructions were shown only when a single task was selected for mapping/validation. This PR will display task instructions even when multiple tasks are selected for validation.
=> Display task instructions also when multiple tasks are selected

frontend/src/components/formInputs.js, frontend/src/components/teamsAndOrgs/teams.js, frontend/src/views/teams.js
Closes #5415 
Initialize the team creation form with a value of `PUBLIC` for visibility key so that the value is also sent as a payload (the field is marked as required on the endpoint).
Also adds a tooltip for the radio button input when a value is not provided as follows.
=> Remove dependency on the visibility value to enable submit button

frontend/src/components/notifications/notificationBodyCard.js
Resolves https://github.com/hotosm/tasking-manager/issues/5429
=> Fix the relative path to navigate to when clicking outside the notification modal

frontend/src/components/comments/commentInput.js
Related to https://github.com/hotosm/tasking-manager/issues/5390; enable spellcheck for the markdown editor
=> Add spellcheck props for the markdown editor

frontend/src/components/comments/commentInput.js
Related to #5390; wrap the markdown editor component with light color mode.
Before:
Now:
=> Opt out of dark mode from the markdown editor

frontend/package.json, frontend/src/App.js, frontend/src/assets/styles/_extra.scss, frontend/src/components/contributions/taskCard.js, frontend/src/components/notifications/notificationBodyCard.js, frontend/src/components/notifications/notificationCard.js, frontend/src/components/notifications/notificationResults.js, frontend/src/components/notifications/styles.scss, frontend/src/views/notifications.js, frontend/yarn.lock
Resolves https://github.com/hotosm/tasking-manager/issues/5431
- Bump `reactjs-popup` dependency to its latest version 2.0.5.
- Remove URL routes for notification modal. The notification modal will be displayed without navigating to the `inbox/message/` page. Notice how the notification modal is displayed on the same page in the attached image.
- Mark notification as read without displaying the loading placeholder. Notice how the red highlight on the left side of the notification list item gets removed without showing a loading placeholder UI. Similar behavior has been implemented for deletion activity.
- Close mini notifications popup after clicking on a notification item.
- Fix hover actions over the tasks list; only perform hover actions when hovered over …
=> Display the notification modal without being directed to the notification list(inbox) page

frontend/src/components/projectCard/priorityBox.js, frontend/src/components/projectCard/projectCard.js, frontend/src/components/projectDetail/header.js, frontend/src/components/projectDetail/tests/header.test.js, frontend/src/components/projects/list.js
Closes #5455 
Remove hideMediumAndLow props from the PriorityBox component to eliminate the conditional not to display priority boxes for medium and low-priority projects. Also, hide the clock icon for medium-priority projects along with urgent ones.
=> Display priority boxes for all priority options

.circleci/config.yml
Two separate issues were preventing CircleCI builds from running properly. 
1. The CI container was running out of memory. To resolve, we increased the resource class for the container (4 -> 8 GB memory) 
2. The node-modules folder was being cached from a hotfix branch that didn't have the proper updates. We were too liberal in the caching rules, so we removed one of the keys for checking whether the pull from the cache.
=> Circleci update resource class and limit cache for frontend deps

frontend/src/components/projectDetail/favorites.js, frontend/src/components/projectDetail/footer.js, frontend/src/components/projectDetail/index.js, frontend/src/components/projectDetail/styles.scss, frontend/src/components/projectDetail/tests/favorites.test.js
Noticed that the description height wasn't rendered as expected, and the container was overlapping with the consecutive container with https://github.com/hotosm/tasking-manager/pull/5516; this PR fixes that. Also adds a flex gap to the end components of the fixed footer.
=> Brush up styles for project detail

frontend/src/components/header/NavLink.js, frontend/src/components/header/index.js, frontend/src/components/header/notificationBell.js, frontend/src/components/header/signUp.js, frontend/src/components/header/tests/index.test.js, frontend/src/components/header/tests/notificationBell.test.js, frontend/src/components/header/tests/signUp.test.js, frontend/src/components/header/tests/topBar.test.js, frontend/src/components/header/tests/updateDialog.test.js, frontend/src/components/header/tests/updateEmail.test.js, frontend/src/components/header/updateDialog.js, frontend/src/components/header/updateEmail.js, frontend/src/components/user/avatar.js, frontend/src/network/tests/mockData/auth.js, frontend/src/network/tests/mockData/notifications.js, frontend/src/network/tests/server-handlers.js, frontend/src/utils/mockMatchMedia.js, frontend/src/views/notifications.js
- Updates tests for the header and its components.
- Not display privacy policy link text if the `ORG_PRIVACY_POLICY_URL` is absent as an environment variable.
- Converts Header and UpdateEmail dialog from class components to functional components.
- Removes redundant NavLink component and a couple of other dead codes.
- Adds mock request handlers to mock API endpoints in the header section.
The coverage report is below, with the greens considered adequate for merging to develop 😏😕
=> Update tests for the header and its components

frontend/src/components/teamsAndOrgs/messages.js, frontend/src/components/teamsAndOrgs/teams.js, frontend/src/components/teamsAndOrgs/tests/teams.test.js
Resolves the first task from #3115
=> Add textfield to search for team members on the team detail page

frontend/src/components/projectDetail/header.js
Fixes styling to align project status and project visibility boxes next to the project title
_Issue:_
_Fix:_
=> Fix project header boxes to be next to project title

frontend/src/components/header/index.js, frontend/src/components/header/tests/menuItems.test.js
The indicator, the underline, for the active page disappears even if the page is a sub-section of the learn page. This PR fixes that.
=> Update nav learn link to not have type param

frontend/package.json, frontend/src/App.js, frontend/src/components/contributions/tests/myTasksNav.test.js, frontend/src/components/projects/tests/myProjectNav.test.js, frontend/src/views/tests/contributions.test.js, frontend/src/views/tests/project.test.js, frontend/src/views/tests/stats.test.js, frontend/yarn.lock
- Bump use-query-params from 1.2.2 to 2.1.2 in /frontend
- Utilize `ReachAdapter` from use-query-params as its adapter; replaces `globalHistory`.
=> Bump use-query-params from 1.2.2 to 2.1.2 in /frontend

frontend/src/App.js, frontend/src/components/banner/tests/topBanner.test.js, frontend/src/components/banner/topBanner.js, frontend/src/network/tests/mockData/miscellaneous.js, frontend/src/network/tests/server-handlers.js, frontend/src/views/fallback.js, frontend/src/views/notFound.js, frontend/src/views/tests/fallback.test.js, frontend/src/views/tests/notFound.test.js
This PR adds test cases for the NotFound, Sentry fallback, and top banner components.
=> Update tests for some smaller miscellaneous components

backend/api/tasks/resources.py, backend/api/tasks/statistics.py, backend/api/utils.py, backend/services/mapping_service.py, backend/services/validator_service.py, tests/backend/api/tasks/test_resources.py, tests/backend/base.py, tests/backend/helpers/test_helpers.py, tests/backend/integration/api/tasks/test_actions.py, tests/backend/integration/api/tasks/test_resources.py, tests/backend/integration/api/tasks/test_statistics.py, tests/backend/unit/services/test_mapping_service.py
This will extend test coverage for the following endpoints that have received at least one hit over the past three months.
This will increase backend test coverage to 70% from 65%
| Endpoint                                              | Total hits( Last 3months )  |
| ----------------------------------------------------------- | ------------ |
| backend.api.tasks.resources:tasksqueriesjsonapi             | 1.08 million |
| backend.api.tasks.resources:tasksrestapi                    | 752k         |
| backend.api.tasks.actions:tasksactionsmappinglockapi        | 303k         |
| backend.api.tasks.resources:tasksqueriesgpxapi              | 279k         |
| backend.api.tasks.actions:tasksactionsmappingunlockapi      | 199k         |
| backend.api.tasks.resources:tasksqueriesxmlapi …
=> Add tests for endpoints associated with the tasks  section

backend/api/campaigns/resources.py, tests/backend/integration/api/campaigns/test_resources.py
This PR handles campaign-related API endpoint tests.
- pull and checkout test branch using `git fetch origin && git checkout chore/add-campaign-tests`
=> Add Campaign API endpoints tests

frontend/src/components/comments/commentInput.js, frontend/src/components/comments/messages.js, frontend/src/components/projectDetail/messages.js, frontend/src/components/projectDetail/questionsAndComments.js, frontend/src/components/projectEdit/actionsForm.js
Closes #5566 
- Replaces textarea in message contributors section with CommentInput markdown editor.
- Enhancements to the CommentInput component to make it more reusable.
- Removes selection tabs from the Questions and Comments component and adds it to the CommentInput component where a flag controls its visibility.
=> Replace textarea in message contributors section with the markdown editor

frontend/src/components/taskSelection/action.js, frontend/src/components/taskSelection/actionSidebars.js
Closes #5564 
_Updates SidebarToggle to accept active editor and restarts editor context accordingly_
_Screenshot_
=> Restart editor context on side panel toggle

frontend/src/components/taskSelection/actionSidebars.js
We used relative routing links in the sidebar panel while mapping or validating tasks. These links didn't work correctly after we migrated to React Router. This PR removes the relative navigation links and updates navigation links to include project ID when redirecting from task selection screens.
=> Revise relative navigation links for action side bars

frontend/src/components/banner/tests/topBanner.test.js, frontend/src/components/banner/topBanner.js
This PR revises the TopBanner component to use a location hook for visibility check to display it only on the landing page. I got a warning while using multiple good old <Routes> components, so I included a route pathname check inside the component itself.
=> Display TopBanner only on the home page

backend/api/teams/actions.py, backend/api/teams/resources.py, backend/services/team_service.py, tests/backend/integration/api/teams/test_actions.py, tests/backend/integration/api/teams/test_resources.py
This PR handles teams-related API endpoint tests.
- pull and checkout test branch using `git fetch origin && git checkout chore/add-team-tests`
=> Add tests for endpoints related to the Teams module

backend/api/organisations/resources.py, tests/backend/integration/api/organisations/test_campaigns.py, tests/backend/integration/api/organisations/test_resources.py
This PR handles organisation-related API endpoint tests. 
How to test:
- pull and checkout test branch using `git fetch && git checkout chore/organisations-tests`
=> Add organisation tests

backend/models/postgis/message.py, backend/services/messaging/templates/level_upgrade_message_en.txt, backend/services/users/user_service.py, frontend/src/components/dropdown.js, frontend/src/components/notifications/notificationBodyCard.js, frontend/src/components/notifications/notificationCard.js, frontend/src/components/projectCard/tests/projectProgressBar.test.js, frontend/src/components/projectDetail/tests/favorites.test.js, frontend/src/components/projects/projectNav.js, frontend/src/components/projects/tests/projectsMap.test.js, frontend/src/components/taskSelection/index.js, frontend/src/components/teamsAndOrgs/tests/organisationProjectStats.test.js, frontend/src/components/tests/button.test.js, frontend/src/components/user/forms/interests.js, frontend/src/index.js, frontend/src/views/project.js, frontend/src/views/tests/fallback.test.js, frontend/src/views/tests/users.test.js
Addresses the issue raised in: #5567 
This PR sets mapping level upgrade notifications as system generated notification type and also modifies the notification templete of this notfication type.
Now the mapper level upgrade notifications will look like:
=> Set mapping level upgrade notifications as system generated

backend/api/users/actions.py, backend/api/users/openstreetmap.py, backend/api/users/statistics.py, backend/services/messaging/message_service.py, tests/backend/helpers/test_helpers.py, tests/backend/integration/api/users/test_actions.py, tests/backend/integration/api/users/test_openstreetmap.py, tests/backend/integration/api/users/test_resources.py, tests/backend/integration/api/users/test_statistics.py, tests/backend/integration/api/users/test_tasks.py
This PR adds test cases for following endponts:
| Transaction                                                 | Total count (last 3 months) |
| ----------------------------------------------------------- | ----------- |
| backend.api.users.resources:usersqueriesownlockeddetailsapi | 705k        |
| backend.api.users.resources:usersqueriesusernameapi         | 606k        |
| backend.api.users.openstreetmap:usersopenstreetmapapi       | 471k        |
| backend.api.users.resources:usersqueriesownlockedapi        | 336k        |
| backend.api.users.statistics:usersstatisticsapi             | 137k        |
| backend.api.users.resources:usersqueriesinterestsapi        | 41.7k       |
| backend.api.users.tasks:userstasksapi                       | 34.2k       |
| …
=> Add tests for endpoints associated with the users section

frontend/src/components/comments/commentInput.js, frontend/src/components/taskSelection/actionSidebars.js, frontend/src/components/taskSelection/taskActivity.js
This PR displays preview tabs in the task action and task detail modal, among other things.
- Gives the preview container a boundary.
- Removes the requirement for a comment value to display hashtag options.
Screenshots:
_Task Action page_
_Task Detail modal_
=> Display preview tabs in task action and task detail modal

frontend/src/assets/styles/_extra.scss, frontend/src/components/editor.js, frontend/src/components/horizontalScroll/index.js, frontend/src/components/horizontalScroll/styles.scss, frontend/src/components/rapidEditor.js, frontend/src/components/taskSelection/action.js, frontend/src/components/taskSelection/actionSidebars.js, frontend/src/components/taskSelection/actionTabsNav.js, frontend/src/components/taskSelection/tests/actionsTabsNav.test.js
- Closes #4047; also adds a bottom border to the tab container and changes the color of the active tab indicator to red.
- Adjust map height to fit the screen's bottom edge.
- Slenderize some tilte.
=> Use horizontal scroll buttons for tabs in task action page

frontend/src/components/taskSelection/actionSidebars.js, frontend/src/components/teamsAndOrgs/messageMembers.js
Screenshots:
_Task status for validation_
_Message team members section:_
=> Display tabs for markdown editor in message team members section and section to provide validation status for task(s)

backend/api/interests/resources.py, tests/backend/integration/api/interests/test_resources.py
This PR handles interests-related API endpoint tests.
- pull and checkout test branch using `git fetch origin && git checkout chore/add-interests-tests`
=> Add Interests API endpoint tests

backend/api/comments/resources.py, tests/backend/integration/api/comments/test_resources.py
This PR handles the Comments module-related API endpoint tests.
- pull and checkout test branch using `git fetch origin && git checkout chore/add-comments-tests`
=> Add Comments Module API Tests

frontend/src/components/portal.js, frontend/src/components/taskSelection/action.js, frontend/src/components/taskSelection/actionSidebars.js, frontend/src/components/taskSelection/actionTabsNav.js, frontend/src/components/taskSelection/multipleTaskHistories.js, frontend/src/components/taskSelection/taskList.js, frontend/src/components/taskSelection/tests/action.test.js, frontend/src/components/taskSelection/tests/actionSidebars.test.js, frontend/src/components/taskSelection/tests/extendSession.test.js, frontend/src/components/taskSelection/tests/index.test.js, frontend/src/components/taskSelection/tests/multipleTaskHistories.test.js, frontend/src/components/taskSelection/tests/taskList.test.js, frontend/src/network/tests/mockData/projects.js, frontend/src/network/tests/mockData/taskHistory.js, frontend/src/network/tests/mockData/userStats.js, frontend/src/network/tests/server-handlers.js, frontend/src/utils/testWithIntl.js, frontend/src/views/tests/taskAction.test.js, frontend/src/views/tests/taskSelection.test.js
This PR updates test cases for the task action page.
- Handle the `<Portal>` wrapper while running tests to render its children in place. Without this being handled, tests wrapped with the `TaskMapAction` component would fail, as the added tests didn't account for the wrapper.
**Challenges Encountered in Testing Certain Functionalities**
- Testing functionality that uses timeouts (setInterval and createInterval).
- Unable to find a workaround to generate map contexts for tests, so conditional functionalities requiring an editors ID or RAPID couldn't be tested.
=> Update tests for the task action page

backend/api/licenses/actions.py, backend/api/licenses/resources.py, backend/models/postgis/licenses.py, tests/backend/integration/api/licenses/test_actions.py, tests/backend/integration/api/licenses/test_resources.py
This PR handles the Licenses module-related API endpoint tests.
- pull and checkout test branch using `git fetch origin && git checkout chore/add-licence-tests`
=> Add Licenses endpoint tests

backend/api/countries/resources.py, tests/backend/integration/api/countries/test_resources.py
This PR handles the countries module-related API endpoint tests.
**How to test**:
- pull and checkout test branch using `git fetch origin && git checkout chore/add-countries-tests`
=> Add Countries Module endpoint tests

.circleci/config.yml
CircleCI used to authenticate to AWS using API key pair credentials. This proved insecure due to exposures in breaches. This commit initiates the move from API Key based approach to OpenID Connect (OIDC) based approach to authenticate to AWS from CircleCI
Circle-CI requires that jobs run within contexts for OIDC auth to work. I am using a global context for common variables like AWS Account ID in addition to existing contexts specific to instances of Tasking Manager.
TODO:
- Investigate and move *all* workflows (that connect with AWS) to OIDC
- Move workflows to the top and add semantic names for each workflow
- Only trigger CI jobs when appropriate file paths are changed
=> Switch to OIDC to authenticate CircleCI to AWS

README.md
To make the Circle-CI badge style consistent with the rest of the buttons, and to make it clear to the readers that the button represents CI status in Circle-CI, the badge style has been updated to shield.io style.
=> Adjust CircleCI badge style for consistency

.circleci/config.yml
Addresses issue #5492
Currently, OpsGenie integration does not work. The issue is being addressed separately. But there is another issue where Circle-CI does not expand the variable `$OPSGENIE_API` into its value and instead simply converts the exact string into URL safe ASCII instead of evaluating it as an ENVVAR.
This change fixes it by adding curly braces per Circle-CI documentation.
=> Fix OpsGenie API Key ENVVAR interpolation

.circleci/config.yml
Remove manual step that upgrades AWS CLI using pip since it is managed by Circle-CI ORB.
=> Remove pip upgrade awscli

frontend/package.json, frontend/src/App.js, frontend/src/components/footer/index.js, frontend/src/components/userDetail/headerProfile.js, frontend/src/components/userDetail/tests/headerProfile.test.js, frontend/src/index.js, frontend/src/routes.js, frontend/src/views/root.js, frontend/yarn.lock
Closes #5672. Does the following:
- Bump use-query-params from 2.1.2 to 2.2.1
- Bump react-router-dom from 6.8.1 to 6.10.0
- Replace mapStateToProps with the useSelector hook
- Replace BrowserRouter with the newly introduced createBrowserRouter
=> Use createBrowserRouter from React Router

scripts/aws/cloudformation/tasking-manager.template.js
In the CloudFormation template we manage, we had hardcoded the instance type of the backend EC2 VM and the AMI. This change parameterises it so that the values can be updated later by passing it to cfn-config
- Update PostgreSQL version from 11.12 to 11.19 - this change has already been made in RDS manually. This is a noop change.
- Update AMI to the latest Ubuntu 20.04. This will cause instances to be replaced.
- Update instance type to c6a.large. This will make our instances cheaper and more performant.
=> Parameterise Backend AMI and Instance Type

scripts/aws/cloudformation/tasking-manager.template.js
AWS Cloudfront properties have been updated to:
1. Enable http2 protocol in the viewer facing side. This might improve performance for users.
2. Improve SSL Cipher suite to the latest version. This might improve performance and security for users.
3. Enable IPv6 for the CDN distribution. This is already the default behaviour in CloudFront. I have just made it explicit.
=> Improve security parameters for AWS CloudFront

scripts/aws/cloudformation/tasking-manager.template.js
After enabling IPv6 support on the CDN itself, we need to create DNS AAAA records to be able to reach the frontend CDN using IPv6. This change creates the resource records in AWS Route53 - the DNS service for hotosm.org
Replaces a RecordSet resource with a RecordSetGroup resource
=> Add IPv6 route to Frontend CloudFront CDN

scripts/aws/cloudformation/tasking-manager.template.js
Reverted all changes made to S3 bucket and restoring access to public for the S3 bucket.
TODO: Restrict access by header set in CloudFront.
=> Allow public access to S3 bucket

frontend/src/components/notifications/notificationResults.js
=> Add spacing to no unread messages

backend/__init__.py, backend/api/teams/resources.py
**What does this PR do?** 
Under the TeamsRestAPI, we have two methods doing the same job, i.e. POST and PATCH. This PR removes the redundant POST method that is not in use anywhere and is essentially a copy of what the PATCH method does. 
The PATCH method is retained since the RFC standards dictate that the PATCH method is what is used to update a resource and not POST.
=> Remove redundant TeamsRestAPI Post method

frontend/package.json, frontend/src/components/taskSelection/imagery.js, frontend/src/components/taskSelection/taskList.js, frontend/src/components/taskSelection/tests/imagery.test.js, frontend/src/components/taskSelection/tests/taskList.test.js, frontend/src/components/teamsAndOrgs/organisations.js, frontend/src/components/user/content.js, frontend/src/components/user/tests/content.test.js, frontend/src/views/tests/organisationManagement.test.js, frontend/yarn.lock
This PR does the following: 
- Closes #5719 . Use the browser window object instead of the React Router location object to generate task and organization URLs. The values of the location object must have changed, making the origin variable undefined when we migrated to React Router from Reach Router.
- Removes the dependency on `@lokibai/react-use-copy-clipboard` previously used for copying text to the clipboard. This is due to deprecated usage of the [document.execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) function and lack of recent commits (last commit over 3 years ago). Instead, the `navigator.clipboard.writeText` function has been implemented to achieve the desired copy-to-clipboard functionality.
=> Use window object to generate copy URLs for tasks and organizations

backend/api/organisations/resources.py, backend/services/organisation_service.py, tests/backend/integration/services/test_organisation_service.py
closes #5723 
_**What to test?**_
Private teams should be hidden on the organization detail page if any of the following conditions are met:
- User is not logged in.
-  User does not have the permission to manage the organization.
Private teams should be displayed on the organization detail page if any of the following conditions are met:
- User has organisation manage permission
- User has system admin role
Public teams should be visible under all circumstances.
=> Hide private teams on organisation detail view for users without manage permission

.circleci/config.yml
This change introduces wait-to-become-available logic  before performing snapshot copy or snapshot creation for RDS Database Servers
=> Wait for RDS resources to become available

frontend/src/components/homepage/stats.js, frontend/src/components/homepage/tests/stats.test.js, frontend/src/network/tests/mockData/miscellaneous.js, frontend/src/network/tests/server-handlers.js
Closes #5738 
- Updates the component to load and display stats from two different APIs simultaneously. It does this by using the Promise.all() method, which allows concurrently fetching data from multiple sources. 
- Updated to show a dash ("-") instead of undefined values while the stats are still loading.
=> Display TM stats on the landing page simultaneously

backend/services/project_admin_service.py, tests/backend/integration/services/test_project_admin_service.py
The condtion to raise NotFound was unreachable as the function to return org already would have raised the NotFound exception if org was returned None. This PR removes that condition and updates the test case reflecting the change.
=> Remove unreachable condition to raise organisation NotFound

frontend/src/components/redirect.js, frontend/src/components/tests/redirect.test.js, frontend/src/routes.js
Closes #5737 
- Updates the Redirect component to support dynamic URL parameters. Previously, the component redirected to a static URL provided in the to prop. It extracts any necessary parameters from the current URL using useParams, constructs the appropriate URL based on the to prop and any extracted parameters, and then redirects to that URL using useNavigate.
- Extracts the Redirect component into a separate file in `src/components/redirect.js`
- Adds a test to cover the scenario that redirects from /project/XXX to /projects/XXX router
=> Refactor Redirect component to support dynamic URL parameters

frontend/src/components/messages.js, frontend/src/components/projectEdit/teamSelect.js
Resolves #5741 
This PR does the following: 
- Adds a new message under the components directory to be utilized throughout the application. This message will be displayed in the select container while organisations and teams options are loading. It was really weird how the loading message won't be displayed if an empty array won't be passed as options.
- Replace fetchLocalJSONAPI with useFetchWithAbort to fetch organizations and teams for permissions.
- Addresses a warning by ensuring that the team ID is used as the key when mapping the teams' list.
Screenshot
=> Display loading text when organisations and teams are loading under Permissions under project creation

backend/config.py, example.env
Use test database name from environment variable instead of adding `test_` ahead of `POSTGRES_DB` variable to improve the maintainability of the code base by reducing redundancy and improving readability.
=> Add env variable POSTGRES_TEST_DB for test database name.

backend/models/postgis/project.py, backend/services/project_search_service.py, backend/services/project_service.py
closes #5578 and #3841
**#5578**
With this PR, we moved the function used to compute project completion out of cache, allowing it to be updated in real time. This will fix a number of side effects, including the issue described in #5578 and the difference in completeness between the project card and the project detail page.
**#3841**
Furthermore, the function to compute project completion has been set as an instance method rather than a static method, so that all project task statistics do not need to be supplied as arguments to calculate project completion statistics. When this is set as the instance method, all of the project tasks' statistics can be retrieved via the project instance itself.
How to test **locally**? _**(Caution: Do not do this in live instance)**_
- Go to any tasks …
=> Fix project completion issues with project summary caching

backend/__init__.py, backend/api/comments/resources.py, backend/models/dtos/message_dto.py, backend/models/postgis/project_chat.py, backend/services/messaging/chat_service.py, frontend/src/components/projectDetail/index.js, frontend/src/components/projectDetail/questionsAndComments.js, frontend/src/components/projectDetail/tests/questionsAndComments.test.js, frontend/src/components/taskSelection/tests/taskList.test.js, frontend/src/components/teamsAndOrgs/management.js, frontend/src/network/tests/server-handlers.js, tests/backend/integration/api/comments/test_resources.py, tests/backend/integration/services/messaging/test_chat_service.py
Partially addresses #4858 by adding feature to delete message on project's question and comment section.
Only the project manager and the message's author will be able to delete a message. On frontend delete button will be shown to all messages if user has project manage permission else the delete button will only be shown on the comment which is posted by the logged in user.
**TO DO: Add a toast message to indicate the success or failure of comment deleting.**
=> Add feature to delete project chat messages.

tests/backend/integration/api/comments/test_resources.py
Because the version of black was not upgraded when working on #5742, all of the code was formatted with the previous version of black, however on develop we upgraded the version of black along with formatting adjustments. After merging #5742, a code formatting issue arose as a result.
=> Fix backend code formatting.

frontend/src/components/projectDetail/header.js, frontend/src/components/projectDetail/tests/header.test.js
Closes #5734 
Changes made:
- The function signature of the TagLine component is updated to include the interests parameter. The rendering logic is also modified to display the interests. Campaigns and interests are now joined with a comma separator, while campaigns, countries, and interests are displayed with an interpunct as the separator.
- Updates tests for the same.
=> Display project categories in the project detail page

.circleci/config.yml
For database snapshots, there are namespace collisions when snapshots are repeated in the same day. To fix this, we use bash(>=4.2) builtin date formatter to add timestamp with minutely granularity as suffix.
This should prevent namespace collisions from happening and as a result, prevent database snapshot creation failures.
=> Fix timestamp suffix to avoid namespace collisions

backend/services/project_search_service.py
Closes #5751 
This PR refactors the country search functionality in response to an issue where South Sudan projects were showing up under Sudan when filtering by location. The previous implementation used an ilike search to match country names in a nested array, which resulted in false positives.
The new implementation uses exact matching to make the search more precise and reliable. It replaces the ilike function with the equality operator, ensuring that only the projects with the exact country name are returned.
This change improves the accuracy of the search results and eliminates the issue like South Sudan projects appearing under Sudan.
=>  Refactor country search for more precise matching

.circleci/config.yml
Upgrade staging PostgreSQL version from 11.x to 13.x in order to test compatibility for future production upgrade.
This change will be used to test if the database is being upgraded in-place or being replaced by AWS with a new database.
=> Upgrade staging PostgreSQL version 11.19 -> 13.7

.circleci/config.yml
AWS RDS PostgreSQL major versions upgrades have to be performed to specific target versions specified in the following link:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/ USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion
In compliance with that, this change updates the target version from 13.7 to 13.10
=> Fix PostgreSQL upgrade target minor version

.circleci/config.yml
Upgrade of instance type was successfull by itself. Now, we upgrade the engine version of RDS PostgreSQL DB
=> Upgrade RDS DB Engine version

pdm.lock, pyproject.toml
Add removed package newrelic needed for production deployment of tasking-manager. This adds missing updates to pdm.lock file.
=> Add newrelic package with pdm.lock

.circleci/config.yml
This commit introduces two changes:
- staging instance is downgraded from an expensive instance type c6a.large to a less expensive t3.medium instance type. This is adequate for testing purposes
- Approvals and holds are now enabled for staging / development deployments through CircleCI
=> Reduce staging backend EC2 instance size

.circleci/config.yml
@eternaltyro 
Removing the OpsGenie webhook so that we maintain just the orb.
=> Remove OpsGenie Webhook and maintain orb

pdm.lock, pyproject.toml
Bump sentry-sdk to 1.24.0 in pyproject.toml as we use pyproject.toml to install dependencies instead of requirements.txt.
=> Bump sentry-sdk on pyproject.toml

pdm.lock, pyproject.toml, requirements.txt
Fixes #5785 
Because of its numerous system dependencies, installing psycopg2 on some systems can occasionally be very challenging. This problem can be fixed by adding psycopg2-binary as a dev dependency as mentioned by @spwoodcock on https://github.com/hotosm/tasking-manager/issues/5785#issuecomment-1548446678
Dev dependencies can be installed with command `pdm install --dev`
PS: Using psycopg2-binary in production is not advised.
=> Add psycopg2-binary as dev dependency.

backend/__init__.py, backend/config.py, backend/services/messaging/message_service.py, tests/backend/base.py, tests/backend/integration/api/comments/test_resources.py
When running tests for the function that involves creating a thread and an associated app context, we encountered an issue with the app configuration. The create_app function, responsible for creating the app context, was using the default `EnvironmentConfig` class even during testing.
To address this issue, we made a modification in the create_app function. We added a condition that checks if the TM_ENVIRONMENT environment variable is set to "test". If so, the configuration is set to `TestEnvironmentConfig` instead of the default `EnvironmentConfig`. 
By introducing this conditional logic, it ensures that the create_app function correctly sets the `TestEnvironmentConfig` for the app created across the project when the test environment is detected.
closes #5691
=> Fix app configuration in create_app for testing.

backend/services/messaging/message_service.py
=> Replace `current_app` with `create_app` to provide `app_context`.

backend/config.py
In the previous implementation, there was an issue with parsing the boolean values of the SMTP configuration from environment variables. The use of bool() on the string returned by `os.getenv()` caused both `MAIL_USE_TLS` and `MAIL_USE_SSL` to be set to True, regardless of the actual environment variable values.
This PR fixes the issue with boolean parsing. By explicitly converting the environment variable values to integers using int() and providing default string values of "1" for `TM_SMTP_USE_TLS` and "0" for `TM_SMTP_USE_SSL`, the correct boolean values are obtained. This ensures that the SMTP configuration reflects the intended TLS and SSL settings based on the environment variables provided.
With this fix, the `MAIL_USE_TLS` and `MAIL_USE_SSL` variables will be set to True only if …
=> Fix boolean parsing of SMTP configuration from environment variables.

backend/services/stats_service.py, tests/backend/integration/api/projects/test_contributions.py
This PR fixes issue #4899 on divergent contributor counts on the project detail and project list views. 
- fetch and checkout branch using `git fetch origin && git checkout fix/contribution-stats`
- install dependencies
- start both the frontend and backend servers
- Go to the http://127.0.0.1:3000/explore to see project list. Note the contributor counts of different projects.
- Click on different projects to compare the contributor counts.
=> Fix contribution stats

backend/models/postgis/utils.py
closes #5847 
For easy use, some of the postgis generic functions have been redefined in the TM backend code base. Due to the attribute 'inherit_cache' being absent, warnings were displayed for these functions. Therefore, all of the redefined functions have this property set to True.
**Warning sample:**
SAWarning: Class ST_Area will not make use of SQL compilation caching as it does not set the `inherit_cache` attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this object can make use of the cache key generated by the superclass.  Alternatively, this attribute may be set to False which will disable this warning. (Background on this warning at: …
=> Fix warnings shown by sqlalchemy on redefined functions.

.coveragerc, pyproject.toml
This PR performs following modifications:
- Adds `__pypackages__` in list of directories that needs be excluded while generating coverage report.
- Modifies alias of pdm script to run command `coverage -m unittest discover` to `coverage-discover`, so that other coverage commands are executable using `pdm run coverage <option>`
=> Update coverage configs

pyproject.toml, requirements.txt
- Remove all of the transitive dependencies from requirements.txt as they are handled in pdm.lock and we only use requirements.txt to get dependency updates from dependabot.
- Reorder dependencies in pyproject.toml since pandas and scikit-learn were listed under section "dependencies used by HOT for production".
=> Remove all of the transitive dependencies from requirements.txt

frontend/src/assets/styles/_extra.scss
=> Remove tachyons outline in link focus

frontend/src/components/projectCard/tests/dueDateBox.test.js, frontend/src/components/projects/tests/moreFiltersForm.test.js, frontend/src/components/taskSelection/tests/footer.test.js, frontend/src/views/tests/fallback.test.js, frontend/src/views/tests/organisationManagement.test.js
* `waitFor`
* `userEvent`
* `clearReduxStore`
Note: `act` not done since it is only async in newer versions of jest.
=> Tests: add missing await for async statements in tests

frontend/src/views/quickstart.js
This is just a warning from react. Since we aren't changing the `steps` variable dynamically, all this does is silence a warning.
=> ReactJS: Fix "Each child in a list should have a unique 'key' prop"

backend/api/notifications/resources.py, backend/services/notification_service.py, tests/backend/helpers/test_helpers.py, tests/backend/integration/api/notifications/test_actions.py, tests/backend/integration/api/notifications/test_resources.py
This PR adds tests related to the Notifications API endpoints. 
**Related issue:**
- #5442
- pull and checkout test branch using `git fetch origin && git checkout chore/add-notifications-tests`
=> Add notification API tests

.circleci/config.yml
Backend functional tests already use PostgreSQL 14.x without any problems. This change brings parity to staging PostgreSQL version: upgrading it from version 13.10 to 14.8
=> Upgrade staging PostgreSQL version to 14

tests/backend/integration/api/projects/test_resources.py
Sorted the returned result to check with the expected to ensures that it doesn't fail due to the order of returned projects.
=> Fix one of the failing project tests due to order of returned result.

backend/__init__.py, backend/error_messages.json, backend/exceptions.py
closes #5909 
This pull request (PR) introduces the necessary infrastructure to enhance backend error handling in the project. It includes the implementation of custom exception classes that extend the `BaseException` class from `werkzeug.exceptions.HTTPException`. These custom exceptions offer additional features for handling various types of errors effectively.
Moreover, this PR also introduces a mechanism to separate error messages from the code. The error messages are now stored in a JSON file named "error_messages.json". This approach simplifies the management and updates of error messages independently, providing more flexibility in maintaining and modifying them
Example:
We can raise a NotFound Exception as:
```python
raise NotFound(sub_code="PROJECT_NOT_FOUND", project_id=1)
``` …
=> Define custom exceptions for better handling error response

backend/models/postgis/project.py
closes #5916 
This commit fixes an issue where the `ProjectTeams` object was not added to the session, causing projects teams being removed while updating them. By adding the `ProjectTeams` object to the session after its creation, the subsequent add operation on Project.teams can proceed without any issues.
The changes ensure that the ProjectTeams object is properly associated with the session, allowing for the correct handling of relationships within the update method.
=> Fix removal of project teams while updating them.

backend/services/users/user_service.py
**Background**
When a user attempts to register a new account, the provided e-mail address is checked against the existing e-mails in the database to detect if there already exists an account with that e-mail address.
**The proposed changes** 
1. Perform the e-mail address comparison in lower-case to make it case-insensitive
2. If there are two or more users with the same e-mail address, return a 400 error (user already exists) instead of a 500 error (internal server error)
=> Improve check for existing email addresses

frontend/src/components/projects/filterSelectFields.js, frontend/src/hooks/UseTasksStatsQueryAPI.js, frontend/src/views/organisationStats.js, frontend/src/views/stats.js
This pull request closes #5863, where the error component would be displayed when a new request to the `/tasks/statistics/` endpoint was made while an ongoing fetch was in progress. The root cause of this issue has been identified and resolved.
- Accommodated using the use `TasksStatsQueryParams` in `OrganisationStats` and `Stats` components, utilizing the useTasksStatsQueryAPI hook.
- Removed the _now_ unused variables `forceUpdate` and `forceUpdated` from the `useForceUpdate`.
- Updated the usage of the `useTasksStatsQueryAPI` hook by _replacing_ the `forceUpdated` argument with the `fetchTasksStatistics` function. This change allows passing the `fetchTasksStatistics` function as the retry function in the `TasksStats` component.
- Wrapped the date picker and icon with flex so that they …
=> Fix issue with error component display during ongoing fetch

backend/models/dtos/__init__.py
This PR adds the necessary component to fix #5910 
- Creates a decorator which can be used to validate the request body against a DTO class.
- This decorator can be applied to the route handler that requires request validation.
- This decorator validates the request using the provided DTO class and stores the validated DTO instance in request.validated_dto.
- Adds a function to fetch validation errors from Schematics `DataError` exception class so  that we can return what and where error occurred during request validation.
**Sample validation error :**
```python
@validate_request(ProjectCreateDTO)
def post():
validated_dto = request.validated_dto # request.validated_dto will be set in the decorator after validating request against dto ProjectCreateDTO
```
If the validation error occurs …
=> Refactor request body validation using decorator

frontend/src/utils/openEditor.js
Right now, there is a race condition when using JOSM remote control.
The TM currently makes the following calls, in order:
1. Import task boundary
a. Create a new, empty layer with a hardcoded XML (I believe this is for the `upload="never"` option)
b. Load the boundary into the new layer
2. Load data from OSM
a. Create a new, empty layer with a hardcoded XML
b. Load the data from a specified bounding box into JOSM
With the current implementation, the return information from JOSM is not checked. This means that if 2a fails, the OSM data will be loaded into the layer created in 1a. Additionally, if the user changes layers prior to the data load, the data may load into the wrong layer.
Having two sub-steps for either step is unnecessary. For the first, there is an `upload_policy=never` query …
=> Use idempotent remote control commands for JOSM

frontend/src/components/editor.js, frontend/src/components/rapidEditor.js, frontend/src/components/teamsAndOrgs/teams.js, frontend/src/components/user/content.js
We were comparing to undefined (literal) instead of 'undefined' (string). `typeof` will always return a string, so `'undefined' !== undefined` would always return `true`.
For more details, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof .
=> Fix eslint warnings for valid-typeof

frontend/src/components/projectEdit/metadataForm.js, frontend/src/components/user/forms/notifications.js, frontend/src/components/user/forms/settings.js, frontend/src/components/user/forms/switchToggleField.js
This is due to the "initial" value being `undefined` or `null` prior to the user data being fetched.
=> ReactJS: Fix an input component changing from uncontrolled to controlled

frontend/src/routes.js, frontend/src/views/projectEdit.js
This reduces the amount of date that must be transmitted in order for the initial page (whatever it is) to load.
For the purposes of this analysis, I am using statoscope.tech with download speeds equivalent to fast 3g (1.4 MBit/s).
||Total Size|Initial Size|Initial download time|Packages Size|Build Time|Modules|Duplicate Modules|Chunks|Assets|Packages|Package Copies|
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
|de65ce14c40f13583b4c0f26e8967630056f21e9|6.39 mb|17.33 mb|101.2s|23.49 mb|103.8s|4000|13|1597|3244|272|5|
|e11bc43bed0bc9c2ad8315aea33c3b54c5140052|3.70 mb|7.62mb|44.5s|23.48 mb|237.6s|4033|13|1631|3335|272|5|
|e11bc43bed0bc9c2ad8315aea33c3b54c5140052 with #5908|3.64 mb|3.64 mb|21.3s|23.15 mb|37.6s|4020|0|1638|1689|265|6|
Note: Build time seems to be highly …
=> Use lazy loading for routes

tests/backend/integration/api/organisations/test_campaigns.py, tests/backend/integration/api/projects/test_actions.py, tests/backend/integration/api/projects/test_resources.py, tests/backend/integration/api/tasks/test_resources.py, tests/backend/integration/api/users/test_resources.py
=> Fix test cases that, while checking the 404 status code, make requests to non-existent urls rather than non-existent resources.

frontend/src/components/header/tests/notificationBell.test.js, frontend/src/components/notifications/actionButtons.js, frontend/src/components/notifications/messages.js, frontend/src/components/notifications/notificationBodyCard.js, frontend/src/components/notifications/notificationOrderBy.js, frontend/src/components/notifications/notificationResults.js, frontend/src/components/notifications/tests/actionButtons.test.js, frontend/src/components/notifications/tests/inboxNav.test.js, frontend/src/components/notifications/tests/notificationBodyCard.test.js, frontend/src/components/notifications/tests/notificationCard.test.js, frontend/src/components/notifications/tests/notificationOrderBy.test.js, frontend/src/components/notifications/tests/notificationResults.test.js, frontend/src/components/notifications/tests/paginator.test.js, frontend/src/network/tests/mockData/notifications.js, frontend/src/network/tests/server-handlers.js, frontend/src/views/notifications.js, frontend/src/views/tests/notifications.test.js
Closes #5722 
This pull request primarily focuses on updating component tests on the notifications page. Additionally, it includes several other improvements unrelated to the test code. Here is a summary of the changes:
- Updated tests for components on the notifications page.
- Resolved an issue by sending `setPoputFocus` to the `InboxNavMini` component, preventing an uncaught error when routing to a location using Link.
- Added a `generateSampleNotifications` function to simplify testing interactions with all notifications on a page.
- Implemented a server handler to intercept requests to the GET `/notifications/:id` endpoint.
- Moved the `updateUnreadCount` function to the `ActionButtons` component to eliminate prop drilling and improve code organization.
- Removed unnecessary `else` …
=> Update tests for the notifications page components

frontend/package.json, frontend/yarn.lock
Ran into the following issue. 
```
One of your dependencies, babel-preset-react-app, is importing the "@babel/plugin-proposal-private-property-in-object" package without declaring it in its dependencies. This is currently working because "@babel/plugin-proposal-private-property-in-object" is already in your node_modules folder for unrelated reasons, but it may break at any time.
babel-preset-react-app is part of the create-react-app project, which is not maintianed anymore. It is thus unlikely that this bug will ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to your devDependencies to work around this error. This will make this message go away.
```
This PR is the workaround to make the message go away.
=> Add @babel/plugin-proposal-private-property-in-object to devDependencies

backend/models/postgis/task.py
closes #5902 
As described in [5902 comment](https://github.com/hotosm/tasking-manager/issues/5902#issuecomment-1603922515), presence of `{`, `}` and `{}` in the specific tasks instructions breaks the endpoint `users/queries/tasks/locked/details/`. This PR captures the exceptions raised while trying to format specific task instruction and returns the instruction as it is.
=> Catch exceptions raised while formatting specific tasks instruction.

frontend/src/components/comments/editorIconConfig.js
This fixes a warning for "Warning: Invalid DOM property `class`. Did you mean `className`?".
=> React: Fix "Invalid DOM property `class`" in JSX SVG

frontend/src/components/projectEdit/settingsForm.js
This makes the language selection box down a  _controlled_ selection box.
=> ReactJS: Don't use 'selected' for '<option/>' nodes

frontend/src/components/taskSelection/footer.js
Closes #5945 
This pull request addresses an apparent oversight introduced in #4934. The code in question pertains to the page reload when handling the locking of a mapping task.
After consulting with Wille, the previous maintainer, it has been determined that the reload behavior introduced in the codebase is not necessary and can be safely removed. 
Fingers crossed that this change doesn't cause any unexpected issues in the mapping flow :crossed_fingers:!
=> Remove window reload from lock task for mapping logic

frontend/src/components/banner/topBanner.js, frontend/src/views/root.js
=> Keep the footer at the bottom on a short page

backend/models/postgis/message.py, backend/services/messaging/smtp_service.py, backend/services/project_service.py
This PR addresses the issue #5331, which was not reproducible locally. The aim of this fix is to identify and eliminate potential factors that may contribute to the problem of sending multiple project update emails.
- Makes sure distinct project contributors are fetched from database.
- Makes sure project is `project_update_email` field is updated before starting to send project update emails.
- Adds a logger to capture email type, project id and email address so that we can examine logs to make sure if the issue has been fixed.
=> #5331 - Eliminate Possibilities of Sending Multiple Project Update Emails

frontend/src/components/banner/index.js, frontend/src/components/footer/index.js, frontend/src/components/footer/tests/index.test.js, frontend/src/components/header/index.js, frontend/src/components/header/signUp.js, frontend/src/components/header/tests/index.test.js, frontend/src/components/header/updateEmail.js
Partially fixes #5925 
This PR updates the protocol to https. I have also updated the ORG_URL in CircleCI Context for staging and production to be "www.hotosm.org"
The reason we can't easily setup a redirect is [from AWS](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html):
> Unlike a CNAME record, you can create an alias record at the top node of a DNS namespace, also known as the zone apex. For example, if you register the DNS name [example.com](http://example.com/), the zone apex is [example.com](http://example.com/). You can't create a CNAME record for [example.com](http://example.com/), but you can create an alias record for [example.com](http://example.com/) that routes traffic to [www.example.com](http://www.example.com/) …
=> Use https for outlink

frontend/src/components/editor.js, frontend/src/components/messages.js, frontend/src/components/rapidEditor.js
=> Make GPX name attribute string translatable

frontend/src/components/header/styles.scss, frontend/src/components/projectDetail/styles.scss
Resolves #5893 
This hides the scrollbar while supporting horizontal scrolling in Firefox. The previous implementation only worked in Chrome but not in Firefox.
=> Hide scrollbar in Firefox

backend/models/dtos/interests_dto.py, tests/backend/integration/api/interests/test_resources.py
=> Don't allow creating/updating interest with empty name

pdm.lock, pyproject.toml
This PR modifies the requires-python constraint in the pyproject.toml file to ensure that the Python version used for this project remains between 3.10 and 3.11. By locking the Python version in this range, we guarantee that the generated lock file will be based on Python 3.10, which aligns with the production setup requirements.
With this change PyYAML is also updated to 6.0.1 which fixes partly #5997.
=> Update requires-python version to ">=3.10,<=3.11"

pdm.lock, pyproject.toml
Staging server was disrupted after merging #6013 due to python 3.10 not being present in server. So revering the changes made in PR #6013 to fix the issue for now
=> Set Python version between 3.9 and 3.11 reverting #6013

.gitignore, frontend/package.json, frontend/src/index.js, frontend/yarn.lock
This PR adds sentry replays and source maps for improved frontend tracking
=> Add sentry replays and source maps

.dockerignore, Dockerfile, Makefile, docker-compose.override.yml, docker-compose.yml, scripts/docker/Dockerfile.backend, scripts/docker/Dockerfile.frontend_development, scripts/docker/tasking-manager/Dockerfile
* Update `Makefile` so it works (`app` -> `backend`/`frontend`, depending upon context)
* Use an official postgis image (that is actually updated, `mdillon/postgis:11` -> `postgis/postgis:11-3.1` (3.1 is the postgis version)
* Use official node images (`tiangolo/node-frontend:10` -> `node:14` (node 10 is no longer supported, and node 12 EOL is less than a year away).
=> Update docker-compose and other docker files

frontend/src/components/taskSelection/footer.js, frontend/src/components/taskSelection/index.js, frontend/src/components/taskSelection/lockedTasks.js, frontend/src/components/taskSelection/map.js, frontend/src/components/taskSelection/messages.js, frontend/src/components/taskSelection/tests/lockedTasks.test.js, frontend/src/locales/en.json
Resolves #5435 
- Added a new "Deselect and Validate" button to the task lock error modal, allowing users to deselect tasks they have mapped for validation.
- Conditionally displayed action buttons based on the user's selected tasks and mapping status.
- Abstracted the action buttons into a new `LockErrorButtons` component, which also handles task deselection and validation logic.
- Updated existing test cases to account for the new button behavior.
=> Enable ability for users to select tasks they mapped

frontend/src/components/userDetail/elementsMapped.js
This PR addresses missing data points currently unavailable from ohsomeNow stats by changing `0` to `-` in My Contributions section.
- Part of #6078
=> Change value from `0` to `-` in My Contributions stats section

frontend/src/api/projects.js
This PR addresses the issue related to the user's unable to access private and draft projects. The issue arose because the API call for project details was missing an auth token. For the fix token has been added to the API call.
Fix for issue #6088
=> fix: unable to access draft and private projects

frontend/src/views/teams.js
The draft and archived projects were not visible on the teams page. This fixes the issue by adding projectStatuses query param to the api for projects in team page.
- fix #6070
=> fix: associated projects in teams page

backend/api/teams/resources.py, backend/services/team_service.py
There was no appropriate error message when trying to delete a team but was not deleted because it has projects associated. Now error message is returned from the backend instead of an internal server error.
- fix #6071
=> fix: team delete message for associated projects

tests/backend/integration/api/tasks/test_statistics.py
- Test cases for tests/backend/integration/api/tasks/test_statistics.py were failing due to time intervals greater than 1 year. 
- There was a fixed date for the startDate value in test cases "2023-01-01". Now the startDate will get the date of the past six-month. 
- The fixed dates are now replaced with dynamic past six month date.
=> fix: unit test fail for backend tasks/statistics

frontend/src/components/projectDetail/downloadOsmData.js
- Enhances download logic for exports 
- On previous approach , We cached file into browser letting user save exports from cache. This approach introduced bottleneck on devices with low RAM . Execution time for function also elevated long as logic waits for file to be downloaded in cache 
- Current approach : We make use of HEAD call instead of GET to know the status code of exports . This includes redirect user to original download link instead of storing in browser cache ! 
- Try downloading exports from projects page . You should observe quicker function execution time !
=> Enhance : Download link for Exports 

.circleci/config.yml, docker-compose.yml, docs/developers/development-setup.md, example.env, scripts/install/install_on_debian_10_buster.sh, scripts/install/install_on_ubuntu_18_04.sh
- The docker compose setup for development uses Traefik on port 80.
- On many machines port 80 is not an option: either in use, or not available in rootless mode.
- The container names are also a mix of conventions: two being automatically generated, two being manually specified.
- The development setup guide is also missing a few things to get started easily.
- Added a `TM_DEV_PORT` variable to the dotenv options, so the port can be configured.
- Updated all containers to have consistent names. I prepended `tm-` to prevent conflict with other tools that may have containers named `backend` and `frontend`.
- Updated the development setup guide:
- Info on running via docker.
- How to set up OSM OAuth creds.
- @robsavoye was having some issues setting up Tasking Manager for testing.
- I …
=> Configurable devevelopment port & documentation updates

frontend/src/components/projectDetail/footer.js
=> fix: footer dynamic on visibility with boolean key

backend/services/project_service.py
- This PR enhances the active projects API by : 
- Fixing bug on UTC timestamp comparison while fetching projects 
- if Project has a comment / conversation happening then that project is also considered as active 
- I am aware of performance of the API , I will wait for the multi process approach that's going on before adding enhancement on this endpoint for the consistency 
- I have compared number of projects returned with following query in database directly and from the API endpoint : ```http://127.0.0.1:5000/api/v2/projects/queries/active/?interval=1```
```sql 
with t1 as (
select distinct  project_id 
from project_chat pc 
WHERE "time_stamp" > (CURRENT_TIMESTAMP AT TIME ZONE 'UTC') - INTERVAL '1 hours'
UNION
SELECT DISTINCT project_id 
FROM task_history 
WHERE action_date > …
```
=> Enhance : Active Projects API 

frontend/src/components/projectDetail/index.js, frontend/src/components/projectDetail/timeline.js, frontend/src/components/projectStats/contributorsStats.js, frontend/src/components/teamsAndOrgs/tasksStatsChart.js, frontend/src/components/teamsAndOrgs/tests/tasksStats.test.js, frontend/src/network/tests/mockData/projects.js, frontend/src/utils/chart.js, frontend/src/views/tests/project.test.js
See https://github.com/hotosm/tasking-manager/pull/5721#discussion_r1193684581 for additional context.
Big things:
* Keep current behavior as much as possible
* ISO 8601 YYYY-MM-DD for chart X axis labels
* Tooltips shouldn't show hour/minute/second
* I ended up expanding the tooltips a bit ("Thursday, July 6, 2023" instead of "2023-07-06").
=> Fix chartjs warnings

backend/models/postgis/task.py, backend/models/postgis/user.py, backend/services/stats_service.py, backend/services/users/user_service.py, backend/services/validator_service.py, tests/backend/integration/api/tasks/test_actions.py
- fix #6244 
- fix #6154 
- Uses Python multiprocessing pool to run validation tasks in parallel using available CPU cores
- Local session for thread implementation for validation-related tasks
- Test case-related validation modified to get task by taskId instead of index as threading may sometimes return task which do not follow order
=> Unlock tasks after validation using in parallel using python threads

docker-compose.yml, docs/developers/development-setup.md, example.env
1. The swagger docs could not be loaded during local development, as they rely on https://hotosm.github.io/swagger/, which is a HTTPS website, while the openapi.json under `/api/v2/system/docs/json/` is HTTP. This causes a mixed content error.
2. The `example.env` defaults are for running locally, while the recommended approach for the entire stack is via docker.
1. Add a docker compose service for Swagger docs, accessible via `http://URL:PORT/docs/`.
The prod deploy does not use docker compose, so I believe this will not be an issue.
2. Updated `example.env` and dev documentation to use port `3000` by default, and `postgresql` as the database host (instead of `localhost`).
- Remove your old `tasking-manager.env`: `mv tasking-manager.env old.tasking-manager.env`.
- Create a new one with …
=> Fix dev swagger docs, update example env defaults

frontend/src/components/projects/projectNav.js, frontend/src/hooks/UseProjectsQueryAPI.js
- Enhances Project Lists Page Project List API and overall execution time, when Map is not turned on. 
- On previous approach , We were using project list api without omitMapResults true and even if the map was not open, It was still fetching all the geojson of projects.
- Current approach : We are using omitMapResults params so that when we don't need geojson we can only fetch the project related data and only fetch geojson when the map is turned on.
- Try using the projectlist page it's response time has decreased and projects card loads faster.
=> Fix/ faster load project list with no map omit

backend/models/postgis/project.py
The unit test `tests/backend/unit/models/postgis/test_project.py`'s `test_set_country_info` method was performing a `GET` from nominatim's reverse geocode api ie: [https://nominatim.openstreetmap.org](https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=56.11996666666666&lon=-3.9156666666666666&accept-language=en) 
This api was failing with `requests.exceptions.HTTPError: 403 Client Error: Forbidden for url. `
```
<html>\n<head>\n<title>Access blocked</title>\n</head>\n<body>\n<h1>Access blocked</h1>\n\n<p>You have been blocked because you have violated the\n<a href="https://operations.osmfoundation.org/policies/nominatim/">usage policy</a>\nof OSM\'s Nominatim geocoding service. Please be aware that OSM\'s resources are\nlimited and shared between many users. The usage policy is …
```
=> hotfix: backend tests failing due to Nominatim server error:403

.github/dependabot.yml
Disabling PRs from dependabot while focusing on refactoring
=> Disabling PRs from dependabot

backend/services/messaging/message_service.py
- fix #6036
Images were not displaying in the email content properly. The reason for the issue was the comment was not being converted from markdown to HTML before sending to the user. To fix this now the comment are cleaned and converted from markdown to html.
=> fix: image displaying in email content for comments

frontend/src/api/stats.js, frontend/src/components/teamsAndOrgs/featureStats.js, frontend/src/config/index.js, frontend/src/network/tests/server-handlers.js
=> Add default changeset comment from env in ohsome API

README.md
- I think during a refactor to us mkdocs, the `screenshot.jpg` image in root was moved to `docs/images/`.
- The readme currently shows:
- I updated the link to reference the new location.
=> Update readme landing page screenshot location

frontend/src/components/projectDetail/downloadOsmData.js, frontend/yarn.lock
- Fixes #6345 
- https://github.com/hotosm/tasking-manager/pull/5721
This PR fixes the crash issue on osm download component which was caused due to the react,node upgrade
Issue:
After Fix :
1. Go into the Single Project Details.
2. Go Back to the projects lists.
3. Error Shows up.
=> feat: fixed osm download destroy issue

frontend/src/components/footer/index.js, frontend/src/components/footer/styles.scss
- Resolves #6402 
Add `AWS Logo` to the footer section.
=> Add `AWS Logo` to footer

frontend/src/components/projectCreate/index.js, frontend/src/components/projectCreate/messages.js, frontend/src/components/projectEdit/messages.js, frontend/src/views/projectEdit.js
=> Validate project name while creating/editing project

frontend/src/utils/countries.js, frontend/src/utils/internationalization.js, frontend/src/utils/tests/internationalization.test.js
=> Fix TM crash issue when language switched to Nederlands

frontend/src/components/projectCreate/projectCreationMap.js, frontend/src/components/projectEdit/priorityAreasForm.js, frontend/src/components/projects/projectsMap.js, frontend/src/components/taskSelection/map.js, frontend/src/components/userDetail/countriesMapped.js, frontend/src/hooks/UseMapboxSupportedLanguage.js
- Handle Mapbox unsupported locale by fallback to `en` language for unsupported ones
- Resolves #6429
=> Fix map page crash due to unsupported language error

migrations/versions/451f6bd05a19_.py
- Migration was getting error with an issue `cannot insert multiple commands into a prepared statement`
- Modified the migration file `451f6bd05a19_.py` to break the operations into multiple commands
From 
```python
def upgrade():
op.execute(
"""
DROP TRIGGER IF EXISTS tsvectorupdate ON project_info;
CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE ON project_info FOR EACH ROW EXECUTE PROCEDURE
tsvector_update_trigger(text_searchable, "pg_catalog.english", project_id_str, short_description, description)
"""
```
To
```python
def upgrade():
op.execute("DROP TRIGGER IF EXISTS tsvectorupdate ON project_info;")
op.execute(
"""
CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE ON project_info FOR EACH ROW EXECUTE PROCEDURE
tsvector_update_trigger(text_searchable, "pg_catalog.english", …
```
=> hot-fix: migrations error fix for multiple entry

.circleci/config.yml
Frontend build despite using a Large resource class (4 core, 8GB) takes 6-7 Minutes. We can use parallel workers with `-w` flag to get most out of available cpu cores.
Also cluttered warnings has been removed with `--silent`. This reduced CircleCI console logs from `5000` lines to `900`ish lines, making it easier to conceive.
For 4 cores, with some testing i found out that `-w 3` worked the best, setting `-w 4` or higher increased the test time also in cases freezed the VM instance.
With more CPU compute this can be improved, Testing on `X-large`  resource class had this time reduced to a minute.
=> Frontend tests now has parallel workers & removed cluttered warnings

.github/workflows/docker-image-push.yml
@eternaltyro 
- This PR uses the hotosm/gh-workflows image build workflow for the backend.
- Everything is preconfigured, including vulnerability scanning, correct tagging, ghcr registry caching, multi-arch builds (AMD64/ARM64).
- The frontend can be built in a similar way, but as the `tasking-manager.env` is copied into the image, either:
- The dockerfile would need to be updated to take ENV/ARG variables for everything instead.
- The workflow would have to be updated to support copying the .env in during the build (not recommended).
Did you attempt any other approaches that are not documented in code?
- 📖 Read the Tasking Manager Contributing Guide: …
=> Use hotosm/gh-workflows for container img builds

scripts/aws/cloudformation/tasking-manager.template.js
Fixes #6506
Use SSM ("Systems Manager") to find the newest AMI for Ubuntu 20.04.
The current method hardcodes a single AMI (in this case [ami-0aa2b7722dc1b5612](https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#ImageDetails:imageId=ami-0aa2b7722dc1b5612)). The problem with this method is that:
1. It is region specific (example: [ami-081a3b9eded47f0f3](https://us-west-1.console.aws.amazon.com/ec2/home?region=us-west-1#ImageDetails:imageId=ami-081a3b9eded47f0f3) is the equivalent AMI for us-west-1).
2. It doesn't automatically update/start with the (almost) latest updates (current latest version for us-west-1 is [ami-023e8dfe2208927a7](https://us-west-1.console.aws.amazon.com/ec2/home?region=us-west-1#Images:visibility=public-images;imageId=ami-023e8dfe2208927a7), which was …
=> Use AWS SSM instead of static AMI for Ubuntu base image in cloudformation

scripts/aws/cloudformation/tasking-manager.template.js
Reverts hotosm/tasking-manager#6514
I misread the error- It was actually a CircleCI OIDC permissions issue rather than one with the LauchTemplate itself. @tsmock thats why you didn't experience it!
=> Revert "Fix ssm permissions to pull the AMI"

frontend/package.json, frontend/yarn.lock, scripts/docker/Dockerfile.frontend
- The react-placeholder frontend dependency is out of date and unmaintained.
- It has a peerDependency lock for React `16 || 17`.
- Upgrading to React 18 has resulted in a conflict when installing frontend dependencies:
```
36.30 npm ERR! ERESOLVE unable to resolve dependency tree
36.30 npm ERR!
36.30 npm ERR! While resolving: TaskingManager-frontend@0.1.0
36.30 npm ERR! Found: react@18.3.1
36.30 npm ERR! node_modules/react
36.30 npm ERR!   react@"^18.2.0" from the root project
36.30 npm ERR!
36.30 npm ERR! Could not resolve dependency:
36.30 npm ERR! peer react@"^16.8.0 || ^17" from react-placeholder@4.1.0
36.30 npm ERR! node_modules/react-placeholder
36.30 npm ERR!   react-placeholder@"^4.1.0" from the root project
```
- The code is actually compatible with React 18, but the repo …
=> Fix react-placeholder peerDependency conflict (React v18)

docker-compose.override.sample.yml, docker-compose.yml
https://github.com/hotosm/tasking-manager/pull/6487
- Bind mounts
- Currently there are no bind-mounts to local files inside dev containers.
- Meaning we have to build every time to run tests or migrations.
- Mounting the files makes it easier for: hot reload, running tests, running migrations.
- I also removed the `version` param from docker-compose.yml files, as it's now obsolete.
- Moved the `upgrade` command out of the tm-migration entrypoint. Allow for override via `command: xxx` in docker-compose.
- 👷‍♀️ Create small PRs. In …
=> Add bind mounts to docker compose dev setup + migration command override

.circleci/config.yml
Fixing an error in the CircleCI config where we were hard-coding the AMI. Now that it's [set automatically by SSM](https://github.com/hotosm/tasking-manager/pull/6512), there is no need for this code. 
I've set this branch to deploy to dev, so if the deployment here passes then we are good to go.
=> Remove hard-coded ami option in favor of ssm in circleci

backend/api/interests/resources.py, backend/api/organisations/resources.py, backend/api/teams/resources.py, backend/models/dtos/team_dto.py, backend/models/postgis/team.py, backend/routes.py, backend/services/interests_service.py, backend/services/team_service.py
Teams apis refactored with encode databases and raw sql and now works asynchronously.
=> Fastapi refactor

backend/api/projects/resources.py, backend/models/dtos/user_dto.py, backend/models/postgis/project.py, backend/models/postgis/project_info.py, backend/models/postgis/user.py, backend/services/project_service.py, backend/services/users/user_service.py
Project detail summary and user touched projects api refactored with encode databases and raw sql.
=> Project detail summary and user touched projects api refactored

scripts/docker/Dockerfile.backend
- Upgrade pdm and pydebug versions
- Reduce RUN layers for apt steps
- Remove gunicorn workers parameter to allow for WEB_CONCURRENCY env
Gunicorn worker count is recommended to be `2-4 x $(NUM_CORES)` . Default is `1`. For production deployments we can rely on `WEB_CONCURRENCY` envvar to set the number of cores. 
- 🔠 Does this PR introduce or change any environment …
=> Cleanup backend dockerfile

docs/developers/development-setup.md
Fixes #4223
- We handle this by default in the docker compose config.
- If the user needs a *dockerised* postgres instance, that is running outside of the TM stack, they have an advanced use case & I am sure setting up a postgres container would be trivial to them.
=> Remove docs info about running independent dockerised postgres

docker-compose.yml
Many users were experiencing failed `tm-migration` container that resulted in `tm-backend` service left in `Created` state and never to `Started`.
This is mainly caused due to `healthcheck` in `tm-db` being too light, and only checks if the `postgresql` server is started or not.
This was one of the reason deployment attempts by Bash from Technology without borders was not successful.
Errors he received:
```
tasking-manager-main-tm-migration-1  |     return self.loaded_dbapi.connect(*cargs, **cparams)
tasking-manager-main-tm-migration-1  |   File "/home/appuser/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
tasking-manager-main-tm-migration-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
tasking-manager-main-tm-migration-1  | …
```
=> fix: db container healthchecks that was earlier broken

frontend/src/assets/styles/_extra.scss, frontend/src/components/button.js, frontend/src/components/partners/customDropdown.js, frontend/src/components/partners/leaderboard.js, frontend/src/components/partners/partners.js, frontend/src/components/partners/partnersResources.js, frontend/src/components/partners/styles.scss, frontend/src/locales/en.json, frontend/src/routes.js, frontend/src/views/partnersStats.js
- Fixes #6513 
Change design for `Partner Stats` page according to [this comment](https://github.com/hotosm/tasking-manager/issues/6513#issuecomment-2326767884).
**Changes-**
- Create dropdown menu popover for `Resources` section
- Move social icons to the banner
- Add a tab layout for switching between `Leaderboard` and `Map Swipe` (further integration) dashboard
- Remove `¿` icon from `New to Mapping?` button
**Before -**
**After -**
=> Redesign Leaderboard Stats Banner

backend/models/postgis/project.py, backend/services/project_search_service.py
Download CSV feature was unreasonably slow when the number of projects was high - 8 minutes for 2700 projects.
I moved the expensive DB calls outside the loop into just one query. It should be much faster now.
Use an DB with multiple users and lots of projects and task history. Preferably 2000+ projects in the search results. Press the download CSV button. Look for the right contributor count and the CSV file getting downloaded without a gateway timeout.
=> Fix: Speed up CSV generation by minimizing DB probes

backend/api/projects/resources.py, backend/models/dtos/project_dto.py, backend/models/postgis/custom_editors.py, backend/models/postgis/priority_area.py, backend/models/postgis/project.py, backend/models/postgis/project_info.py, backend/models/postgis/task.py, backend/services/project_admin_service.py, backend/services/recommendation_service.py
=> fix: project post api

backend/api/users/statistics.py, backend/models/dtos/stats_dto.py, backend/services/project_search_service.py
Project action filter and user stats fixed.
=> fix: Project action filter and user stats

.circleci/config.yml
This change sets the deployment backend server environment to use debian AMI
=> Set AMI to debian for staging and prod deployment

scripts/aws/cloudformation/tasking-manager.template.js
None
I noticed that snapshot backups are not being tagged. This change will fix that.
=> Enable copying tags to snapshots

example.env
Removes incorrect and conflicting instruction about not using scheme on "next two variables". Second example does indeed include scheme and first example produces an incorrect link without scheme included.
Example: Fixes #6165
See above.
Notes for the reviewer. Probably look at your own variables in production. Barring that, set up a server using these instructions and check the website link in the upper right header; the domain name will appear as a path on the base server domain not as its own domain. 
- 👷‍♀️ Create small PRs. In most …
=> Addresses #6165 by removing incorrect and conflicting instruction

backend/api/projects/resources.py, backend/models/postgis/project.py, backend/models/postgis/team.py, backend/services/organisation_service.py, backend/services/project_admin_service.py, backend/services/team_service.py
Fixes:
Project, organisation teams deletion.
Licence Imagery patch.
=> Project, organisation teams deletion and other fixes

backend/api/comments/resources.py, backend/api/organisations/resources.py, backend/models/dtos/interests_dto.py, backend/models/dtos/message_dto.py, backend/models/postgis/project.py, backend/models/postgis/utils.py, backend/services/interests_service.py, backend/services/messaging/message_service.py, backend/services/messaging/smtp_service.py, backend/services/users/authentication_service.py, backend/services/users/user_service.py
Register user fixed.
Retrieve org by id and slug made to one endpoint.
User interests refactored and removed ListProjectInterestDTO.
=> Register user, retrieve org by id and slug and user interests refactored

frontend/src/api/projects.js, frontend/src/components/footer/index.js, frontend/src/components/projectDetail/footer.js, frontend/src/components/projectDetail/index.js, frontend/src/components/projectDetail/messages.js, frontend/src/components/projectDetail/styles.scss, frontend/src/components/taskSelection/footer.js, frontend/src/components/taskSelection/index.js, frontend/src/components/taskSelection/tabSelector.js, frontend/src/components/taskSelection/tests/footer.test.js, frontend/src/components/taskSelection/tests/index.test.js, frontend/src/components/taskSelection/tests/tabSelector.test.js, frontend/src/hooks/UseFilterContributors.js, frontend/src/routes.js, frontend/src/views/taskSelection.js, frontend/src/views/tests/taskSelection.test.js
- Resolves #6302 
This PR enables user to share the task instructions URL of a project without having to log in to Tasking Manager.
**Key Changes**
- Add a Link button `View Project Specific Instructions` to the bottom of `Description` section
- Create different URL routes for `/instructions` and `/contributions`
- Show `Project Detail Map` instead of `Task Map` for `Instructions` page when not logged in
=> View Task Instructions without login

backend/api/teams/actions.py, backend/services/messaging/message_service.py, backend/services/team_service.py
=> fix: Join team by request

backend/api/projects/actions.py, backend/api/teams/actions.py, backend/models/dtos/message_dto.py, backend/models/postgis/project.py, backend/models/postgis/team.py, backend/services/project_search_service.py, backend/services/team_service.py
Project search and deletion fixed.
=> fix: Project search and deletion.

backend/models/postgis/project.py, backend/services/project_admin_service.py
Tasks added to cloned projects.
=> fix: Tasks added to cloned projects

backend/api/projects/resources.py, backend/models/dtos/project_dto.py, backend/models/postgis/project.py, backend/services/project_admin_service.py, backend/services/project_search_service.py
* Export projects as csv
* Project partnership filters
* Changeset comment population on project creation and update
* Cleanups
=> * Export projects as csv * Project partnership filters * Changeset comment population on project creation and update * Cleanups

.circleci/config.yml, frontend/src/views/teams.js
- Resolves  #6541, #6629,  #6631
This PR fixes the above mentioned issues.
**Changes**
- Fetch only `published projects` in `Team Members` page
- Do not allow user to access `Teams` page without login
=> Fix Team Members page issues

frontend/src/assets/styles/_extra.scss, frontend/src/components/partnerMapswipeStats/contributionsGrid.js, frontend/src/components/partnerMapswipeStats/dateFilter.js, frontend/src/components/partnerMapswipeStats/messages.js, frontend/src/components/partnerMapswipeStats/overview.js, frontend/src/views/partnersMapswipeStats.js
- Resolves #6620
Add `Date Filter` for date-wise filter of charts & visualizations in MapSwipe Partners page.
=> Add Date Filter to MapSwipe Partners Page

.github/workflows/ecs-deploy.yml
Bumped aws-actions/amazon-ecs-deploy-task-definition version to V2 as v1 was throwing `Error: Failed to register task definition in ECS: Unexpected key 'enableFaultInjection' found in params` error
=> fix: update aws-actions/amazon-ecs-deploy-task-definition to v2

frontend/src/api/projects.ts, frontend/src/components/svgIcons/grid.tsx, frontend/src/components/taskSelection/map.jsx, frontend/src/utils/internationalization.jsx
Fixes:
- i18n not working at all, was importing just the module, not the contents
- persist project data between renders on project page - broken by tanstack query bump
- invalid svg property on grid icon - renamed property to camel case
- missing ternary when accessing authDetails in taskSelection causing runtime error/crash - added ternary
=> typescript-vite: fix(frontend): i18n, projects list, icon, tasks

frontend/vite.config.ts
Switches frontend port from 5173 to 3000, as we already use 3000 in our env's.
Requested by @royallsilwallz
=> typescript-vite: chore(frontend): switch port from 5173 -> 3000

example.env, frontend/src/api/stats.js, frontend/src/components/partners/partnersActivity.js, frontend/src/components/partners/partnersProgresBar.js, frontend/src/components/teamsAndOrgs/featureStats.js, frontend/src/config/index.js, frontend/src/config/tests/config.test.js, frontend/src/network/tests/server-handlers.js, frontend/src/views/partnersStats.js
- Fixes #6681 
This PR resolves the wrong URL for opening ohsomeNow stats page on Bar chart label click.
**Changes**
- Break down ohsomeNow stats environment variables to `OHSOME_STATS_BASE_URL` & `OHSOME_STATS_API_URL`
- Update `example.env`
- Correct query param `hashtag` in the ohsomeNow redirect URL
This PR requires some environment variables to be changed on the CI / development. 
Following env vars should be altered -
```
OHSOME_STATS_BASE_URL=https://stats.now.ohsome.org
OHSOME_STATS_API_URL=https://stats.now.ohsome.org/api
```
cc - @dakotabenjamin
=> Fix ohsomeNow URL link on Bar Chart click in Partner Stats page

backend/services/project_search_service.py
Project action and permission filters fixed.
=> fix: project action and permission filters

.circleci/config.yml, scripts/docker/Dockerfile.frontend, scripts/docker/Dockerfile.frontend_development
Update to Node 22 from Node 18. Node 18 is losing support this year (2025-04-30).
Of some interest, node now has a built-in test runner (as of node 20).
Node on Linux
||Node Version|EOL|
|---|---|---|
|Ubuntu 20.04|v10.19.0|2025-04|
|Ubuntu 22.04|v12.22.9|2027-04|
|Ubuntu 24.04|v18.19.1|2029-04|
Realistically, that only matters in a dev environment -- production environments _should_ be using static builds.
1. Install node 22
2. Install dependencies
3. `CI=true yarn test` -- note: node
=> Update node to node 22 from node 18

backend/cron_jobs.py
Misfire gracetime removed from cron interval trigger.
=> fix: misfire gracetime removed from cron interval trigger

backend/models/dtos/partner_dto.py
Partner logo url changed to str instead of httpurl type as invalid url was causing serialization error.
=> Partner logo url changed to str instead of httpurl type

scripts/aws/infra/staging/purgeable/ecs-cron/terragrunt.hcl, scripts/aws/infra/staging/purgeable/ecs/terragrunt.hcl
- Adds option to make ECS task executable. Disabled by default. Can be overridden from `terragrunt.hcl` inside purgable.
=> feat: add option to enable or disable execute

.github/workflows/backend-build-deploy.yml, .github/workflows/frontend-build-deploy.yml, .github/workflows/frontend-deploy.yml, example.env, scripts/aws/infra/_envcommon/cloudfront.hcl, scripts/aws/infra/_envcommon/s3.hcl, scripts/aws/infra/develop/non-purgeable/cloudfront/terragrunt.hcl, scripts/aws/infra/develop/non-purgeable/s3/terragrunt.hcl, scripts/aws/infra/infra.env.example, scripts/aws/infra/staging/non-purgeable/cloudfront/terragrunt.hcl, scripts/aws/infra/staging/non-purgeable/s3/terragrunt.hcl
A brief description of how this solves the issue.
Did you attempt any other approaches that are not documented in code?
- 🔠 Does this PR introduce or change any environment variables? If so, make sure to specify this change in the description.
=> Merge `develop` to `staging`

Dockerfile, docker-compose.yml, pdm.lock, pyproject.toml
gevent version upgraded from 22.10.2 to 23.9.0 to fix the vulnerability issue arising while container scan.
=> gevent version upgrade for vulnerability issue

scripts/aws/infra/root.hcl
The default tags in the modules are lowercase, so this was causing them to be set blank and new (untracked) tags to be set by the deployment.
=> Change default tags to lowercase for terragrunt infrastructure

frontend/src/components/projectCreate/index.js
- Fixes #6644
This PR resolves "error message not displaying on error" in Create Project page.
=> Fix Error Message not displaying issue in Create Project page

backend/services/project_service.py
Add missing db connection param in allowed users for mapping on private projects.
=> fix: Add missing db connection param in allowed users for mapping on private projects

frontend/src/components/projectDetail/styles.scss
- [X ] 🐛 Bug Fix
Example: Fixes #6806 
On the project details page, the height of the container for the map and project details to the left of it was a fixed height so that the nav bar, footer, and this container would nicely take up all the view port height. Changing the fixed height to min height allows the container to still do this when the page is opened at normal zoom, but allows it to grow downward with very high zoom / scaling rather than disappearing the intro text and overlapping visual elements.
At very high zoom, intro text is gone and visual elements overlap.
At very high zoom, intro text is present and visual elements do not overlap.
Maintains visual style with the container taking up 100% of vertical space minus the nav bar and footer.
Go to a project at /projects/12345 and …
=> Fix visual elements overlapping and intro text too small or gone with high zoom on project details page

frontend/src/components/projectCard/priorityBox.js, frontend/src/components/projectCard/projectCard.js
Fixes issue #6674 
This PR addresses a longstanding issue where markdown in the short descriptions of project cards (e.g., URLs) was not rendered correctly. This bug caused markdown syntax (like [text](URL)) to display as plain text instead of being interpreted as clickable links.
##Changes made
Updated the ProjectCard component to ensure the shortDescription field renders markdown properly.
Integrated a markdown-to-HTML parser (react-markdown) for safe and efficient markdown rendering.
=> Fix: Render markdown correctly for short descriptions

frontend/src/components/projectCard/projectCard.js, frontend/src/components/projectCard/styles.scss
Fixes #6674 
This PR enables markdown rendering in the project card's short description and ensures rendered markdown elements inherit typography styles from parent's for consistent and structured content display.
=> Fix:  Markdown Parsing In Project Card Component

frontend/src/components/projects/clearFilters.js, frontend/src/components/projects/exploreProjectsTable.js, frontend/src/components/projects/messages.js, frontend/src/components/projects/projectNav.js, frontend/src/components/projects/projectsActionFilter.js, frontend/src/components/projects/projectsStatusFilter.js, frontend/src/components/projects/tests/projectsActionFilter.test.js, frontend/src/hooks/UseProjectsQueryAPI.js, frontend/src/locales/en.json
- Resolves #6807 
This PR resolves the above mentioned issues.
**Changes**
- Separate `Progress` column into `Percent mapped` & `Percent validated`
- Move `Published`, `Archived`, `Draft` into `Project Status` dropdown
- Allow Draft filter only for admins and organization admins
- Remove `DRAFT` filter on the URL for non-admins
- Fix list/grid view not persisting on Clear filter
- Fix `view` param not persisting on More Filter
- Adjust test cases for for the changes done
=> Improvements to Explore Projects page

backend/models/postgis/project.py
Fixes #6852
When the project was cloned, the new changeset included all the previous changeset comment including the original project's default changeset comment too which is now discarded in the cloned project.
=> Default changeset to discard previous default changeset comment when the project is cloned

frontend/src/components/dropdown.js, frontend/src/components/taskSelection/taskActivity.js
- Resolves #6509 
This PR adds support for right-aligned dropdowns via a new `toRight` prop, applied to the task data menu dropdown.
**Changes**
- Updates styling to align the dropdown items to the right when `toRight` is true
- Passes `toRight` prop to the task data menu dropdown for right alignment
=> Align task data menu dropdown to the right

frontend/src/views/partnersMapswipeStats.js
Fixes:- #6989 
Removed `timeSpentContributing` from `messages` in a previous release because of duplication, but one component was still referencing it, causing a runtime error.
This commit updates the reference to `mapSwipeMessages.timeSpentContributing` to match the current message structure and fix the missing key issue.
=> Correct localization key for `timeSpentContributing`

frontend/src/components/projectDetail/downloadButtons.js, frontend/src/components/projectDetail/tests/downloadButtons.test.js, frontend/src/components/taskSelection/tests/resourcesTab.test.js
Example: Fixes #6984 
This PR replaces the direct anchor tag-based file download with a `fetch`-based approach that allows secure downloading of the task grid file. The request now conditionally includes an Authorization token in the headers, enabling access to protected endpoints.
**Changes:**
- Replaced `<a>` download link with a `fetch` request for downloading the `.geojson` task file.
- Conditionally attach the `Authorization` header.
- Use `Blob` to handle the response and trigger a file download programmatically.
- Removed test cases related to the anchor tag-based file download
=> Download task grid file with auth token using fetch and Blob

frontend/src/components/header/styles.scss, frontend/src/components/localeSelect.js
Fixes: #6508 
This PR removes the `.settings-width` class from the localization dropdown. The fixed width was causing layout issues—specifically, the login button would overlap when the localization text was long. Removing the class allows the dropdown to size naturally and prevents content overlap.
=> Remove fixed width causing login button overlap.

backend/models/postgis/task.py, tests/api/unit/services/test_project_admin_service.py
Fixes #7009 
When a project's all tasks were reset, the project id was not populated in the task history causing it to revert to the last action before it was reset resulting in ambiguous actions.
=> project id in reset task action while setting action history

backend/models/dtos/mapping_level_dto.py, backend/models/postgis/user.py, backend/services/project_search_service.py, frontend/src/components/levels/index.js, frontend/src/components/projectEdit/permissionsBlock.js, frontend/src/components/user/list.js
=> Restore three requested functionality related to super mapper

backend/api/projects/activities.py, backend/api/projects/contributions.py, backend/api/projects/resources.py, backend/api/tasks/resources.py, backend/models/postgis/user.py, migrations/versions/4489b9e235f8_.py, tests/api/unit/services/mapping_levels/test_mapping_level_service.py, tests/api/unit/services/users/test_user_service.py
Uses CASCADE for relationships that come from voting related tables so that they don't interfere when deleting a level with no users.
=> fix problem when deleting level with votes
